// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Specifies the jobs to cancel and the reason for the cancellation.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct CancelJobsInput {
    /// <p>An array of up to 50 Batch job IDs of the jobs to cancel.</p>
    pub jobs: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    /// <p>A message to attach to the job that explains the reason for cancelling it. This message is returned by future <code>DescribeJobs</code> operations on the job. It is also recorded in the Batch activity logs.</p>
    /// <p>This parameter has a limit of 1024 characters.</p>
    pub reason: ::std::option::Option<::std::string::String>,
}
impl CancelJobsInput {
    /// <p>An array of up to 50 Batch job IDs of the jobs to cancel.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.jobs.is_none()`.
    pub fn jobs(&self) -> &[::std::string::String] {
        self.jobs.as_deref().unwrap_or_default()
    }
    /// <p>A message to attach to the job that explains the reason for cancelling it. This message is returned by future <code>DescribeJobs</code> operations on the job. It is also recorded in the Batch activity logs.</p>
    /// <p>This parameter has a limit of 1024 characters.</p>
    pub fn reason(&self) -> ::std::option::Option<&str> {
        self.reason.as_deref()
    }
}
impl CancelJobsInput {
    /// Creates a new builder-style object to manufacture [`CancelJobsInput`](crate::operation::cancel_jobs::CancelJobsInput).
    pub fn builder() -> crate::operation::cancel_jobs::builders::CancelJobsInputBuilder {
        crate::operation::cancel_jobs::builders::CancelJobsInputBuilder::default()
    }
}

/// A builder for [`CancelJobsInput`](crate::operation::cancel_jobs::CancelJobsInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct CancelJobsInputBuilder {
    pub(crate) jobs: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    pub(crate) reason: ::std::option::Option<::std::string::String>,
}
impl CancelJobsInputBuilder {
    /// Appends an item to `jobs`.
    ///
    /// To override the contents of this collection use [`set_jobs`](Self::set_jobs).
    ///
    /// <p>An array of up to 50 Batch job IDs of the jobs to cancel.</p>
    pub fn jobs(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        let mut v = self.jobs.unwrap_or_default();
        v.push(input.into());
        self.jobs = ::std::option::Option::Some(v);
        self
    }
    /// <p>An array of up to 50 Batch job IDs of the jobs to cancel.</p>
    pub fn set_jobs(mut self, input: ::std::option::Option<::std::vec::Vec<::std::string::String>>) -> Self {
        self.jobs = input;
        self
    }
    /// <p>An array of up to 50 Batch job IDs of the jobs to cancel.</p>
    pub fn get_jobs(&self) -> &::std::option::Option<::std::vec::Vec<::std::string::String>> {
        &self.jobs
    }
    /// <p>A message to attach to the job that explains the reason for cancelling it. This message is returned by future <code>DescribeJobs</code> operations on the job. It is also recorded in the Batch activity logs.</p>
    /// <p>This parameter has a limit of 1024 characters.</p>
    /// This field is required.
    pub fn reason(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.reason = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>A message to attach to the job that explains the reason for cancelling it. This message is returned by future <code>DescribeJobs</code> operations on the job. It is also recorded in the Batch activity logs.</p>
    /// <p>This parameter has a limit of 1024 characters.</p>
    pub fn set_reason(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.reason = input;
        self
    }
    /// <p>A message to attach to the job that explains the reason for cancelling it. This message is returned by future <code>DescribeJobs</code> operations on the job. It is also recorded in the Batch activity logs.</p>
    /// <p>This parameter has a limit of 1024 characters.</p>
    pub fn get_reason(&self) -> &::std::option::Option<::std::string::String> {
        &self.reason
    }
    /// Consumes the builder and constructs a [`CancelJobsInput`](crate::operation::cancel_jobs::CancelJobsInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::cancel_jobs::CancelJobsInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::cancel_jobs::CancelJobsInput {
            jobs: self.jobs,
            reason: self.reason,
        })
    }
}
