// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`CancelJobs`](crate::operation::cancel_jobs::builders::CancelJobsFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`jobs(impl Into<String>)`](crate::operation::cancel_jobs::builders::CancelJobsFluentBuilder::jobs) / [`set_jobs(Option<Vec::<String>>)`](crate::operation::cancel_jobs::builders::CancelJobsFluentBuilder::set_jobs):<br>required: **true**<br><p>An array of up to 50 Batch job IDs of the jobs to cancel.</p><br>
    ///   - [`reason(impl Into<String>)`](crate::operation::cancel_jobs::builders::CancelJobsFluentBuilder::reason) / [`set_reason(Option<String>)`](crate::operation::cancel_jobs::builders::CancelJobsFluentBuilder::set_reason):<br>required: **true**<br><p>A message to attach to the job that explains the reason for cancelling it. This message is returned by future <code>DescribeJobs</code> operations on the job. It is also recorded in the Batch activity logs.</p> <p>This parameter has a limit of 1024 characters.</p><br>
    /// - On success, responds with [`CancelJobsOutput`](crate::operation::cancel_jobs::CancelJobsOutput) with field(s):
    ///   - [`successful(Option<Vec::<String>>)`](crate::operation::cancel_jobs::CancelJobsOutput::successful): <p>A list of the job IDs whose cancellation request was accepted.</p>
    ///   - [`errors(Option<Vec::<CancelJobsErrorDetail>>)`](crate::operation::cancel_jobs::CancelJobsOutput::errors): <p>A list of <code>CancelJobsErrorDetail</code> items, one for each job that couldn't be cancelled. Each item includes the job ID along with a code and message that describe why the job wasn't cancelled.</p>
    /// - On failure, responds with [`SdkError<CancelJobsError>`](crate::operation::cancel_jobs::CancelJobsError)
    pub fn cancel_jobs(&self) -> crate::operation::cancel_jobs::builders::CancelJobsFluentBuilder {
        crate::operation::cancel_jobs::builders::CancelJobsFluentBuilder::new(self.handle.clone())
    }
}
