// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`TerminateJobs`](crate::operation::terminate_jobs::builders::TerminateJobsFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`jobs(impl Into<String>)`](crate::operation::terminate_jobs::builders::TerminateJobsFluentBuilder::jobs) / [`set_jobs(Option<Vec::<String>>)`](crate::operation::terminate_jobs::builders::TerminateJobsFluentBuilder::set_jobs):<br>required: **true**<br><p>An array of up to 50 Batch job IDs of the jobs to terminate.</p><br>
    ///   - [`reason(impl Into<String>)`](crate::operation::terminate_jobs::builders::TerminateJobsFluentBuilder::reason) / [`set_reason(Option<String>)`](crate::operation::terminate_jobs::builders::TerminateJobsFluentBuilder::set_reason):<br>required: **true**<br><p>A message to attach to the job that explains the reason for terminating it. This message is returned by future <code>DescribeJobs</code> operations on the job. It is also recorded in the Batch activity logs.</p> <p>This parameter has a limit of 1024 characters.</p><br>
    /// - On success, responds with [`TerminateJobsOutput`](crate::operation::terminate_jobs::TerminateJobsOutput) with field(s):
    ///   - [`successful(Option<Vec::<String>>)`](crate::operation::terminate_jobs::TerminateJobsOutput::successful): <p>A list of the job IDs whose termination request was accepted.</p>
    ///   - [`errors(Option<Vec::<TerminateJobsErrorDetail>>)`](crate::operation::terminate_jobs::TerminateJobsOutput::errors): <p>A list of <code>TerminateJobsErrorDetail</code> items, one for each job that couldn't be terminated. Each item includes the job ID along with a code and message that describe why the job wasn't terminated.</p>
    /// - On failure, responds with [`SdkError<TerminateJobsError>`](crate::operation::terminate_jobs::TerminateJobsError)
    pub fn terminate_jobs(&self) -> crate::operation::terminate_jobs::builders::TerminateJobsFluentBuilder {
        crate::operation::terminate_jobs::builders::TerminateJobsFluentBuilder::new(self.handle.clone())
    }
}
