// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`TerminateServiceJobs`](crate::operation::terminate_service_jobs::builders::TerminateServiceJobsFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`jobs(impl Into<String>)`](crate::operation::terminate_service_jobs::builders::TerminateServiceJobsFluentBuilder::jobs) / [`set_jobs(Option<Vec::<String>>)`](crate::operation::terminate_service_jobs::builders::TerminateServiceJobsFluentBuilder::set_jobs):<br>required: **true**<br><p>An array of up to 50 service job IDs of the service jobs to terminate.</p><br>
    ///   - [`reason(impl Into<String>)`](crate::operation::terminate_service_jobs::builders::TerminateServiceJobsFluentBuilder::reason) / [`set_reason(Option<String>)`](crate::operation::terminate_service_jobs::builders::TerminateServiceJobsFluentBuilder::set_reason):<br>required: **true**<br><p>A message to attach to the service job that explains the reason for terminating it. This message is returned by <code>DescribeServiceJob</code> operations on the service job.</p><br>
    /// - On success, responds with [`TerminateServiceJobsOutput`](crate::operation::terminate_service_jobs::TerminateServiceJobsOutput) with field(s):
    ///   - [`successful(Option<Vec::<String>>)`](crate::operation::terminate_service_jobs::TerminateServiceJobsOutput::successful): <p>A list of the service job IDs whose termination request was accepted.</p>
    ///   - [`errors(Option<Vec::<TerminateServiceJobsErrorDetail>>)`](crate::operation::terminate_service_jobs::TerminateServiceJobsOutput::errors): <p>A list of <code>TerminateServiceJobsErrorDetail</code> items, one for each service job that couldn't be terminated. Each item includes the service job ID along with a code and message that describe why the service job wasn't terminated.</p>
    /// - On failure, responds with [`SdkError<TerminateServiceJobsError>`](crate::operation::terminate_service_jobs::TerminateServiceJobsError)
    pub fn terminate_service_jobs(
        &self,
    ) -> crate::operation::terminate_service_jobs::builders::TerminateServiceJobsFluentBuilder {
        crate::operation::terminate_service_jobs::builders::TerminateServiceJobsFluentBuilder::new(self.handle.clone())
    }
}
