// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use ::aws_types::request_id::RequestId;

#[cfg(feature = "op_associate_email_identity_certificate")]
/// Types for the `AssociateEmailIdentityCertificate` operation.
pub mod associate_email_identity_certificate;

#[cfg(feature = "op_batch_get_metric_data")]
/// Types for the `BatchGetMetricData` operation.
pub mod batch_get_metric_data;

#[cfg(feature = "op_cancel_export_job")]
/// Types for the `CancelExportJob` operation.
pub mod cancel_export_job;

#[cfg(feature = "op_create_configuration_set")]
/// Types for the `CreateConfigurationSet` operation.
pub mod create_configuration_set;

#[cfg(feature = "op_create_configuration_set_event_destination")]
/// Types for the `CreateConfigurationSetEventDestination` operation.
pub mod create_configuration_set_event_destination;

#[cfg(feature = "op_create_contact")]
/// Types for the `CreateContact` operation.
pub mod create_contact;

#[cfg(feature = "op_create_contact_list")]
/// Types for the `CreateContactList` operation.
pub mod create_contact_list;

#[cfg(feature = "op_create_custom_verification_email_template")]
/// Types for the `CreateCustomVerificationEmailTemplate` operation.
pub mod create_custom_verification_email_template;

#[cfg(feature = "op_create_dedicated_ip_pool")]
/// Types for the `CreateDedicatedIpPool` operation.
pub mod create_dedicated_ip_pool;

#[cfg(feature = "op_create_deliverability_test_report")]
/// Types for the `CreateDeliverabilityTestReport` operation.
pub mod create_deliverability_test_report;

#[cfg(feature = "op_create_email_identity")]
/// Types for the `CreateEmailIdentity` operation.
pub mod create_email_identity;

#[cfg(feature = "op_create_email_identity_policy")]
/// Types for the `CreateEmailIdentityPolicy` operation.
pub mod create_email_identity_policy;

#[cfg(feature = "op_create_email_template")]
/// Types for the `CreateEmailTemplate` operation.
pub mod create_email_template;

#[cfg(feature = "op_create_export_job")]
/// Types for the `CreateExportJob` operation.
pub mod create_export_job;

#[cfg(feature = "op_create_import_job")]
/// Types for the `CreateImportJob` operation.
pub mod create_import_job;

#[cfg(feature = "op_create_multi_region_endpoint")]
/// Types for the `CreateMultiRegionEndpoint` operation.
pub mod create_multi_region_endpoint;

#[cfg(feature = "op_create_tenant")]
/// Types for the `CreateTenant` operation.
pub mod create_tenant;

#[cfg(feature = "op_create_tenant_resource_association")]
/// Types for the `CreateTenantResourceAssociation` operation.
pub mod create_tenant_resource_association;

#[cfg(feature = "op_delete_configuration_set")]
/// Types for the `DeleteConfigurationSet` operation.
pub mod delete_configuration_set;

#[cfg(feature = "op_delete_configuration_set_event_destination")]
/// Types for the `DeleteConfigurationSetEventDestination` operation.
pub mod delete_configuration_set_event_destination;

#[cfg(feature = "op_delete_contact")]
/// Types for the `DeleteContact` operation.
pub mod delete_contact;

#[cfg(feature = "op_delete_contact_list")]
/// Types for the `DeleteContactList` operation.
pub mod delete_contact_list;

#[cfg(feature = "op_delete_custom_verification_email_template")]
/// Types for the `DeleteCustomVerificationEmailTemplate` operation.
pub mod delete_custom_verification_email_template;

#[cfg(feature = "op_delete_dedicated_ip_pool")]
/// Types for the `DeleteDedicatedIpPool` operation.
pub mod delete_dedicated_ip_pool;

#[cfg(feature = "op_delete_email_identity")]
/// Types for the `DeleteEmailIdentity` operation.
pub mod delete_email_identity;

#[cfg(feature = "op_delete_email_identity_policy")]
/// Types for the `DeleteEmailIdentityPolicy` operation.
pub mod delete_email_identity_policy;

#[cfg(feature = "op_delete_email_template")]
/// Types for the `DeleteEmailTemplate` operation.
pub mod delete_email_template;

#[cfg(feature = "op_delete_multi_region_endpoint")]
/// Types for the `DeleteMultiRegionEndpoint` operation.
pub mod delete_multi_region_endpoint;

#[cfg(feature = "op_delete_suppressed_destination")]
/// Types for the `DeleteSuppressedDestination` operation.
pub mod delete_suppressed_destination;

#[cfg(feature = "op_delete_tenant")]
/// Types for the `DeleteTenant` operation.
pub mod delete_tenant;

#[cfg(feature = "op_delete_tenant_resource_association")]
/// Types for the `DeleteTenantResourceAssociation` operation.
pub mod delete_tenant_resource_association;

#[cfg(feature = "op_disassociate_email_identity_certificate")]
/// Types for the `DisassociateEmailIdentityCertificate` operation.
pub mod disassociate_email_identity_certificate;

#[cfg(feature = "op_get_account")]
/// Types for the `GetAccount` operation.
pub mod get_account;

#[cfg(feature = "op_get_blacklist_reports")]
/// Types for the `GetBlacklistReports` operation.
pub mod get_blacklist_reports;

#[cfg(feature = "op_get_configuration_set")]
/// Types for the `GetConfigurationSet` operation.
pub mod get_configuration_set;

#[cfg(feature = "op_get_configuration_set_event_destinations")]
/// Types for the `GetConfigurationSetEventDestinations` operation.
pub mod get_configuration_set_event_destinations;

#[cfg(feature = "op_get_contact")]
/// Types for the `GetContact` operation.
pub mod get_contact;

#[cfg(feature = "op_get_contact_list")]
/// Types for the `GetContactList` operation.
pub mod get_contact_list;

#[cfg(feature = "op_get_custom_verification_email_template")]
/// Types for the `GetCustomVerificationEmailTemplate` operation.
pub mod get_custom_verification_email_template;

#[cfg(feature = "op_get_dedicated_ip")]
/// Types for the `GetDedicatedIp` operation.
pub mod get_dedicated_ip;

#[cfg(feature = "op_get_dedicated_ip_pool")]
/// Types for the `GetDedicatedIpPool` operation.
pub mod get_dedicated_ip_pool;

#[cfg(feature = "op_get_dedicated_ips")]
/// Types for the `GetDedicatedIps` operation.
pub mod get_dedicated_ips;

#[cfg(feature = "op_get_deliverability_dashboard_options")]
/// Types for the `GetDeliverabilityDashboardOptions` operation.
pub mod get_deliverability_dashboard_options;

#[cfg(feature = "op_get_deliverability_test_report")]
/// Types for the `GetDeliverabilityTestReport` operation.
pub mod get_deliverability_test_report;

#[cfg(feature = "op_get_domain_deliverability_campaign")]
/// Types for the `GetDomainDeliverabilityCampaign` operation.
pub mod get_domain_deliverability_campaign;

#[cfg(feature = "op_get_domain_statistics_report")]
/// Types for the `GetDomainStatisticsReport` operation.
pub mod get_domain_statistics_report;

#[cfg(feature = "op_get_email_address_insights")]
/// Types for the `GetEmailAddressInsights` operation.
pub mod get_email_address_insights;

#[cfg(feature = "op_get_email_identity")]
/// Types for the `GetEmailIdentity` operation.
pub mod get_email_identity;

#[cfg(feature = "op_get_email_identity_policies")]
/// Types for the `GetEmailIdentityPolicies` operation.
pub mod get_email_identity_policies;

#[cfg(feature = "op_get_email_template")]
/// Types for the `GetEmailTemplate` operation.
pub mod get_email_template;

#[cfg(feature = "op_get_export_job")]
/// Types for the `GetExportJob` operation.
pub mod get_export_job;

#[cfg(feature = "op_get_import_job")]
/// Types for the `GetImportJob` operation.
pub mod get_import_job;

#[cfg(feature = "op_get_message_insights")]
/// Types for the `GetMessageInsights` operation.
pub mod get_message_insights;

#[cfg(feature = "op_get_multi_region_endpoint")]
/// Types for the `GetMultiRegionEndpoint` operation.
pub mod get_multi_region_endpoint;

#[cfg(feature = "op_get_reputation_entity")]
/// Types for the `GetReputationEntity` operation.
pub mod get_reputation_entity;

#[cfg(feature = "op_get_suppressed_destination")]
/// Types for the `GetSuppressedDestination` operation.
pub mod get_suppressed_destination;

#[cfg(feature = "op_get_tenant")]
/// Types for the `GetTenant` operation.
pub mod get_tenant;

#[cfg(feature = "op_list_configuration_sets")]
/// Types for the `ListConfigurationSets` operation.
pub mod list_configuration_sets;

#[cfg(feature = "op_list_contact_lists")]
/// Types for the `ListContactLists` operation.
pub mod list_contact_lists;

#[cfg(feature = "op_list_contacts")]
/// Types for the `ListContacts` operation.
pub mod list_contacts;

#[cfg(feature = "op_list_custom_verification_email_templates")]
/// Types for the `ListCustomVerificationEmailTemplates` operation.
pub mod list_custom_verification_email_templates;

#[cfg(feature = "op_list_dedicated_ip_pools")]
/// Types for the `ListDedicatedIpPools` operation.
pub mod list_dedicated_ip_pools;

#[cfg(feature = "op_list_deliverability_test_reports")]
/// Types for the `ListDeliverabilityTestReports` operation.
pub mod list_deliverability_test_reports;

#[cfg(feature = "op_list_domain_deliverability_campaigns")]
/// Types for the `ListDomainDeliverabilityCampaigns` operation.
pub mod list_domain_deliverability_campaigns;

#[cfg(feature = "op_list_email_identities")]
/// Types for the `ListEmailIdentities` operation.
pub mod list_email_identities;

#[cfg(feature = "op_list_email_identity_certificates")]
/// Types for the `ListEmailIdentityCertificates` operation.
pub mod list_email_identity_certificates;

#[cfg(feature = "op_list_email_templates")]
/// Types for the `ListEmailTemplates` operation.
pub mod list_email_templates;

#[cfg(feature = "op_list_export_jobs")]
/// Types for the `ListExportJobs` operation.
pub mod list_export_jobs;

#[cfg(feature = "op_list_import_jobs")]
/// Types for the `ListImportJobs` operation.
pub mod list_import_jobs;

#[cfg(feature = "op_list_multi_region_endpoints")]
/// Types for the `ListMultiRegionEndpoints` operation.
pub mod list_multi_region_endpoints;

#[cfg(feature = "op_list_recommendations")]
/// Types for the `ListRecommendations` operation.
pub mod list_recommendations;

#[cfg(feature = "op_list_reputation_entities")]
/// Types for the `ListReputationEntities` operation.
pub mod list_reputation_entities;

#[cfg(feature = "op_list_resource_tenants")]
/// Types for the `ListResourceTenants` operation.
pub mod list_resource_tenants;

#[cfg(feature = "op_list_suppressed_destinations")]
/// Types for the `ListSuppressedDestinations` operation.
pub mod list_suppressed_destinations;

#[cfg(feature = "op_list_tags_for_resource")]
/// Types for the `ListTagsForResource` operation.
pub mod list_tags_for_resource;

#[cfg(feature = "op_list_tenant_resources")]
/// Types for the `ListTenantResources` operation.
pub mod list_tenant_resources;

#[cfg(feature = "op_list_tenants")]
/// Types for the `ListTenants` operation.
pub mod list_tenants;

#[cfg(feature = "op_put_account_dedicated_ip_warmup_attributes")]
/// Types for the `PutAccountDedicatedIpWarmupAttributes` operation.
pub mod put_account_dedicated_ip_warmup_attributes;

#[cfg(feature = "op_put_account_details")]
/// Types for the `PutAccountDetails` operation.
pub mod put_account_details;

#[cfg(feature = "op_put_account_pricing_attributes")]
/// Types for the `PutAccountPricingAttributes` operation.
pub mod put_account_pricing_attributes;

#[cfg(feature = "op_put_account_sending_attributes")]
/// Types for the `PutAccountSendingAttributes` operation.
pub mod put_account_sending_attributes;

#[cfg(feature = "op_put_account_suppression_attributes")]
/// Types for the `PutAccountSuppressionAttributes` operation.
pub mod put_account_suppression_attributes;

#[cfg(feature = "op_put_account_vdm_attributes")]
/// Types for the `PutAccountVdmAttributes` operation.
pub mod put_account_vdm_attributes;

#[cfg(feature = "op_put_configuration_set_archiving_options")]
/// Types for the `PutConfigurationSetArchivingOptions` operation.
pub mod put_configuration_set_archiving_options;

#[cfg(feature = "op_put_configuration_set_delivery_options")]
/// Types for the `PutConfigurationSetDeliveryOptions` operation.
pub mod put_configuration_set_delivery_options;

#[cfg(feature = "op_put_configuration_set_reputation_options")]
/// Types for the `PutConfigurationSetReputationOptions` operation.
pub mod put_configuration_set_reputation_options;

#[cfg(feature = "op_put_configuration_set_sending_options")]
/// Types for the `PutConfigurationSetSendingOptions` operation.
pub mod put_configuration_set_sending_options;

#[cfg(feature = "op_put_configuration_set_suppression_options")]
/// Types for the `PutConfigurationSetSuppressionOptions` operation.
pub mod put_configuration_set_suppression_options;

#[cfg(feature = "op_put_configuration_set_tracking_options")]
/// Types for the `PutConfigurationSetTrackingOptions` operation.
pub mod put_configuration_set_tracking_options;

#[cfg(feature = "op_put_configuration_set_vdm_options")]
/// Types for the `PutConfigurationSetVdmOptions` operation.
pub mod put_configuration_set_vdm_options;

#[cfg(feature = "op_put_dedicated_ip_in_pool")]
/// Types for the `PutDedicatedIpInPool` operation.
pub mod put_dedicated_ip_in_pool;

#[cfg(feature = "op_put_dedicated_ip_pool_scaling_attributes")]
/// Types for the `PutDedicatedIpPoolScalingAttributes` operation.
pub mod put_dedicated_ip_pool_scaling_attributes;

#[cfg(feature = "op_put_dedicated_ip_warmup_attributes")]
/// Types for the `PutDedicatedIpWarmupAttributes` operation.
pub mod put_dedicated_ip_warmup_attributes;

#[cfg(feature = "op_put_deliverability_dashboard_option")]
/// Types for the `PutDeliverabilityDashboardOption` operation.
pub mod put_deliverability_dashboard_option;

#[cfg(feature = "op_put_email_identity_configuration_set_attributes")]
/// Types for the `PutEmailIdentityConfigurationSetAttributes` operation.
pub mod put_email_identity_configuration_set_attributes;

#[cfg(feature = "op_put_email_identity_dkim_attributes")]
/// Types for the `PutEmailIdentityDkimAttributes` operation.
pub mod put_email_identity_dkim_attributes;

#[cfg(feature = "op_put_email_identity_dkim_signing_attributes")]
/// Types for the `PutEmailIdentityDkimSigningAttributes` operation.
pub mod put_email_identity_dkim_signing_attributes;

#[cfg(feature = "op_put_email_identity_feedback_attributes")]
/// Types for the `PutEmailIdentityFeedbackAttributes` operation.
pub mod put_email_identity_feedback_attributes;

#[cfg(feature = "op_put_email_identity_mail_from_attributes")]
/// Types for the `PutEmailIdentityMailFromAttributes` operation.
pub mod put_email_identity_mail_from_attributes;

#[cfg(feature = "op_put_suppressed_destination")]
/// Types for the `PutSuppressedDestination` operation.
pub mod put_suppressed_destination;

#[cfg(feature = "op_put_tenant_suppression_attributes")]
/// Types for the `PutTenantSuppressionAttributes` operation.
pub mod put_tenant_suppression_attributes;

#[cfg(feature = "op_send_bulk_email")]
/// Types for the `SendBulkEmail` operation.
pub mod send_bulk_email;

#[cfg(feature = "op_send_custom_verification_email")]
/// Types for the `SendCustomVerificationEmail` operation.
pub mod send_custom_verification_email;

#[cfg(feature = "op_send_email")]
/// Types for the `SendEmail` operation.
pub mod send_email;

#[cfg(feature = "op_tag_resource")]
/// Types for the `TagResource` operation.
pub mod tag_resource;

#[cfg(feature = "op_test_render_email_template")]
/// Types for the `TestRenderEmailTemplate` operation.
pub mod test_render_email_template;

#[cfg(feature = "op_untag_resource")]
/// Types for the `UntagResource` operation.
pub mod untag_resource;

#[cfg(feature = "op_update_configuration_set")]
/// Types for the `UpdateConfigurationSet` operation.
pub mod update_configuration_set;

#[cfg(feature = "op_update_configuration_set_event_destination")]
/// Types for the `UpdateConfigurationSetEventDestination` operation.
pub mod update_configuration_set_event_destination;

#[cfg(feature = "op_update_contact")]
/// Types for the `UpdateContact` operation.
pub mod update_contact;

#[cfg(feature = "op_update_contact_list")]
/// Types for the `UpdateContactList` operation.
pub mod update_contact_list;

#[cfg(feature = "op_update_custom_verification_email_template")]
/// Types for the `UpdateCustomVerificationEmailTemplate` operation.
pub mod update_custom_verification_email_template;

#[cfg(feature = "op_update_email_identity_policy")]
/// Types for the `UpdateEmailIdentityPolicy` operation.
pub mod update_email_identity_policy;

#[cfg(feature = "op_update_email_template")]
/// Types for the `UpdateEmailTemplate` operation.
pub mod update_email_template;

#[cfg(feature = "op_update_reputation_entity_customer_managed_status")]
/// Types for the `UpdateReputationEntityCustomerManagedStatus` operation.
pub mod update_reputation_entity_customer_managed_status;

#[cfg(feature = "op_update_reputation_entity_policy")]
/// Types for the `UpdateReputationEntityPolicy` operation.
pub mod update_reputation_entity_policy;
