// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(any(feature = "op_create_configuration_set", feature = "op_get_configuration_set"))]
pub use crate::types::_tracking_options::TrackingOptions;

#[cfg(any(feature = "op_create_configuration_set", feature = "op_get_configuration_set"))]
pub use crate::types::_delivery_options::DeliveryOptions;

#[cfg(any(feature = "op_create_configuration_set", feature = "op_get_configuration_set"))]
pub use crate::types::_reputation_options::ReputationOptions;

#[cfg(any(feature = "op_create_configuration_set", feature = "op_get_configuration_set"))]
pub use crate::types::_sending_options::SendingOptions;

#[cfg(any(feature = "op_create_configuration_set", feature = "op_get_configuration_set"))]
pub use crate::types::_suppression_options::SuppressionOptions;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_put_configuration_set_vdm_options"
))]
pub use crate::types::_vdm_options::VdmOptions;

#[cfg(any(feature = "op_create_configuration_set", feature = "op_get_configuration_set"))]
pub use crate::types::_archiving_options::ArchivingOptions;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_update_configuration_set"
))]
pub use crate::types::_message_security_options::MessageSecurityOptions;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_update_configuration_set_event_destination"
))]
pub use crate::types::_event_destination_definition::EventDestinationDefinition;

#[cfg(any(
    feature = "op_create_dedicated_ip_pool",
    feature = "op_get_dedicated_ip_pool",
    feature = "op_put_dedicated_ip_pool_scaling_attributes"
))]
pub use crate::types::_scaling_mode::ScalingMode;

#[cfg(any(feature = "op_create_deliverability_test_report", feature = "op_send_email"))]
pub use crate::types::_email_content::EmailContent;

#[cfg(any(
    feature = "op_create_deliverability_test_report",
    feature = "op_get_deliverability_test_report",
    feature = "op_list_deliverability_test_reports"
))]
pub use crate::types::_deliverability_test_status::DeliverabilityTestStatus;

#[cfg(any(
    feature = "op_create_email_identity",
    feature = "op_put_email_identity_dkim_signing_attributes"
))]
pub use crate::types::_dkim_signing_attributes::DkimSigningAttributes;

#[cfg(any(
    feature = "op_create_email_identity",
    feature = "op_get_email_identity",
    feature = "op_list_email_identities"
))]
pub use crate::types::_identity_type::IdentityType;

#[cfg(any(feature = "op_create_email_identity", feature = "op_get_email_identity"))]
pub use crate::types::_dkim_attributes::DkimAttributes;

#[cfg(any(
    feature = "op_create_deliverability_test_report",
    feature = "op_create_email_template",
    feature = "op_get_email_template",
    feature = "op_send_bulk_email",
    feature = "op_send_email",
    feature = "op_update_email_template"
))]
pub use crate::types::_email_template_content::EmailTemplateContent;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
pub use crate::types::_export_data_source::ExportDataSource;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
pub use crate::types::_export_destination::ExportDestination;

#[cfg(any(
    feature = "op_create_import_job",
    feature = "op_get_import_job",
    feature = "op_list_import_jobs"
))]
pub use crate::types::_import_destination::ImportDestination;

#[cfg(any(feature = "op_create_import_job", feature = "op_get_import_job"))]
pub use crate::types::_import_data_source::ImportDataSource;

#[cfg(feature = "op_create_multi_region_endpoint")]
pub use crate::types::_details::Details;

#[cfg(any(
    feature = "op_create_multi_region_endpoint",
    feature = "op_delete_multi_region_endpoint",
    feature = "op_get_multi_region_endpoint",
    feature = "op_list_multi_region_endpoints"
))]
pub use crate::types::_status::Status;

#[cfg(any(feature = "op_create_tenant", feature = "op_get_tenant"))]
pub use crate::types::_tenant_suppression_attributes::TenantSuppressionAttributes;

#[cfg(any(
    feature = "op_create_tenant",
    feature = "op_get_reputation_entity",
    feature = "op_get_tenant",
    feature = "op_list_reputation_entities",
    feature = "op_update_reputation_entity_customer_managed_status"
))]
pub use crate::types::_sending_status::SendingStatus;

#[cfg(feature = "op_get_account")]
pub use crate::types::_send_quota::SendQuota;

#[cfg(feature = "op_get_account")]
pub use crate::types::_suppression_attributes::SuppressionAttributes;

#[cfg(feature = "op_get_account")]
pub use crate::types::_account_details::AccountDetails;

#[cfg(any(feature = "op_get_account", feature = "op_put_account_vdm_attributes"))]
pub use crate::types::_vdm_attributes::VdmAttributes;

#[cfg(feature = "op_get_account")]
pub use crate::types::_pricing_attributes::PricingAttributes;

#[cfg(any(feature = "op_get_dedicated_ip", feature = "op_get_dedicated_ips"))]
pub use crate::types::_dedicated_ip::DedicatedIp;

#[cfg(feature = "op_get_dedicated_ip_pool")]
pub use crate::types::_dedicated_ip_pool::DedicatedIpPool;

#[cfg(feature = "op_get_deliverability_dashboard_options")]
pub use crate::types::_deliverability_dashboard_account_status::DeliverabilityDashboardAccountStatus;

#[cfg(any(
    feature = "op_get_deliverability_test_report",
    feature = "op_list_deliverability_test_reports"
))]
pub use crate::types::_deliverability_test_report::DeliverabilityTestReport;

#[cfg(feature = "op_get_deliverability_test_report")]
pub use crate::types::_placement_statistics::PlacementStatistics;

#[cfg(any(
    feature = "op_get_domain_deliverability_campaign",
    feature = "op_list_domain_deliverability_campaigns"
))]
pub use crate::types::_domain_deliverability_campaign::DomainDeliverabilityCampaign;

#[cfg(feature = "op_get_domain_statistics_report")]
pub use crate::types::_overall_volume::OverallVolume;

#[cfg(feature = "op_get_email_address_insights")]
pub use crate::types::_mailbox_validation::MailboxValidation;

#[cfg(feature = "op_get_email_identity")]
pub use crate::types::_mail_from_attributes::MailFromAttributes;

#[cfg(any(feature = "op_get_email_identity", feature = "op_list_email_identities"))]
pub use crate::types::_verification_status::VerificationStatus;

#[cfg(feature = "op_get_email_identity")]
pub use crate::types::_verification_info::VerificationInfo;

#[cfg(any(feature = "op_get_export_job", feature = "op_list_export_jobs"))]
pub use crate::types::_export_source_type::ExportSourceType;

#[cfg(any(
    feature = "op_get_export_job",
    feature = "op_get_import_job",
    feature = "op_list_export_jobs",
    feature = "op_list_import_jobs"
))]
pub use crate::types::_job_status::JobStatus;

#[cfg(any(feature = "op_get_export_job", feature = "op_get_import_job"))]
pub use crate::types::_failure_info::FailureInfo;

#[cfg(feature = "op_get_export_job")]
pub use crate::types::_export_statistics::ExportStatistics;

#[cfg(any(
    feature = "op_get_reputation_entity",
    feature = "op_list_reputation_entities",
    feature = "op_update_reputation_entity_customer_managed_status",
    feature = "op_update_reputation_entity_policy"
))]
pub use crate::types::_reputation_entity_type::ReputationEntityType;

#[cfg(any(feature = "op_get_reputation_entity", feature = "op_list_reputation_entities"))]
pub use crate::types::_reputation_entity::ReputationEntity;

#[cfg(feature = "op_get_suppressed_destination")]
pub use crate::types::_suppressed_destination::SuppressedDestination;

#[cfg(feature = "op_get_tenant")]
pub use crate::types::_tenant::Tenant;

#[cfg(feature = "op_list_contacts")]
pub use crate::types::_list_contacts_filter::ListContactsFilter;

#[cfg(feature = "op_list_import_jobs")]
pub use crate::types::_import_destination_type::ImportDestinationType;

#[cfg(any(feature = "op_get_account", feature = "op_put_account_details"))]
pub use crate::types::_mail_type::MailType;

#[cfg(any(feature = "op_get_account", feature = "op_put_account_details"))]
pub use crate::types::_contact_language::ContactLanguage;

#[cfg(any(feature = "op_get_account", feature = "op_put_account_pricing_attributes"))]
pub use crate::types::_pricing_plan::PricingPlan;

#[cfg(any(feature = "op_get_account", feature = "op_put_account_suppression_attributes"))]
pub use crate::types::_suppression_validation_attributes::SuppressionValidationAttributes;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_put_configuration_set_delivery_options"
))]
pub use crate::types::_tls_policy::TlsPolicy;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_create_tenant",
    feature = "op_get_configuration_set",
    feature = "op_get_tenant",
    feature = "op_put_configuration_set_suppression_options",
    feature = "op_put_tenant_suppression_attributes"
))]
pub use crate::types::_suppression_list_scope::SuppressionListScope;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_put_configuration_set_suppression_options"
))]
pub use crate::types::_suppression_validation_options::SuppressionValidationOptions;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_put_configuration_set_tracking_options"
))]
pub use crate::types::_https_policy::HttpsPolicy;

#[cfg(any(
    feature = "op_create_email_identity",
    feature = "op_get_email_identity",
    feature = "op_put_email_identity_dkim_signing_attributes"
))]
pub use crate::types::_dkim_signing_attributes_origin::DkimSigningAttributesOrigin;

#[cfg(any(
    feature = "op_create_email_identity",
    feature = "op_get_email_identity",
    feature = "op_put_email_identity_dkim_signing_attributes"
))]
pub use crate::types::_dkim_status::DkimStatus;

#[cfg(any(
    feature = "op_get_email_identity",
    feature = "op_put_email_identity_mail_from_attributes"
))]
pub use crate::types::_behavior_on_mx_failure::BehaviorOnMxFailure;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_create_tenant",
    feature = "op_get_account",
    feature = "op_get_configuration_set",
    feature = "op_get_suppressed_destination",
    feature = "op_get_tenant",
    feature = "op_list_suppressed_destinations",
    feature = "op_put_account_suppression_attributes",
    feature = "op_put_configuration_set_suppression_options",
    feature = "op_put_suppressed_destination",
    feature = "op_put_tenant_suppression_attributes"
))]
pub use crate::types::_suppression_list_reason::SuppressionListReason;

#[cfg(feature = "op_send_bulk_email")]
pub use crate::types::_bulk_email_content::BulkEmailContent;

#[cfg(any(feature = "op_send_bulk_email", feature = "op_send_email"))]
pub use crate::types::_configuration_overrides::ConfigurationOverrides;

#[cfg(any(feature = "op_send_bulk_email", feature = "op_send_email"))]
pub use crate::types::_destination::Destination;

#[cfg(feature = "op_send_email")]
pub use crate::types::_list_management_options::ListManagementOptions;

#[cfg(feature = "op_batch_get_metric_data")]
pub use crate::types::_batch_get_metric_data_query::BatchGetMetricDataQuery;

#[cfg(feature = "op_batch_get_metric_data")]
pub use crate::types::_metric_data_result::MetricDataResult;

#[cfg(feature = "op_batch_get_metric_data")]
pub use crate::types::_metric_data_error::MetricDataError;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_create_contact_list",
    feature = "op_create_custom_verification_email_template",
    feature = "op_create_dedicated_ip_pool",
    feature = "op_create_deliverability_test_report",
    feature = "op_create_email_identity",
    feature = "op_create_email_template",
    feature = "op_create_multi_region_endpoint",
    feature = "op_create_tenant",
    feature = "op_get_configuration_set",
    feature = "op_get_contact_list",
    feature = "op_get_custom_verification_email_template",
    feature = "op_get_deliverability_test_report",
    feature = "op_get_email_identity",
    feature = "op_get_email_template",
    feature = "op_get_tenant",
    feature = "op_list_tags_for_resource",
    feature = "op_tag_resource"
))]
pub use crate::types::_tag::Tag;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_put_configuration_set_vdm_options"
))]
pub use crate::types::_dashboard_options::DashboardOptions;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_put_configuration_set_vdm_options"
))]
pub use crate::types::_guardian_options::GuardianOptions;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_update_configuration_set"
))]
pub use crate::types::_signing_scheme::SigningScheme;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_update_configuration_set_event_destination"
))]
pub use crate::types::_kinesis_firehose_destination::KinesisFirehoseDestination;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_update_configuration_set_event_destination"
))]
pub use crate::types::_cloud_watch_destination::CloudWatchDestination;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_update_configuration_set_event_destination"
))]
pub use crate::types::_sns_destination::SnsDestination;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_update_configuration_set_event_destination"
))]
pub use crate::types::_event_bridge_destination::EventBridgeDestination;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_update_configuration_set_event_destination"
))]
pub use crate::types::_pinpoint_destination::PinpointDestination;

#[cfg(any(
    feature = "op_create_contact",
    feature = "op_get_contact",
    feature = "op_list_contacts",
    feature = "op_update_contact"
))]
pub use crate::types::_topic_preference::TopicPreference;

#[cfg(any(
    feature = "op_create_contact_list",
    feature = "op_get_contact_list",
    feature = "op_update_contact_list"
))]
pub use crate::types::_topic::Topic;

#[cfg(any(feature = "op_create_deliverability_test_report", feature = "op_send_email"))]
pub use crate::types::_message::Message;

#[cfg(any(feature = "op_create_deliverability_test_report", feature = "op_send_email"))]
pub use crate::types::_raw_message::RawMessage;

#[cfg(any(
    feature = "op_create_deliverability_test_report",
    feature = "op_send_bulk_email",
    feature = "op_send_email"
))]
pub use crate::types::_template::Template;

#[cfg(any(
    feature = "op_create_email_identity",
    feature = "op_get_email_identity",
    feature = "op_put_email_identity_dkim_signing_attributes"
))]
pub use crate::types::_dkim_signing_key_length::DkimSigningKeyLength;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
pub use crate::types::_metrics_data_source::MetricsDataSource;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
pub use crate::types::_message_insights_data_source::MessageInsightsDataSource;

#[cfg(any(
    feature = "op_create_export_job",
    feature = "op_create_import_job",
    feature = "op_get_export_job",
    feature = "op_get_import_job"
))]
pub use crate::types::_data_format::DataFormat;

#[cfg(any(
    feature = "op_create_import_job",
    feature = "op_get_import_job",
    feature = "op_list_import_jobs"
))]
pub use crate::types::_suppression_list_destination::SuppressionListDestination;

#[cfg(any(
    feature = "op_create_import_job",
    feature = "op_get_import_job",
    feature = "op_list_import_jobs"
))]
pub use crate::types::_contact_list_destination::ContactListDestination;

#[cfg(feature = "op_get_account")]
pub use crate::types::_review_details::ReviewDetails;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_account",
    feature = "op_get_configuration_set",
    feature = "op_put_account_suppression_attributes",
    feature = "op_put_account_vdm_attributes",
    feature = "op_put_configuration_set_suppression_options",
    feature = "op_put_configuration_set_vdm_options",
    feature = "op_send_bulk_email",
    feature = "op_send_email"
))]
pub use crate::types::_feature_status::FeatureStatus;

#[cfg(any(feature = "op_get_account", feature = "op_put_account_vdm_attributes"))]
pub use crate::types::_dashboard_attributes::DashboardAttributes;

#[cfg(any(feature = "op_get_account", feature = "op_put_account_vdm_attributes"))]
pub use crate::types::_guardian_attributes::GuardianAttributes;

#[cfg(feature = "op_get_configuration_set_event_destinations")]
pub use crate::types::_event_destination::EventDestination;

#[cfg(any(feature = "op_get_dedicated_ip", feature = "op_get_dedicated_ips"))]
pub use crate::types::_warmup_status::WarmupStatus;

#[cfg(any(
    feature = "op_get_deliverability_dashboard_options",
    feature = "op_put_deliverability_dashboard_option"
))]
pub use crate::types::_domain_deliverability_tracking_option::DomainDeliverabilityTrackingOption;

#[cfg(feature = "op_get_deliverability_test_report")]
pub use crate::types::_isp_placement::IspPlacement;

#[cfg(feature = "op_get_domain_statistics_report")]
pub use crate::types::_volume_statistics::VolumeStatistics;

#[cfg(feature = "op_get_domain_statistics_report")]
pub use crate::types::_daily_volume::DailyVolume;

#[cfg(feature = "op_get_email_address_insights")]
pub use crate::types::_email_address_insights_verdict::EmailAddressInsightsVerdict;

#[cfg(feature = "op_get_email_address_insights")]
pub use crate::types::_email_address_insights_mailbox_evaluations::EmailAddressInsightsMailboxEvaluations;

#[cfg(feature = "op_get_email_identity")]
pub use crate::types::_mail_from_domain_status::MailFromDomainStatus;

#[cfg(feature = "op_get_email_identity")]
pub use crate::types::_verification_error::VerificationError;

#[cfg(feature = "op_get_email_identity")]
pub use crate::types::_soa_record::SoaRecord;

#[cfg(any(
    feature = "op_get_message_insights",
    feature = "op_send_bulk_email",
    feature = "op_send_email"
))]
pub use crate::types::_message_tag::MessageTag;

#[cfg(feature = "op_get_message_insights")]
pub use crate::types::_email_insights::EmailInsights;

#[cfg(feature = "op_get_multi_region_endpoint")]
pub use crate::types::_route::Route;

#[cfg(any(feature = "op_get_reputation_entity", feature = "op_list_reputation_entities"))]
pub use crate::types::_status_record::StatusRecord;

#[cfg(any(
    feature = "op_get_reputation_entity",
    feature = "op_list_recommendations",
    feature = "op_list_reputation_entities"
))]
pub use crate::types::_recommendation_impact::RecommendationImpact;

#[cfg(feature = "op_get_suppressed_destination")]
pub use crate::types::_suppressed_destination_attributes::SuppressedDestinationAttributes;

#[cfg(feature = "op_list_contact_lists")]
pub use crate::types::_contact_list::ContactList;

#[cfg(any(
    feature = "op_create_contact",
    feature = "op_create_contact_list",
    feature = "op_get_contact",
    feature = "op_get_contact_list",
    feature = "op_list_contacts",
    feature = "op_update_contact",
    feature = "op_update_contact_list"
))]
pub use crate::types::_subscription_status::SubscriptionStatus;

#[cfg(feature = "op_list_contacts")]
pub use crate::types::_topic_filter::TopicFilter;

#[cfg(feature = "op_list_contacts")]
pub use crate::types::_contact::Contact;

#[cfg(feature = "op_list_custom_verification_email_templates")]
pub use crate::types::_custom_verification_email_template_metadata::CustomVerificationEmailTemplateMetadata;

#[cfg(feature = "op_list_email_identities")]
pub use crate::types::_identity_info::IdentityInfo;

#[cfg(feature = "op_list_email_identity_certificates")]
pub use crate::types::_identity_certificate::IdentityCertificate;

#[cfg(feature = "op_list_email_templates")]
pub use crate::types::_email_template_metadata::EmailTemplateMetadata;

#[cfg(feature = "op_list_export_jobs")]
pub use crate::types::_export_job_summary::ExportJobSummary;

#[cfg(feature = "op_list_import_jobs")]
pub use crate::types::_import_job_summary::ImportJobSummary;

#[cfg(feature = "op_list_multi_region_endpoints")]
pub use crate::types::_multi_region_endpoint::MultiRegionEndpoint;

#[cfg(feature = "op_list_recommendations")]
pub use crate::types::_list_recommendations_filter_key::ListRecommendationsFilterKey;

#[cfg(feature = "op_list_recommendations")]
pub use crate::types::_recommendation::Recommendation;

#[cfg(feature = "op_list_reputation_entities")]
pub use crate::types::_reputation_entity_filter_key::ReputationEntityFilterKey;

#[cfg(feature = "op_list_resource_tenants")]
pub use crate::types::_resource_tenant_metadata::ResourceTenantMetadata;

#[cfg(feature = "op_list_suppressed_destinations")]
pub use crate::types::_suppressed_destination_summary::SuppressedDestinationSummary;

#[cfg(feature = "op_list_tenant_resources")]
pub use crate::types::_list_tenant_resources_filter_key::ListTenantResourcesFilterKey;

#[cfg(feature = "op_list_tenant_resources")]
pub use crate::types::_tenant_resource::TenantResource;

#[cfg(feature = "op_list_tenants")]
pub use crate::types::_tenant_info::TenantInfo;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_account",
    feature = "op_get_configuration_set",
    feature = "op_put_account_suppression_attributes",
    feature = "op_put_configuration_set_suppression_options"
))]
pub use crate::types::_suppression_condition_threshold::SuppressionConditionThreshold;

#[cfg(feature = "op_send_bulk_email")]
pub use crate::types::_bulk_email_entry::BulkEmailEntry;

#[cfg(any(feature = "op_send_bulk_email", feature = "op_send_email"))]
pub use crate::types::_tracking_configuration_overrides::TrackingConfigurationOverrides;

#[cfg(feature = "op_send_bulk_email")]
pub use crate::types::_bulk_email_entry_result::BulkEmailEntryResult;

#[cfg(any(
    feature = "op_batch_get_metric_data",
    feature = "op_create_export_job",
    feature = "op_get_export_job"
))]
pub use crate::types::_metric_namespace::MetricNamespace;

#[cfg(any(
    feature = "op_batch_get_metric_data",
    feature = "op_create_export_job",
    feature = "op_get_export_job"
))]
pub use crate::types::_metric::Metric;

#[cfg(feature = "op_batch_get_metric_data")]
pub use crate::types::_query_error_code::QueryErrorCode;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_update_configuration_set"
))]
pub use crate::types::_default_signing_scheme::DefaultSigningScheme;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_update_configuration_set"
))]
pub use crate::types::_smime_signing_scheme::SmimeSigningScheme;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_get_message_insights",
    feature = "op_update_configuration_set_event_destination"
))]
pub use crate::types::_event_type::EventType;

#[cfg(any(feature = "op_create_deliverability_test_report", feature = "op_send_email"))]
pub use crate::types::_content::Content;

#[cfg(any(feature = "op_create_deliverability_test_report", feature = "op_send_email"))]
pub use crate::types::_body::Body;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
pub use crate::types::_message_insights_filters::MessageInsightsFilters;

#[cfg(any(
    feature = "op_create_import_job",
    feature = "op_get_import_job",
    feature = "op_list_import_jobs"
))]
pub use crate::types::_suppression_list_import_action::SuppressionListImportAction;

#[cfg(any(
    feature = "op_create_import_job",
    feature = "op_get_import_job",
    feature = "op_list_import_jobs"
))]
pub use crate::types::_contact_list_import_action::ContactListImportAction;

#[cfg(feature = "op_create_multi_region_endpoint")]
pub use crate::types::_route_details::RouteDetails;

#[cfg(feature = "op_get_account")]
pub use crate::types::_review_status::ReviewStatus;

#[cfg(feature = "op_get_blacklist_reports")]
pub use crate::types::_blacklist_entry::BlacklistEntry;

#[cfg(any(
    feature = "op_get_deliverability_dashboard_options",
    feature = "op_put_deliverability_dashboard_option"
))]
pub use crate::types::_inbox_placement_tracking_option::InboxPlacementTrackingOption;

#[cfg(feature = "op_get_domain_statistics_report")]
pub use crate::types::_domain_isp_placement::DomainIspPlacement;

#[cfg(feature = "op_get_email_address_insights")]
pub use crate::types::_email_address_insights_confidence_verdict::EmailAddressInsightsConfidenceVerdict;

#[cfg(feature = "op_list_email_identity_certificates")]
pub use crate::types::_identity_certificate_status::IdentityCertificateStatus;

#[cfg(feature = "op_list_recommendations")]
pub use crate::types::_recommendation_type::RecommendationType;

#[cfg(feature = "op_list_recommendations")]
pub use crate::types::_recommendation_status::RecommendationStatus;

#[cfg(feature = "op_list_tenant_resources")]
pub use crate::types::_resource_type::ResourceType;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_account",
    feature = "op_get_configuration_set",
    feature = "op_put_account_suppression_attributes",
    feature = "op_put_configuration_set_suppression_options"
))]
pub use crate::types::_suppression_confidence_threshold::SuppressionConfidenceThreshold;

#[cfg(feature = "op_send_bulk_email")]
pub use crate::types::_replacement_email_content::ReplacementEmailContent;

#[cfg(feature = "op_send_bulk_email")]
pub use crate::types::_bulk_email_status::BulkEmailStatus;

#[cfg(any(
    feature = "op_batch_get_metric_data",
    feature = "op_create_export_job",
    feature = "op_get_export_job"
))]
pub use crate::types::_metric_dimension_name::MetricDimensionName;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_update_configuration_set"
))]
pub use crate::types::_signature_format::SignatureFormat;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_update_configuration_set_event_destination"
))]
pub use crate::types::_cloud_watch_dimension_configuration::CloudWatchDimensionConfiguration;

#[cfg(any(
    feature = "op_create_deliverability_test_report",
    feature = "op_send_bulk_email",
    feature = "op_send_email"
))]
pub use crate::types::_message_header::MessageHeader;

#[cfg(any(
    feature = "op_create_deliverability_test_report",
    feature = "op_send_bulk_email",
    feature = "op_send_email"
))]
pub use crate::types::_attachment::Attachment;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
pub use crate::types::_export_metric::ExportMetric;

#[cfg(feature = "op_get_message_insights")]
pub use crate::types::_insights_event::InsightsEvent;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_account",
    feature = "op_get_configuration_set",
    feature = "op_put_account_suppression_attributes",
    feature = "op_put_configuration_set_suppression_options"
))]
pub use crate::types::_suppression_confidence_verdict_threshold::SuppressionConfidenceVerdictThreshold;

#[cfg(feature = "op_send_bulk_email")]
pub use crate::types::_replacement_template::ReplacementTemplate;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_update_configuration_set_event_destination"
))]
pub use crate::types::_dimension_value_source::DimensionValueSource;

#[cfg(any(
    feature = "op_create_deliverability_test_report",
    feature = "op_send_bulk_email",
    feature = "op_send_email"
))]
pub use crate::types::_attachment_content_disposition::AttachmentContentDisposition;

#[cfg(any(
    feature = "op_create_deliverability_test_report",
    feature = "op_send_bulk_email",
    feature = "op_send_email"
))]
pub use crate::types::_attachment_content_transfer_encoding::AttachmentContentTransferEncoding;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
pub use crate::types::_metric_aggregation::MetricAggregation;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
pub use crate::types::_delivery_event_type::DeliveryEventType;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
pub use crate::types::_engagement_event_type::EngagementEventType;

#[cfg(feature = "op_get_message_insights")]
pub use crate::types::_event_details::EventDetails;

#[cfg(feature = "op_get_message_insights")]
pub use crate::types::_bounce::Bounce;

#[cfg(feature = "op_get_message_insights")]
pub use crate::types::_complaint::Complaint;

#[cfg(feature = "op_get_message_insights")]
pub use crate::types::_bounce_type::BounceType;

#[cfg(feature = "op_get_account")]
mod _account_details;

#[cfg(any(feature = "op_create_configuration_set", feature = "op_get_configuration_set"))]
mod _archiving_options;

#[cfg(any(
    feature = "op_create_deliverability_test_report",
    feature = "op_send_bulk_email",
    feature = "op_send_email"
))]
mod _attachment;

#[cfg(any(
    feature = "op_create_deliverability_test_report",
    feature = "op_send_bulk_email",
    feature = "op_send_email"
))]
mod _attachment_content_disposition;

#[cfg(any(
    feature = "op_create_deliverability_test_report",
    feature = "op_send_bulk_email",
    feature = "op_send_email"
))]
mod _attachment_content_transfer_encoding;

#[cfg(feature = "op_batch_get_metric_data")]
mod _batch_get_metric_data_query;

#[cfg(any(
    feature = "op_get_email_identity",
    feature = "op_put_email_identity_mail_from_attributes"
))]
mod _behavior_on_mx_failure;

#[cfg(feature = "op_get_blacklist_reports")]
mod _blacklist_entry;

#[cfg(any(feature = "op_create_deliverability_test_report", feature = "op_send_email"))]
mod _body;

#[cfg(feature = "op_get_message_insights")]
mod _bounce;

#[cfg(feature = "op_get_message_insights")]
mod _bounce_type;

#[cfg(feature = "op_send_bulk_email")]
mod _bulk_email_content;

#[cfg(feature = "op_send_bulk_email")]
mod _bulk_email_entry;

#[cfg(feature = "op_send_bulk_email")]
mod _bulk_email_entry_result;

#[cfg(feature = "op_send_bulk_email")]
mod _bulk_email_status;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_update_configuration_set_event_destination"
))]
mod _cloud_watch_destination;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_update_configuration_set_event_destination"
))]
mod _cloud_watch_dimension_configuration;

#[cfg(feature = "op_get_message_insights")]
mod _complaint;

#[cfg(any(feature = "op_send_bulk_email", feature = "op_send_email"))]
mod _configuration_overrides;

#[cfg(feature = "op_list_contacts")]
mod _contact;

#[cfg(any(feature = "op_get_account", feature = "op_put_account_details"))]
mod _contact_language;

#[cfg(feature = "op_list_contact_lists")]
mod _contact_list;

#[cfg(any(
    feature = "op_create_import_job",
    feature = "op_get_import_job",
    feature = "op_list_import_jobs"
))]
mod _contact_list_destination;

#[cfg(any(
    feature = "op_create_import_job",
    feature = "op_get_import_job",
    feature = "op_list_import_jobs"
))]
mod _contact_list_import_action;

#[cfg(any(feature = "op_create_deliverability_test_report", feature = "op_send_email"))]
mod _content;

#[cfg(feature = "op_list_custom_verification_email_templates")]
mod _custom_verification_email_template_metadata;

#[cfg(feature = "op_get_domain_statistics_report")]
mod _daily_volume;

#[cfg(any(feature = "op_get_account", feature = "op_put_account_vdm_attributes"))]
mod _dashboard_attributes;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_put_configuration_set_vdm_options"
))]
mod _dashboard_options;

#[cfg(any(
    feature = "op_create_export_job",
    feature = "op_create_import_job",
    feature = "op_get_export_job",
    feature = "op_get_import_job"
))]
mod _data_format;

#[cfg(any(feature = "op_get_dedicated_ip", feature = "op_get_dedicated_ips"))]
mod _dedicated_ip;

#[cfg(feature = "op_get_dedicated_ip_pool")]
mod _dedicated_ip_pool;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_update_configuration_set"
))]
mod _default_signing_scheme;

#[cfg(feature = "op_get_deliverability_dashboard_options")]
mod _deliverability_dashboard_account_status;

#[cfg(any(
    feature = "op_get_deliverability_test_report",
    feature = "op_list_deliverability_test_reports"
))]
mod _deliverability_test_report;

#[cfg(any(
    feature = "op_create_deliverability_test_report",
    feature = "op_get_deliverability_test_report",
    feature = "op_list_deliverability_test_reports"
))]
mod _deliverability_test_status;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
mod _delivery_event_type;

#[cfg(any(feature = "op_create_configuration_set", feature = "op_get_configuration_set"))]
mod _delivery_options;

#[cfg(any(feature = "op_send_bulk_email", feature = "op_send_email"))]
mod _destination;

#[cfg(feature = "op_create_multi_region_endpoint")]
mod _details;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_update_configuration_set_event_destination"
))]
mod _dimension_value_source;

#[cfg(any(feature = "op_create_email_identity", feature = "op_get_email_identity"))]
mod _dkim_attributes;

#[cfg(any(
    feature = "op_create_email_identity",
    feature = "op_put_email_identity_dkim_signing_attributes"
))]
mod _dkim_signing_attributes;

#[cfg(any(
    feature = "op_create_email_identity",
    feature = "op_get_email_identity",
    feature = "op_put_email_identity_dkim_signing_attributes"
))]
mod _dkim_signing_attributes_origin;

#[cfg(any(
    feature = "op_create_email_identity",
    feature = "op_get_email_identity",
    feature = "op_put_email_identity_dkim_signing_attributes"
))]
mod _dkim_signing_key_length;

#[cfg(any(
    feature = "op_create_email_identity",
    feature = "op_get_email_identity",
    feature = "op_put_email_identity_dkim_signing_attributes"
))]
mod _dkim_status;

#[cfg(any(
    feature = "op_get_domain_deliverability_campaign",
    feature = "op_list_domain_deliverability_campaigns"
))]
mod _domain_deliverability_campaign;

#[cfg(any(
    feature = "op_get_deliverability_dashboard_options",
    feature = "op_put_deliverability_dashboard_option"
))]
mod _domain_deliverability_tracking_option;

#[cfg(feature = "op_get_domain_statistics_report")]
mod _domain_isp_placement;

#[cfg(feature = "op_get_email_address_insights")]
mod _email_address_insights_confidence_verdict;

#[cfg(feature = "op_get_email_address_insights")]
mod _email_address_insights_mailbox_evaluations;

#[cfg(feature = "op_get_email_address_insights")]
mod _email_address_insights_verdict;

#[cfg(any(feature = "op_create_deliverability_test_report", feature = "op_send_email"))]
mod _email_content;

#[cfg(feature = "op_get_message_insights")]
mod _email_insights;

#[cfg(any(
    feature = "op_create_deliverability_test_report",
    feature = "op_create_email_template",
    feature = "op_get_email_template",
    feature = "op_send_bulk_email",
    feature = "op_send_email",
    feature = "op_update_email_template"
))]
mod _email_template_content;

#[cfg(feature = "op_list_email_templates")]
mod _email_template_metadata;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
mod _engagement_event_type;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_update_configuration_set_event_destination"
))]
mod _event_bridge_destination;

#[cfg(feature = "op_get_configuration_set_event_destinations")]
mod _event_destination;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_update_configuration_set_event_destination"
))]
mod _event_destination_definition;

#[cfg(feature = "op_get_message_insights")]
mod _event_details;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_get_message_insights",
    feature = "op_update_configuration_set_event_destination"
))]
mod _event_type;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
mod _export_data_source;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
mod _export_destination;

#[cfg(feature = "op_list_export_jobs")]
mod _export_job_summary;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
mod _export_metric;

#[cfg(any(feature = "op_get_export_job", feature = "op_list_export_jobs"))]
mod _export_source_type;

#[cfg(feature = "op_get_export_job")]
mod _export_statistics;

#[cfg(any(feature = "op_get_export_job", feature = "op_get_import_job"))]
mod _failure_info;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_account",
    feature = "op_get_configuration_set",
    feature = "op_put_account_suppression_attributes",
    feature = "op_put_account_vdm_attributes",
    feature = "op_put_configuration_set_suppression_options",
    feature = "op_put_configuration_set_vdm_options",
    feature = "op_send_bulk_email",
    feature = "op_send_email"
))]
mod _feature_status;

#[cfg(any(feature = "op_get_account", feature = "op_put_account_vdm_attributes"))]
mod _guardian_attributes;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_put_configuration_set_vdm_options"
))]
mod _guardian_options;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_put_configuration_set_tracking_options"
))]
mod _https_policy;

#[cfg(feature = "op_list_email_identity_certificates")]
mod _identity_certificate;

#[cfg(feature = "op_list_email_identity_certificates")]
mod _identity_certificate_status;

#[cfg(feature = "op_list_email_identities")]
mod _identity_info;

#[cfg(any(
    feature = "op_create_email_identity",
    feature = "op_get_email_identity",
    feature = "op_list_email_identities"
))]
mod _identity_type;

#[cfg(any(feature = "op_create_import_job", feature = "op_get_import_job"))]
mod _import_data_source;

#[cfg(any(
    feature = "op_create_import_job",
    feature = "op_get_import_job",
    feature = "op_list_import_jobs"
))]
mod _import_destination;

#[cfg(feature = "op_list_import_jobs")]
mod _import_destination_type;

#[cfg(feature = "op_list_import_jobs")]
mod _import_job_summary;

#[cfg(any(
    feature = "op_get_deliverability_dashboard_options",
    feature = "op_put_deliverability_dashboard_option"
))]
mod _inbox_placement_tracking_option;

#[cfg(feature = "op_get_message_insights")]
mod _insights_event;

#[cfg(feature = "op_get_deliverability_test_report")]
mod _isp_placement;

#[cfg(any(
    feature = "op_get_export_job",
    feature = "op_get_import_job",
    feature = "op_list_export_jobs",
    feature = "op_list_import_jobs"
))]
mod _job_status;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_update_configuration_set_event_destination"
))]
mod _kinesis_firehose_destination;

#[cfg(feature = "op_list_contacts")]
mod _list_contacts_filter;

#[cfg(feature = "op_send_email")]
mod _list_management_options;

#[cfg(feature = "op_list_recommendations")]
mod _list_recommendations_filter_key;

#[cfg(feature = "op_list_tenant_resources")]
mod _list_tenant_resources_filter_key;

#[cfg(feature = "op_get_email_identity")]
mod _mail_from_attributes;

#[cfg(feature = "op_get_email_identity")]
mod _mail_from_domain_status;

#[cfg(any(feature = "op_get_account", feature = "op_put_account_details"))]
mod _mail_type;

#[cfg(feature = "op_get_email_address_insights")]
mod _mailbox_validation;

#[cfg(any(feature = "op_create_deliverability_test_report", feature = "op_send_email"))]
mod _message;

#[cfg(any(
    feature = "op_create_deliverability_test_report",
    feature = "op_send_bulk_email",
    feature = "op_send_email"
))]
mod _message_header;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
mod _message_insights_data_source;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
mod _message_insights_filters;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_update_configuration_set"
))]
mod _message_security_options;

#[cfg(any(
    feature = "op_get_message_insights",
    feature = "op_send_bulk_email",
    feature = "op_send_email"
))]
mod _message_tag;

#[cfg(any(
    feature = "op_batch_get_metric_data",
    feature = "op_create_export_job",
    feature = "op_get_export_job"
))]
mod _metric;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
mod _metric_aggregation;

#[cfg(feature = "op_batch_get_metric_data")]
mod _metric_data_error;

#[cfg(feature = "op_batch_get_metric_data")]
mod _metric_data_result;

#[cfg(any(
    feature = "op_batch_get_metric_data",
    feature = "op_create_export_job",
    feature = "op_get_export_job"
))]
mod _metric_dimension_name;

#[cfg(any(
    feature = "op_batch_get_metric_data",
    feature = "op_create_export_job",
    feature = "op_get_export_job"
))]
mod _metric_namespace;

#[cfg(any(feature = "op_create_export_job", feature = "op_get_export_job"))]
mod _metrics_data_source;

#[cfg(feature = "op_list_multi_region_endpoints")]
mod _multi_region_endpoint;

#[cfg(feature = "op_get_domain_statistics_report")]
mod _overall_volume;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_update_configuration_set_event_destination"
))]
mod _pinpoint_destination;

#[cfg(feature = "op_get_deliverability_test_report")]
mod _placement_statistics;

#[cfg(feature = "op_get_account")]
mod _pricing_attributes;

#[cfg(any(feature = "op_get_account", feature = "op_put_account_pricing_attributes"))]
mod _pricing_plan;

#[cfg(feature = "op_batch_get_metric_data")]
mod _query_error_code;

#[cfg(any(feature = "op_create_deliverability_test_report", feature = "op_send_email"))]
mod _raw_message;

#[cfg(feature = "op_list_recommendations")]
mod _recommendation;

#[cfg(any(
    feature = "op_get_reputation_entity",
    feature = "op_list_recommendations",
    feature = "op_list_reputation_entities"
))]
mod _recommendation_impact;

#[cfg(feature = "op_list_recommendations")]
mod _recommendation_status;

#[cfg(feature = "op_list_recommendations")]
mod _recommendation_type;

#[cfg(feature = "op_send_bulk_email")]
mod _replacement_email_content;

#[cfg(feature = "op_send_bulk_email")]
mod _replacement_template;

#[cfg(any(feature = "op_get_reputation_entity", feature = "op_list_reputation_entities"))]
mod _reputation_entity;

#[cfg(feature = "op_list_reputation_entities")]
mod _reputation_entity_filter_key;

#[cfg(any(
    feature = "op_get_reputation_entity",
    feature = "op_list_reputation_entities",
    feature = "op_update_reputation_entity_customer_managed_status",
    feature = "op_update_reputation_entity_policy"
))]
mod _reputation_entity_type;

#[cfg(any(feature = "op_create_configuration_set", feature = "op_get_configuration_set"))]
mod _reputation_options;

#[cfg(feature = "op_list_resource_tenants")]
mod _resource_tenant_metadata;

#[cfg(feature = "op_list_tenant_resources")]
mod _resource_type;

#[cfg(feature = "op_get_account")]
mod _review_details;

#[cfg(feature = "op_get_account")]
mod _review_status;

#[cfg(feature = "op_get_multi_region_endpoint")]
mod _route;

#[cfg(feature = "op_create_multi_region_endpoint")]
mod _route_details;

#[cfg(any(
    feature = "op_create_dedicated_ip_pool",
    feature = "op_get_dedicated_ip_pool",
    feature = "op_put_dedicated_ip_pool_scaling_attributes"
))]
mod _scaling_mode;

#[cfg(feature = "op_get_account")]
mod _send_quota;

#[cfg(any(feature = "op_create_configuration_set", feature = "op_get_configuration_set"))]
mod _sending_options;

#[cfg(any(
    feature = "op_create_tenant",
    feature = "op_get_reputation_entity",
    feature = "op_get_tenant",
    feature = "op_list_reputation_entities",
    feature = "op_update_reputation_entity_customer_managed_status"
))]
mod _sending_status;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_update_configuration_set"
))]
mod _signature_format;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_update_configuration_set"
))]
mod _signing_scheme;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_update_configuration_set"
))]
mod _smime_signing_scheme;

#[cfg(any(
    feature = "op_create_configuration_set_event_destination",
    feature = "op_get_configuration_set_event_destinations",
    feature = "op_update_configuration_set_event_destination"
))]
mod _sns_destination;

#[cfg(feature = "op_get_email_identity")]
mod _soa_record;

#[cfg(any(
    feature = "op_create_multi_region_endpoint",
    feature = "op_delete_multi_region_endpoint",
    feature = "op_get_multi_region_endpoint",
    feature = "op_list_multi_region_endpoints"
))]
mod _status;

#[cfg(any(feature = "op_get_reputation_entity", feature = "op_list_reputation_entities"))]
mod _status_record;

#[cfg(any(
    feature = "op_create_contact",
    feature = "op_create_contact_list",
    feature = "op_get_contact",
    feature = "op_get_contact_list",
    feature = "op_list_contacts",
    feature = "op_update_contact",
    feature = "op_update_contact_list"
))]
mod _subscription_status;

#[cfg(feature = "op_get_suppressed_destination")]
mod _suppressed_destination;

#[cfg(feature = "op_get_suppressed_destination")]
mod _suppressed_destination_attributes;

#[cfg(feature = "op_list_suppressed_destinations")]
mod _suppressed_destination_summary;

#[cfg(feature = "op_get_account")]
mod _suppression_attributes;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_account",
    feature = "op_get_configuration_set",
    feature = "op_put_account_suppression_attributes",
    feature = "op_put_configuration_set_suppression_options"
))]
mod _suppression_condition_threshold;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_account",
    feature = "op_get_configuration_set",
    feature = "op_put_account_suppression_attributes",
    feature = "op_put_configuration_set_suppression_options"
))]
mod _suppression_confidence_threshold;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_account",
    feature = "op_get_configuration_set",
    feature = "op_put_account_suppression_attributes",
    feature = "op_put_configuration_set_suppression_options"
))]
mod _suppression_confidence_verdict_threshold;

#[cfg(any(
    feature = "op_create_import_job",
    feature = "op_get_import_job",
    feature = "op_list_import_jobs"
))]
mod _suppression_list_destination;

#[cfg(any(
    feature = "op_create_import_job",
    feature = "op_get_import_job",
    feature = "op_list_import_jobs"
))]
mod _suppression_list_import_action;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_create_tenant",
    feature = "op_get_account",
    feature = "op_get_configuration_set",
    feature = "op_get_suppressed_destination",
    feature = "op_get_tenant",
    feature = "op_list_suppressed_destinations",
    feature = "op_put_account_suppression_attributes",
    feature = "op_put_configuration_set_suppression_options",
    feature = "op_put_suppressed_destination",
    feature = "op_put_tenant_suppression_attributes"
))]
mod _suppression_list_reason;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_create_tenant",
    feature = "op_get_configuration_set",
    feature = "op_get_tenant",
    feature = "op_put_configuration_set_suppression_options",
    feature = "op_put_tenant_suppression_attributes"
))]
mod _suppression_list_scope;

#[cfg(any(feature = "op_create_configuration_set", feature = "op_get_configuration_set"))]
mod _suppression_options;

#[cfg(any(feature = "op_get_account", feature = "op_put_account_suppression_attributes"))]
mod _suppression_validation_attributes;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_put_configuration_set_suppression_options"
))]
mod _suppression_validation_options;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_create_contact_list",
    feature = "op_create_custom_verification_email_template",
    feature = "op_create_dedicated_ip_pool",
    feature = "op_create_deliverability_test_report",
    feature = "op_create_email_identity",
    feature = "op_create_email_template",
    feature = "op_create_multi_region_endpoint",
    feature = "op_create_tenant",
    feature = "op_get_configuration_set",
    feature = "op_get_contact_list",
    feature = "op_get_custom_verification_email_template",
    feature = "op_get_deliverability_test_report",
    feature = "op_get_email_identity",
    feature = "op_get_email_template",
    feature = "op_get_tenant",
    feature = "op_list_tags_for_resource",
    feature = "op_tag_resource"
))]
mod _tag;

#[cfg(any(
    feature = "op_create_deliverability_test_report",
    feature = "op_send_bulk_email",
    feature = "op_send_email"
))]
mod _template;

#[cfg(feature = "op_get_tenant")]
mod _tenant;

#[cfg(feature = "op_list_tenants")]
mod _tenant_info;

#[cfg(feature = "op_list_tenant_resources")]
mod _tenant_resource;

#[cfg(any(feature = "op_create_tenant", feature = "op_get_tenant"))]
mod _tenant_suppression_attributes;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_put_configuration_set_delivery_options"
))]
mod _tls_policy;

#[cfg(any(
    feature = "op_create_contact_list",
    feature = "op_get_contact_list",
    feature = "op_update_contact_list"
))]
mod _topic;

#[cfg(feature = "op_list_contacts")]
mod _topic_filter;

#[cfg(any(
    feature = "op_create_contact",
    feature = "op_get_contact",
    feature = "op_list_contacts",
    feature = "op_update_contact"
))]
mod _topic_preference;

#[cfg(any(feature = "op_send_bulk_email", feature = "op_send_email"))]
mod _tracking_configuration_overrides;

#[cfg(any(feature = "op_create_configuration_set", feature = "op_get_configuration_set"))]
mod _tracking_options;

#[cfg(any(feature = "op_get_account", feature = "op_put_account_vdm_attributes"))]
mod _vdm_attributes;

#[cfg(any(
    feature = "op_create_configuration_set",
    feature = "op_get_configuration_set",
    feature = "op_put_configuration_set_vdm_options"
))]
mod _vdm_options;

#[cfg(feature = "op_get_email_identity")]
mod _verification_error;

#[cfg(feature = "op_get_email_identity")]
mod _verification_info;

#[cfg(any(feature = "op_get_email_identity", feature = "op_list_email_identities"))]
mod _verification_status;

#[cfg(feature = "op_get_domain_statistics_report")]
mod _volume_statistics;

#[cfg(any(feature = "op_get_dedicated_ip", feature = "op_get_dedicated_ips"))]
mod _warmup_status;

/// Builders
pub mod builders;

/// Error types that Amazon Simple Email Service can respond with.
pub mod error;
