// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(any(
    feature = "op_add_user_pool_client_secret",
    feature = "op_list_user_pool_client_secrets"
))]
pub use crate::types::_client_secret_descriptor_type::ClientSecretDescriptorTypeBuilder;

#[cfg(any(
    feature = "op_admin_create_user",
    feature = "op_list_users",
    feature = "op_list_users_in_group"
))]
pub use crate::types::_user_type::UserTypeBuilder;

#[cfg(any(
    feature = "op_admin_disable_provider_for_user",
    feature = "op_admin_link_provider_for_user"
))]
pub use crate::types::_provider_user_identifier_type::ProviderUserIdentifierTypeBuilder;

#[cfg(any(
    feature = "op_admin_get_device",
    feature = "op_admin_list_devices",
    feature = "op_get_device",
    feature = "op_list_devices"
))]
pub use crate::types::_device_type::DeviceTypeBuilder;

#[cfg(any(
    feature = "op_admin_initiate_auth",
    feature = "op_admin_respond_to_auth_challenge",
    feature = "op_confirm_forgot_password",
    feature = "op_confirm_sign_up",
    feature = "op_forgot_password",
    feature = "op_initiate_auth",
    feature = "op_resend_confirmation_code",
    feature = "op_respond_to_auth_challenge",
    feature = "op_sign_up"
))]
pub use crate::types::_analytics_metadata_type::AnalyticsMetadataTypeBuilder;

#[cfg(any(feature = "op_admin_initiate_auth", feature = "op_admin_respond_to_auth_challenge"))]
pub use crate::types::_context_data_type::ContextDataTypeBuilder;

#[cfg(any(
    feature = "op_admin_initiate_auth",
    feature = "op_admin_respond_to_auth_challenge",
    feature = "op_get_tokens_from_refresh_token",
    feature = "op_initiate_auth",
    feature = "op_respond_to_auth_challenge"
))]
pub use crate::types::_authentication_result_type::AuthenticationResultTypeBuilder;

#[cfg(any(feature = "op_admin_set_user_mfa_preference", feature = "op_set_user_mfa_preference"))]
pub use crate::types::_sms_mfa_settings_type::SmsMfaSettingsTypeBuilder;

#[cfg(any(feature = "op_admin_set_user_mfa_preference", feature = "op_set_user_mfa_preference"))]
pub use crate::types::_software_token_mfa_settings_type::SoftwareTokenMfaSettingsTypeBuilder;

#[cfg(any(feature = "op_admin_set_user_mfa_preference", feature = "op_set_user_mfa_preference"))]
pub use crate::types::_email_mfa_settings_type::EmailMfaSettingsTypeBuilder;

#[cfg(any(feature = "op_admin_set_user_mfa_preference", feature = "op_set_user_mfa_preference"))]
pub use crate::types::_web_authn_mfa_settings_type::WebAuthnMfaSettingsTypeBuilder;

#[cfg(feature = "op_confirm_device")]
pub use crate::types::_device_secret_verifier_config_type::DeviceSecretVerifierConfigTypeBuilder;

#[cfg(any(
    feature = "op_confirm_forgot_password",
    feature = "op_confirm_sign_up",
    feature = "op_forgot_password",
    feature = "op_initiate_auth",
    feature = "op_resend_confirmation_code",
    feature = "op_respond_to_auth_challenge",
    feature = "op_sign_up"
))]
pub use crate::types::_user_context_data_type::UserContextDataTypeBuilder;

#[cfg(any(
    feature = "op_admin_list_groups_for_user",
    feature = "op_create_group",
    feature = "op_get_group",
    feature = "op_list_groups",
    feature = "op_update_group"
))]
pub use crate::types::_group_type::GroupTypeBuilder;

#[cfg(any(
    feature = "op_create_identity_provider",
    feature = "op_describe_identity_provider",
    feature = "op_get_identity_provider_by_identifier",
    feature = "op_update_identity_provider"
))]
pub use crate::types::_identity_provider_type::IdentityProviderTypeBuilder;

#[cfg(any(
    feature = "op_create_managed_login_branding",
    feature = "op_describe_managed_login_branding",
    feature = "op_describe_managed_login_branding_by_client",
    feature = "op_update_managed_login_branding"
))]
pub use crate::types::_managed_login_branding_type::ManagedLoginBrandingTypeBuilder;

#[cfg(any(
    feature = "op_create_resource_server",
    feature = "op_describe_resource_server",
    feature = "op_list_resource_servers",
    feature = "op_update_resource_server"
))]
pub use crate::types::_resource_server_type::ResourceServerTypeBuilder;

#[cfg(any(
    feature = "op_create_terms",
    feature = "op_describe_terms",
    feature = "op_describe_terms_by_client",
    feature = "op_update_terms"
))]
pub use crate::types::_terms_type::TermsTypeBuilder;

#[cfg(any(
    feature = "op_create_user_import_job",
    feature = "op_describe_user_import_job",
    feature = "op_list_user_import_jobs",
    feature = "op_start_user_import_job",
    feature = "op_stop_user_import_job"
))]
pub use crate::types::_user_import_job_type::UserImportJobTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_user_pool_policy_type::UserPoolPolicyTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
pub use crate::types::_lambda_config_type::LambdaConfigTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_verification_message_template_type::VerificationMessageTemplateTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_user_attribute_update_settings_type::UserAttributeUpdateSettingsTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_device_configuration_type::DeviceConfigurationTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_email_configuration_type::EmailConfigurationTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_get_user_pool_mfa_config",
    feature = "op_set_user_pool_mfa_config",
    feature = "op_update_user_pool"
))]
pub use crate::types::_sms_configuration_type::SmsConfigurationTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_admin_create_user_config_type::AdminCreateUserConfigTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_user_pool_add_ons_type::UserPoolAddOnsTypeBuilder;

#[cfg(any(feature = "op_create_user_pool", feature = "op_describe_user_pool"))]
pub use crate::types::_username_configuration_type::UsernameConfigurationTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_account_recovery_setting_type::AccountRecoverySettingTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_key_configuration_type::KeyConfigurationTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_issuer_configuration_type::IssuerConfigurationTypeBuilder;

#[cfg(any(feature = "op_create_user_pool", feature = "op_describe_user_pool"))]
pub use crate::types::_user_pool_type::UserPoolTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
pub use crate::types::_token_validity_units_type::TokenValidityUnitsTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
pub use crate::types::_analytics_configuration_type::AnalyticsConfigurationTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
pub use crate::types::_refresh_token_rotation_type::RefreshTokenRotationTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
pub use crate::types::_user_pool_client_type::UserPoolClientTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool_domain",
    feature = "op_describe_user_pool_domain",
    feature = "op_update_user_pool_domain"
))]
pub use crate::types::_custom_domain_config_type::CustomDomainConfigTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool_domain",
    feature = "op_describe_user_pool_domain",
    feature = "op_update_user_pool_domain"
))]
pub use crate::types::_routing_type::RoutingTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool_replica",
    feature = "op_delete_user_pool_replica",
    feature = "op_list_user_pool_replicas",
    feature = "op_update_user_pool_replica"
))]
pub use crate::types::_user_pool_replica_type::UserPoolReplicaTypeBuilder;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_risk_configuration_type::RiskConfigurationTypeBuilder;

#[cfg(feature = "op_describe_user_pool_domain")]
pub use crate::types::_domain_description_type::DomainDescriptionTypeBuilder;

#[cfg(any(
    feature = "op_forgot_password",
    feature = "op_get_user_attribute_verification_code",
    feature = "op_resend_confirmation_code",
    feature = "op_sign_up",
    feature = "op_update_user_attributes"
))]
pub use crate::types::_code_delivery_details_type::CodeDeliveryDetailsTypeBuilder;

#[cfg(feature = "op_get_client_token")]
pub use crate::types::_client_authentication_result_type::ClientAuthenticationResultTypeBuilder;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
pub use crate::types::_log_delivery_configuration_type::LogDeliveryConfigurationTypeBuilder;

#[cfg(any(feature = "op_get_provisioned_limit", feature = "op_update_provisioned_limit"))]
pub use crate::types::_limit_definition_type::LimitDefinitionTypeBuilder;

#[cfg(any(feature = "op_get_provisioned_limit", feature = "op_update_provisioned_limit"))]
pub use crate::types::_limit_type::LimitTypeBuilder;

#[cfg(any(feature = "op_get_ui_customization", feature = "op_set_ui_customization"))]
pub use crate::types::_ui_customization_type::UiCustomizationTypeBuilder;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
pub use crate::types::_sms_mfa_config_type::SmsMfaConfigTypeBuilder;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
pub use crate::types::_software_token_mfa_config_type::SoftwareTokenMfaConfigTypeBuilder;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
pub use crate::types::_email_mfa_config_type::EmailMfaConfigTypeBuilder;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
pub use crate::types::_web_authn_configuration_type::WebAuthnConfigurationTypeBuilder;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_compromised_credentials_risk_configuration_type::CompromisedCredentialsRiskConfigurationTypeBuilder;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_account_takeover_risk_configuration_type::AccountTakeoverRiskConfigurationTypeBuilder;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_risk_exception_configuration_type::RiskExceptionConfigurationTypeBuilder;

#[cfg(any(
    feature = "op_add_custom_attributes",
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool"
))]
pub use crate::types::_schema_attribute_type::SchemaAttributeTypeBuilder;

#[cfg(any(
    feature = "op_admin_create_user",
    feature = "op_admin_get_device",
    feature = "op_admin_get_user",
    feature = "op_admin_list_devices",
    feature = "op_admin_update_user_attributes",
    feature = "op_get_device",
    feature = "op_get_user",
    feature = "op_list_devices",
    feature = "op_list_users",
    feature = "op_list_users_in_group",
    feature = "op_sign_up",
    feature = "op_update_user_attributes"
))]
pub use crate::types::_attribute_type::AttributeTypeBuilder;

#[cfg(any(
    feature = "op_admin_create_user",
    feature = "op_admin_get_user",
    feature = "op_admin_set_user_settings",
    feature = "op_get_user",
    feature = "op_list_users",
    feature = "op_list_users_in_group",
    feature = "op_set_user_settings"
))]
pub use crate::types::_mfa_option_type::MfaOptionTypeBuilder;

#[cfg(any(
    feature = "op_admin_initiate_auth",
    feature = "op_admin_respond_to_auth_challenge",
    feature = "op_get_tokens_from_refresh_token",
    feature = "op_initiate_auth",
    feature = "op_respond_to_auth_challenge"
))]
pub use crate::types::_new_device_metadata_type::NewDeviceMetadataTypeBuilder;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_auth_event_type::AuthEventTypeBuilder;

#[cfg(any(
    feature = "op_create_managed_login_branding",
    feature = "op_describe_managed_login_branding",
    feature = "op_describe_managed_login_branding_by_client",
    feature = "op_update_managed_login_branding"
))]
pub use crate::types::_asset_type::AssetTypeBuilder;

#[cfg(any(
    feature = "op_create_resource_server",
    feature = "op_describe_resource_server",
    feature = "op_list_resource_servers",
    feature = "op_update_resource_server"
))]
pub use crate::types::_resource_server_scope_type::ResourceServerScopeTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_password_policy_type::PasswordPolicyTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_sign_in_policy_type::SignInPolicyTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
pub use crate::types::_pre_token_generation_version_config_type::PreTokenGenerationVersionConfigTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
pub use crate::types::_custom_sms_lambda_version_config_type::CustomSmsLambdaVersionConfigTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
pub use crate::types::_custom_email_lambda_version_config_type::CustomEmailLambdaVersionConfigTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
pub use crate::types::_inbound_federation_lambda_type::InboundFederationLambdaTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_get_user_pool_mfa_config",
    feature = "op_set_user_pool_mfa_config",
    feature = "op_update_user_pool"
))]
pub use crate::types::_eums_sms_configuration_type::EumsSmsConfigurationTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_message_template_type::MessageTemplateTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_advanced_security_additional_flows_type::AdvancedSecurityAdditionalFlowsTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool_domain",
    feature = "op_describe_user_pool_domain",
    feature = "op_update_user_pool_domain"
))]
pub use crate::types::_failover_type::FailoverTypeBuilder;

#[cfg(feature = "op_list_identity_providers")]
pub use crate::types::_provider_description::ProviderDescriptionBuilder;

#[cfg(feature = "op_list_terms")]
pub use crate::types::_terms_description_type::TermsDescriptionTypeBuilder;

#[cfg(feature = "op_list_user_pool_clients")]
pub use crate::types::_user_pool_client_description::UserPoolClientDescriptionBuilder;

#[cfg(feature = "op_list_user_pools")]
pub use crate::types::_user_pool_description_type::UserPoolDescriptionTypeBuilder;

#[cfg(feature = "op_list_web_authn_credentials")]
pub use crate::types::_web_authn_credential_description::WebAuthnCredentialDescriptionBuilder;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
pub use crate::types::_log_configuration_type::LogConfigurationTypeBuilder;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_compromised_credentials_actions_type::CompromisedCredentialsActionsTypeBuilder;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_notify_configuration_type::NotifyConfigurationTypeBuilder;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_account_takeover_actions_type::AccountTakeoverActionsTypeBuilder;

#[cfg(any(
    feature = "op_add_custom_attributes",
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool"
))]
pub use crate::types::_number_attribute_constraints_type::NumberAttributeConstraintsTypeBuilder;

#[cfg(any(
    feature = "op_add_custom_attributes",
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool"
))]
pub use crate::types::_string_attribute_constraints_type::StringAttributeConstraintsTypeBuilder;

#[cfg(any(feature = "op_admin_initiate_auth", feature = "op_admin_respond_to_auth_challenge"))]
pub use crate::types::_http_header::HttpHeaderBuilder;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_event_risk_type::EventRiskTypeBuilder;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_event_context_data_type::EventContextDataTypeBuilder;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_event_feedback_type::EventFeedbackTypeBuilder;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_recovery_option_type::RecoveryOptionTypeBuilder;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
pub use crate::types::_cloud_watch_logs_configuration_type::CloudWatchLogsConfigurationTypeBuilder;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
pub use crate::types::_s3_configuration_type::S3ConfigurationTypeBuilder;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
pub use crate::types::_firehose_configuration_type::FirehoseConfigurationTypeBuilder;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_notify_email_type::NotifyEmailTypeBuilder;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_account_takeover_action_type::AccountTakeoverActionTypeBuilder;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_challenge_response_type::ChallengeResponseTypeBuilder;
