// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(any(
    feature = "op_abort_multipart_upload",
    feature = "op_complete_multipart_upload",
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_delete_object",
    feature = "op_delete_object_annotation",
    feature = "op_delete_objects",
    feature = "op_get_bucket_accelerate_configuration",
    feature = "op_get_object",
    feature = "op_get_object_acl",
    feature = "op_get_object_annotation",
    feature = "op_get_object_attributes",
    feature = "op_get_object_legal_hold",
    feature = "op_get_object_retention",
    feature = "op_get_object_tagging",
    feature = "op_get_object_torrent",
    feature = "op_head_object",
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_annotations",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2",
    feature = "op_list_parts",
    feature = "op_put_object",
    feature = "op_put_object_acl",
    feature = "op_put_object_annotation",
    feature = "op_put_object_legal_hold",
    feature = "op_put_object_lock_configuration",
    feature = "op_put_object_retention",
    feature = "op_put_object_tagging",
    feature = "op_restore_object",
    feature = "op_update_object_encryption",
    feature = "op_upload_part",
    feature = "op_upload_part_copy"
))]
pub use crate::types::_request_payer::RequestPayer;

#[cfg(any(
    feature = "op_abort_multipart_upload",
    feature = "op_complete_multipart_upload",
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_delete_object",
    feature = "op_delete_object_annotation",
    feature = "op_delete_objects",
    feature = "op_get_bucket_accelerate_configuration",
    feature = "op_get_object",
    feature = "op_get_object_acl",
    feature = "op_get_object_annotation",
    feature = "op_get_object_attributes",
    feature = "op_get_object_torrent",
    feature = "op_head_object",
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_annotations",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2",
    feature = "op_list_parts",
    feature = "op_put_object",
    feature = "op_put_object_acl",
    feature = "op_put_object_annotation",
    feature = "op_put_object_legal_hold",
    feature = "op_put_object_lock_configuration",
    feature = "op_put_object_retention",
    feature = "op_restore_object",
    feature = "op_update_object_encryption",
    feature = "op_upload_part",
    feature = "op_upload_part_copy",
    feature = "op_write_get_object_response"
))]
pub use crate::types::_request_charged::RequestCharged;

#[cfg(feature = "op_complete_multipart_upload")]
pub use crate::types::_completed_multipart_upload::CompletedMultipartUpload;

#[cfg(any(
    feature = "op_complete_multipart_upload",
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_get_object",
    feature = "op_get_object_annotation",
    feature = "op_get_object_attributes",
    feature = "op_head_object",
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2",
    feature = "op_list_parts",
    feature = "op_put_object",
    feature = "op_put_object_annotation"
))]
pub use crate::types::_checksum_type::ChecksumType;

#[cfg(any(
    feature = "op_complete_multipart_upload",
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_create_session",
    feature = "op_get_bucket_encryption",
    feature = "op_get_object",
    feature = "op_get_object_annotation",
    feature = "op_head_object",
    feature = "op_put_bucket_encryption",
    feature = "op_put_object",
    feature = "op_put_object_annotation",
    feature = "op_restore_object",
    feature = "op_upload_part",
    feature = "op_upload_part_copy",
    feature = "op_write_get_object_response"
))]
pub use crate::types::_server_side_encryption::ServerSideEncryption;

#[cfg(any(
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_put_object",
    feature = "op_put_object_acl",
    feature = "op_restore_object"
))]
pub use crate::types::_object_canned_acl::ObjectCannedAcl;

#[cfg(any(
    feature = "op_copy_object",
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_create_bucket_metadata_table_configuration",
    feature = "op_create_multipart_upload",
    feature = "op_delete_objects",
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_annotations",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2",
    feature = "op_list_parts",
    feature = "op_put_bucket_abac",
    feature = "op_put_bucket_accelerate_configuration",
    feature = "op_put_bucket_acl",
    feature = "op_put_bucket_cors",
    feature = "op_put_bucket_encryption",
    feature = "op_put_bucket_lifecycle_configuration",
    feature = "op_put_bucket_logging",
    feature = "op_put_bucket_ownership_controls",
    feature = "op_put_bucket_policy",
    feature = "op_put_bucket_replication",
    feature = "op_put_bucket_request_payment",
    feature = "op_put_bucket_tagging",
    feature = "op_put_bucket_versioning",
    feature = "op_put_bucket_website",
    feature = "op_put_object",
    feature = "op_put_object_acl",
    feature = "op_put_object_annotation",
    feature = "op_put_object_legal_hold",
    feature = "op_put_object_lock_configuration",
    feature = "op_put_object_retention",
    feature = "op_put_object_tagging",
    feature = "op_put_public_access_block",
    feature = "op_restore_object",
    feature = "op_update_bucket_metadata_annotation_table_configuration",
    feature = "op_update_bucket_metadata_inventory_table_configuration",
    feature = "op_update_bucket_metadata_journal_table_configuration",
    feature = "op_update_object_encryption",
    feature = "op_upload_part"
))]
pub use crate::types::_checksum_algorithm::ChecksumAlgorithm;

#[cfg(feature = "op_copy_object")]
pub use crate::types::_metadata_directive::MetadataDirective;

#[cfg(feature = "op_copy_object")]
pub use crate::types::_tagging_directive::TaggingDirective;

#[cfg(feature = "op_copy_object")]
pub use crate::types::_annotation_directive::AnnotationDirective;

#[cfg(any(
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_get_bucket_replication",
    feature = "op_get_object",
    feature = "op_get_object_attributes",
    feature = "op_head_object",
    feature = "op_list_multipart_uploads",
    feature = "op_list_parts",
    feature = "op_put_bucket_replication",
    feature = "op_put_object",
    feature = "op_restore_object",
    feature = "op_write_get_object_response"
))]
pub use crate::types::_storage_class::StorageClass;

#[cfg(any(
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_get_object",
    feature = "op_head_object",
    feature = "op_put_object",
    feature = "op_write_get_object_response"
))]
pub use crate::types::_object_lock_mode::ObjectLockMode;

#[cfg(any(
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_get_object",
    feature = "op_get_object_legal_hold",
    feature = "op_head_object",
    feature = "op_put_object",
    feature = "op_put_object_legal_hold",
    feature = "op_write_get_object_response"
))]
pub use crate::types::_object_lock_legal_hold_status::ObjectLockLegalHoldStatus;

#[cfg(any(
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_get_object",
    feature = "op_get_object_retention",
    feature = "op_head_object",
    feature = "op_put_object",
    feature = "op_put_object_retention"
))]
pub use crate::types::_object_lock_event_hold::ObjectLockEventHold;

#[cfg(feature = "op_copy_object")]
pub use crate::types::_copy_object_result::CopyObjectResult;

#[cfg(any(feature = "op_create_bucket", feature = "op_put_bucket_acl"))]
pub use crate::types::_bucket_canned_acl::BucketCannedAcl;

#[cfg(feature = "op_create_bucket")]
pub use crate::types::_create_bucket_configuration::CreateBucketConfiguration;

#[cfg(any(
    feature = "op_create_bucket",
    feature = "op_get_bucket_ownership_controls",
    feature = "op_put_bucket_ownership_controls"
))]
pub use crate::types::_object_ownership::ObjectOwnership;

#[cfg(feature = "op_create_bucket")]
pub use crate::types::_bucket_namespace::BucketNamespace;

#[cfg(feature = "op_create_bucket_metadata_configuration")]
pub use crate::types::_metadata_configuration::MetadataConfiguration;

#[cfg(feature = "op_create_bucket_metadata_table_configuration")]
pub use crate::types::_metadata_table_configuration::MetadataTableConfiguration;

#[cfg(feature = "op_create_session")]
pub use crate::types::_session_mode::SessionMode;

#[cfg(feature = "op_create_session")]
pub use crate::types::_session_credentials::SessionCredentials;

#[cfg(feature = "op_delete_objects")]
pub use crate::types::_delete::Delete;

#[cfg(any(feature = "op_get_bucket_abac", feature = "op_put_bucket_abac"))]
pub use crate::types::_abac_status::AbacStatus;

#[cfg(any(
    feature = "op_get_bucket_accelerate_configuration",
    feature = "op_put_bucket_accelerate_configuration"
))]
pub use crate::types::_bucket_accelerate_status::BucketAccelerateStatus;

#[cfg(any(
    feature = "op_get_bucket_acl",
    feature = "op_get_object_acl",
    feature = "op_list_buckets",
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2",
    feature = "op_list_parts",
    feature = "op_put_bucket_acl",
    feature = "op_put_object_acl"
))]
pub use crate::types::_owner::Owner;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_analytics_configuration::AnalyticsConfiguration;

#[cfg(any(feature = "op_get_bucket_encryption", feature = "op_put_bucket_encryption"))]
pub use crate::types::_server_side_encryption_configuration::ServerSideEncryptionConfiguration;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
pub use crate::types::_intelligent_tiering_configuration::IntelligentTieringConfiguration;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_configuration::InventoryConfiguration;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_transition_default_minimum_object_size::TransitionDefaultMinimumObjectSize;

#[cfg(any(feature = "op_create_bucket", feature = "op_get_bucket_location"))]
pub use crate::types::_bucket_location_constraint::BucketLocationConstraint;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
pub use crate::types::_logging_enabled::LoggingEnabled;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
pub use crate::types::_get_bucket_metadata_configuration_result::GetBucketMetadataConfigurationResult;

#[cfg(feature = "op_get_bucket_metadata_table_configuration")]
pub use crate::types::_get_bucket_metadata_table_configuration_result::GetBucketMetadataTableConfigurationResult;

#[cfg(any(
    feature = "op_get_bucket_metrics_configuration",
    feature = "op_list_bucket_metrics_configurations",
    feature = "op_put_bucket_metrics_configuration"
))]
pub use crate::types::_metrics_configuration::MetricsConfiguration;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_event_bridge_configuration::EventBridgeConfiguration;

#[cfg(any(
    feature = "op_get_bucket_ownership_controls",
    feature = "op_put_bucket_ownership_controls"
))]
pub use crate::types::_ownership_controls::OwnershipControls;

#[cfg(feature = "op_get_bucket_policy_status")]
pub use crate::types::_policy_status::PolicyStatus;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replication_configuration::ReplicationConfiguration;

#[cfg(any(feature = "op_get_bucket_request_payment", feature = "op_put_bucket_request_payment"))]
pub use crate::types::_payer::Payer;

#[cfg(any(feature = "op_get_bucket_versioning", feature = "op_put_bucket_versioning"))]
pub use crate::types::_bucket_versioning_status::BucketVersioningStatus;

#[cfg(feature = "op_get_bucket_versioning")]
pub use crate::types::_mfa_delete_status::MfaDeleteStatus;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
pub use crate::types::_redirect_all_requests_to::RedirectAllRequestsTo;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
pub use crate::types::_index_document::IndexDocument;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
pub use crate::types::_error_document::ErrorDocument;

#[cfg(any(
    feature = "op_get_object",
    feature = "op_get_object_annotation",
    feature = "op_head_object"
))]
pub use crate::types::_checksum_mode::ChecksumMode;

#[cfg(any(
    feature = "op_get_object",
    feature = "op_get_object_annotation",
    feature = "op_head_object",
    feature = "op_list_object_annotations",
    feature = "op_write_get_object_response"
))]
pub use crate::types::_replication_status::ReplicationStatus;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_get_object",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
pub use crate::types::_intelligent_tiering_access_tier::IntelligentTieringAccessTier;

#[cfg(feature = "op_get_object_attributes")]
pub use crate::types::_checksum::Checksum;

#[cfg(feature = "op_get_object_attributes")]
pub use crate::types::_get_object_attributes_parts::GetObjectAttributesParts;

#[cfg(any(feature = "op_get_object_legal_hold", feature = "op_put_object_legal_hold"))]
pub use crate::types::_object_lock_legal_hold::ObjectLockLegalHold;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_put_object_lock_configuration"
))]
pub use crate::types::_object_lock_configuration::ObjectLockConfiguration;

#[cfg(any(feature = "op_get_object_retention", feature = "op_put_object_retention"))]
pub use crate::types::_object_lock_retention::ObjectLockRetention;

#[cfg(any(feature = "op_get_public_access_block", feature = "op_put_public_access_block"))]
pub use crate::types::_public_access_block_configuration::PublicAccessBlockConfiguration;

#[cfg(any(feature = "op_create_bucket", feature = "op_head_bucket"))]
pub use crate::types::_location_type::LocationType;

#[cfg(feature = "op_head_object")]
pub use crate::types::_archive_status::ArchiveStatus;

#[cfg(any(
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2"
))]
pub use crate::types::_encoding_type::EncodingType;

#[cfg(any(feature = "op_list_multipart_uploads", feature = "op_list_parts"))]
pub use crate::types::_initiator::Initiator;

#[cfg(feature = "op_put_bucket_accelerate_configuration")]
pub use crate::types::_accelerate_configuration::AccelerateConfiguration;

#[cfg(any(feature = "op_put_bucket_acl", feature = "op_put_object_acl"))]
pub use crate::types::_access_control_policy::AccessControlPolicy;

#[cfg(feature = "op_put_bucket_cors")]
pub use crate::types::_cors_configuration::CorsConfiguration;

#[cfg(feature = "op_put_bucket_lifecycle_configuration")]
pub use crate::types::_bucket_lifecycle_configuration::BucketLifecycleConfiguration;

#[cfg(feature = "op_put_bucket_logging")]
pub use crate::types::_bucket_logging_status::BucketLoggingStatus;

#[cfg(feature = "op_put_bucket_notification_configuration")]
pub use crate::types::_notification_configuration::NotificationConfiguration;

#[cfg(feature = "op_put_bucket_request_payment")]
pub use crate::types::_request_payment_configuration::RequestPaymentConfiguration;

#[cfg(any(
    feature = "op_put_bucket_tagging",
    feature = "op_put_object_tagging",
    feature = "op_restore_object"
))]
pub use crate::types::_tagging::Tagging;

#[cfg(feature = "op_put_bucket_versioning")]
pub use crate::types::_versioning_configuration::VersioningConfiguration;

#[cfg(feature = "op_put_bucket_website")]
pub use crate::types::_website_configuration::WebsiteConfiguration;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_restore_request::RestoreRequest;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_expression_type::ExpressionType;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_request_progress::RequestProgress;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_input_serialization::InputSerialization;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_output_serialization::OutputSerialization;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_scan_range::ScanRange;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_select_object_content_event_stream::SelectObjectContentEventStream;

#[cfg(feature = "op_update_bucket_metadata_annotation_table_configuration")]
pub use crate::types::_annotation_table_configuration_updates::AnnotationTableConfigurationUpdates;

#[cfg(feature = "op_update_bucket_metadata_inventory_table_configuration")]
pub use crate::types::_inventory_table_configuration_updates::InventoryTableConfigurationUpdates;

#[cfg(feature = "op_update_bucket_metadata_journal_table_configuration")]
pub use crate::types::_journal_table_configuration_updates::JournalTableConfigurationUpdates;

#[cfg(feature = "op_update_object_encryption")]
pub use crate::types::_object_encryption::ObjectEncryption;

#[cfg(feature = "op_upload_part_copy")]
pub use crate::types::_copy_part_result::CopyPartResult;

#[cfg(feature = "op_create_bucket")]
pub use crate::types::_location_info::LocationInfo;

#[cfg(feature = "op_create_bucket")]
pub use crate::types::_bucket_info::BucketInfo;

#[cfg(feature = "op_create_bucket_metadata_configuration")]
pub use crate::types::_journal_table_configuration::JournalTableConfiguration;

#[cfg(feature = "op_create_bucket_metadata_configuration")]
pub use crate::types::_inventory_table_configuration::InventoryTableConfiguration;

#[cfg(feature = "op_create_bucket_metadata_configuration")]
pub use crate::types::_annotation_table_configuration::AnnotationTableConfiguration;

#[cfg(feature = "op_create_bucket_metadata_table_configuration")]
pub use crate::types::_s3_tables_destination::S3TablesDestination;

#[cfg(feature = "op_delete_objects")]
pub use crate::types::_deleted_object::DeletedObject;

#[cfg(feature = "op_delete_objects")]
pub use crate::types::_error::Error;

#[cfg(any(feature = "op_get_bucket_abac", feature = "op_put_bucket_abac"))]
pub use crate::types::_bucket_abac_status::BucketAbacStatus;

#[cfg(any(
    feature = "op_get_bucket_acl",
    feature = "op_get_object_acl",
    feature = "op_put_bucket_acl",
    feature = "op_put_object_acl",
    feature = "op_restore_object"
))]
pub use crate::types::_grant::Grant;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_analytics_filter::AnalyticsFilter;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_storage_class_analysis::StorageClassAnalysis;

#[cfg(any(feature = "op_get_bucket_cors", feature = "op_put_bucket_cors"))]
pub use crate::types::_cors_rule::CorsRule;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
pub use crate::types::_intelligent_tiering_filter::IntelligentTieringFilter;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
pub use crate::types::_intelligent_tiering_status::IntelligentTieringStatus;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_destination::InventoryDestination;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_filter::InventoryFilter;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_included_object_versions::InventoryIncludedObjectVersions;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_schedule::InventorySchedule;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_lifecycle_rule::LifecycleRule;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
pub use crate::types::_target_object_key_format::TargetObjectKeyFormat;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
pub use crate::types::_metadata_configuration_result::MetadataConfigurationResult;

#[cfg(feature = "op_get_bucket_metadata_table_configuration")]
pub use crate::types::_metadata_table_configuration_result::MetadataTableConfigurationResult;

#[cfg(any(
    feature = "op_get_bucket_metadata_configuration",
    feature = "op_get_bucket_metadata_table_configuration"
))]
pub use crate::types::_error_details::ErrorDetails;

#[cfg(any(
    feature = "op_get_bucket_metrics_configuration",
    feature = "op_list_bucket_metrics_configurations",
    feature = "op_put_bucket_metrics_configuration"
))]
pub use crate::types::_metrics_filter::MetricsFilter;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_topic_configuration::TopicConfiguration;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_queue_configuration::QueueConfiguration;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_lambda_function_configuration::LambdaFunctionConfiguration;

#[cfg(any(
    feature = "op_create_bucket",
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_get_bucket_metrics_configuration",
    feature = "op_get_bucket_replication",
    feature = "op_get_bucket_tagging",
    feature = "op_get_object_tagging",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_list_bucket_metrics_configurations",
    feature = "op_put_bucket_analytics_configuration",
    feature = "op_put_bucket_intelligent_tiering_configuration",
    feature = "op_put_bucket_lifecycle_configuration",
    feature = "op_put_bucket_metrics_configuration",
    feature = "op_put_bucket_replication",
    feature = "op_put_bucket_tagging",
    feature = "op_put_object_tagging",
    feature = "op_restore_object"
))]
pub use crate::types::_tag::Tag;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
pub use crate::types::_protocol::Protocol;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
pub use crate::types::_routing_rule::RoutingRule;

#[cfg(feature = "op_get_object_attributes")]
pub use crate::types::_object_attributes::ObjectAttributes;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_put_object_lock_configuration"
))]
pub use crate::types::_object_lock_enabled::ObjectLockEnabled;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_put_object_lock_configuration"
))]
pub use crate::types::_object_lock_rule::ObjectLockRule;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_get_object_retention",
    feature = "op_put_object_lock_configuration",
    feature = "op_put_object_retention"
))]
pub use crate::types::_object_lock_retention_mode::ObjectLockRetentionMode;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_get_object_retention",
    feature = "op_put_object_lock_configuration",
    feature = "op_put_object_retention"
))]
pub use crate::types::_event_hold_duration::EventHoldDuration;

#[cfg(any(feature = "op_list_buckets", feature = "op_list_directory_buckets"))]
pub use crate::types::_bucket::Bucket;

#[cfg(feature = "op_list_multipart_uploads")]
pub use crate::types::_multipart_upload::MultipartUpload;

#[cfg(any(
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2"
))]
pub use crate::types::_common_prefix::CommonPrefix;

#[cfg(feature = "op_list_object_annotations")]
pub use crate::types::_annotation_entry::AnnotationEntry;

#[cfg(any(
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2"
))]
pub use crate::types::_optional_object_attributes::OptionalObjectAttributes;

#[cfg(any(feature = "op_list_objects", feature = "op_list_objects_v2"))]
pub use crate::types::_object::Object;

#[cfg(feature = "op_list_object_versions")]
pub use crate::types::_object_version::ObjectVersion;

#[cfg(feature = "op_list_object_versions")]
pub use crate::types::_delete_marker_entry::DeleteMarkerEntry;

#[cfg(feature = "op_list_parts")]
pub use crate::types::_part::Part;

#[cfg(feature = "op_put_bucket_versioning")]
pub use crate::types::_mfa_delete::MfaDelete;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_glacier_job_parameters::GlacierJobParameters;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_restore_request_type::RestoreRequestType;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_tier::Tier;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_select_parameters::SelectParameters;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_output_location::OutputLocation;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_csv_input::CsvInput;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_compression_type::CompressionType;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_json_input::JsonInput;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_parquet_input::ParquetInput;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_csv_output::CsvOutput;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_json_output::JsonOutput;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_records_event::RecordsEvent;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_stats_event::StatsEvent;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_progress_event::ProgressEvent;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_continuation_event::ContinuationEvent;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_end_event::EndEvent;

#[cfg(any(
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_get_bucket_metadata_configuration",
    feature = "op_update_bucket_metadata_annotation_table_configuration"
))]
pub use crate::types::_annotation_configuration_state::AnnotationConfigurationState;

#[cfg(any(
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_update_bucket_metadata_annotation_table_configuration",
    feature = "op_update_bucket_metadata_inventory_table_configuration"
))]
pub use crate::types::_metadata_table_encryption_configuration::MetadataTableEncryptionConfiguration;

#[cfg(any(
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_get_bucket_metadata_configuration",
    feature = "op_update_bucket_metadata_inventory_table_configuration"
))]
pub use crate::types::_inventory_configuration_state::InventoryConfigurationState;

#[cfg(any(
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_get_bucket_metadata_configuration",
    feature = "op_update_bucket_metadata_journal_table_configuration"
))]
pub use crate::types::_record_expiration::RecordExpiration;

#[cfg(feature = "op_update_object_encryption")]
pub use crate::types::_ssekms_encryption::SsekmsEncryption;

#[cfg(feature = "op_complete_multipart_upload")]
pub use crate::types::_completed_part::CompletedPart;

#[cfg(feature = "op_create_bucket")]
pub use crate::types::_data_redundancy::DataRedundancy;

#[cfg(feature = "op_create_bucket")]
pub use crate::types::_bucket_type::BucketType;

#[cfg(feature = "op_delete_objects")]
pub use crate::types::_object_identifier::ObjectIdentifier;

#[cfg(any(
    feature = "op_get_bucket_acl",
    feature = "op_get_bucket_logging",
    feature = "op_get_object_acl",
    feature = "op_put_bucket_acl",
    feature = "op_put_bucket_logging",
    feature = "op_put_object_acl",
    feature = "op_restore_object"
))]
pub use crate::types::_grantee::Grantee;

#[cfg(any(
    feature = "op_get_bucket_acl",
    feature = "op_get_object_acl",
    feature = "op_put_bucket_acl",
    feature = "op_put_object_acl",
    feature = "op_restore_object"
))]
pub use crate::types::_permission::Permission;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_analytics_and_operator::AnalyticsAndOperator;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_storage_class_analysis_data_export::StorageClassAnalysisDataExport;

#[cfg(any(feature = "op_get_bucket_encryption", feature = "op_put_bucket_encryption"))]
pub use crate::types::_server_side_encryption_rule::ServerSideEncryptionRule;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
pub use crate::types::_intelligent_tiering_and_operator::IntelligentTieringAndOperator;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
pub use crate::types::_tiering::Tiering;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_s3_bucket_destination::InventoryS3BucketDestination;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_optional_field::InventoryOptionalField;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_frequency::InventoryFrequency;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_lifecycle_expiration::LifecycleExpiration;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_lifecycle_rule_filter::LifecycleRuleFilter;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_expiration_status::ExpirationStatus;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_noncurrent_version_expiration::NoncurrentVersionExpiration;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_abort_incomplete_multipart_upload::AbortIncompleteMultipartUpload;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
pub use crate::types::_target_grant::TargetGrant;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
pub use crate::types::_simple_prefix::SimplePrefix;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
pub use crate::types::_partitioned_prefix::PartitionedPrefix;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
pub use crate::types::_destination_result::DestinationResult;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
pub use crate::types::_journal_table_configuration_result::JournalTableConfigurationResult;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
pub use crate::types::_inventory_table_configuration_result::InventoryTableConfigurationResult;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
pub use crate::types::_annotation_table_configuration_result::AnnotationTableConfigurationResult;

#[cfg(feature = "op_get_bucket_metadata_table_configuration")]
pub use crate::types::_s3_tables_destination_result::S3TablesDestinationResult;

#[cfg(any(
    feature = "op_get_bucket_metrics_configuration",
    feature = "op_list_bucket_metrics_configurations",
    feature = "op_put_bucket_metrics_configuration"
))]
pub use crate::types::_metrics_and_operator::MetricsAndOperator;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_notification_configuration_filter::NotificationConfigurationFilter;

#[cfg(any(
    feature = "op_get_bucket_ownership_controls",
    feature = "op_put_bucket_ownership_controls"
))]
pub use crate::types::_ownership_controls_rule::OwnershipControlsRule;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replication_rule::ReplicationRule;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
pub use crate::types::_condition::Condition;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
pub use crate::types::_redirect::Redirect;

#[cfg(feature = "op_get_object_attributes")]
pub use crate::types::_object_part::ObjectPart;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_put_object_lock_configuration"
))]
pub use crate::types::_default_retention::DefaultRetention;

#[cfg(any(feature = "op_list_objects", feature = "op_list_objects_v2"))]
pub use crate::types::_object_storage_class::ObjectStorageClass;

#[cfg(any(
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2"
))]
pub use crate::types::_restore_status::RestoreStatus;

#[cfg(feature = "op_list_object_versions")]
pub use crate::types::_object_version_storage_class::ObjectVersionStorageClass;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_s3_location::S3Location;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_file_header_info::FileHeaderInfo;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_json_type::JsonType;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_quote_fields::QuoteFields;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_stats::Stats;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_progress::Progress;

#[cfg(any(
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_update_bucket_metadata_annotation_table_configuration",
    feature = "op_update_bucket_metadata_inventory_table_configuration"
))]
pub use crate::types::_table_sse_algorithm::TableSseAlgorithm;

#[cfg(any(
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_get_bucket_metadata_configuration",
    feature = "op_update_bucket_metadata_journal_table_configuration"
))]
pub use crate::types::_expiration_state::ExpirationState;

#[cfg(any(
    feature = "op_get_bucket_acl",
    feature = "op_get_bucket_logging",
    feature = "op_get_object_acl",
    feature = "op_put_bucket_acl",
    feature = "op_put_bucket_logging",
    feature = "op_put_object_acl",
    feature = "op_restore_object"
))]
pub use crate::types::_type_::Type;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_storage_class_analysis_schema_version::StorageClassAnalysisSchemaVersion;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_analytics_export_destination::AnalyticsExportDestination;

#[cfg(any(feature = "op_get_bucket_encryption", feature = "op_put_bucket_encryption"))]
pub use crate::types::_server_side_encryption_by_default::ServerSideEncryptionByDefault;

#[cfg(any(feature = "op_get_bucket_encryption", feature = "op_put_bucket_encryption"))]
pub use crate::types::_blocked_encryption_types::BlockedEncryptionTypes;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_format::InventoryFormat;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_encryption::InventoryEncryption;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_lifecycle_rule_and_operator::LifecycleRuleAndOperator;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_transition::Transition;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_noncurrent_version_transition::NoncurrentVersionTransition;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
pub use crate::types::_bucket_logs_permission::BucketLogsPermission;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
pub use crate::types::_partition_date_source::PartitionDateSource;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
pub use crate::types::_s3_tables_bucket_type::S3TablesBucketType;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_event::Event;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_s3_key_filter::S3KeyFilter;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replication_rule_filter::ReplicationRuleFilter;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replication_rule_status::ReplicationRuleStatus;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_source_selection_criteria::SourceSelectionCriteria;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_existing_object_replication::ExistingObjectReplication;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_destination::Destination;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_delete_marker_replication::DeleteMarkerReplication;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_encryption::Encryption;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_analytics_s3_bucket_destination::AnalyticsS3BucketDestination;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_sses3::Sses3;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_ssekms::Ssekms;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_transition_storage_class::TransitionStorageClass;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replication_rule_and_operator::ReplicationRuleAndOperator;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_sse_kms_encrypted_objects::SseKmsEncryptedObjects;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replica_modifications::ReplicaModifications;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_existing_object_replication_status::ExistingObjectReplicationStatus;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_access_control_translation::AccessControlTranslation;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_encryption_configuration::EncryptionConfiguration;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replication_time::ReplicationTime;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_metrics::Metrics;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_delete_marker_replication_status::DeleteMarkerReplicationStatus;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_metadata_entry::MetadataEntry;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_analytics_s3_export_file_format::AnalyticsS3ExportFileFormat;

#[cfg(any(feature = "op_get_bucket_encryption", feature = "op_put_bucket_encryption"))]
pub use crate::types::_encryption_type::EncryptionType;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_filter_rule::FilterRule;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_sse_kms_encrypted_objects_status::SseKmsEncryptedObjectsStatus;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replica_modifications_status::ReplicaModificationsStatus;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_owner_override::OwnerOverride;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replication_time_status::ReplicationTimeStatus;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replication_time_value::ReplicationTimeValue;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_metrics_status::MetricsStatus;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_filter_rule_name::FilterRuleName;

#[cfg(any(feature = "op_get_bucket_abac", feature = "op_put_bucket_abac"))]
mod _abac_status;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
mod _abort_incomplete_multipart_upload;

#[cfg(feature = "op_put_bucket_accelerate_configuration")]
mod _accelerate_configuration;

#[cfg(any(feature = "op_put_bucket_acl", feature = "op_put_object_acl"))]
mod _access_control_policy;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _access_control_translation;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
mod _analytics_and_operator;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
mod _analytics_configuration;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
mod _analytics_export_destination;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
mod _analytics_filter;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
mod _analytics_s3_bucket_destination;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
mod _analytics_s3_export_file_format;

#[cfg(any(
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_get_bucket_metadata_configuration",
    feature = "op_update_bucket_metadata_annotation_table_configuration"
))]
mod _annotation_configuration_state;

#[cfg(feature = "op_copy_object")]
mod _annotation_directive;

#[cfg(feature = "op_list_object_annotations")]
mod _annotation_entry;

#[cfg(feature = "op_create_bucket_metadata_configuration")]
mod _annotation_table_configuration;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
mod _annotation_table_configuration_result;

#[cfg(feature = "op_update_bucket_metadata_annotation_table_configuration")]
mod _annotation_table_configuration_updates;

#[cfg(feature = "op_head_object")]
mod _archive_status;

#[cfg(any(feature = "op_get_bucket_encryption", feature = "op_put_bucket_encryption"))]
mod _blocked_encryption_types;

#[cfg(any(feature = "op_list_buckets", feature = "op_list_directory_buckets"))]
mod _bucket;

#[cfg(any(feature = "op_get_bucket_abac", feature = "op_put_bucket_abac"))]
mod _bucket_abac_status;

#[cfg(any(
    feature = "op_get_bucket_accelerate_configuration",
    feature = "op_put_bucket_accelerate_configuration"
))]
mod _bucket_accelerate_status;

#[cfg(any(feature = "op_create_bucket", feature = "op_put_bucket_acl"))]
mod _bucket_canned_acl;

#[cfg(feature = "op_create_bucket")]
mod _bucket_info;

#[cfg(feature = "op_put_bucket_lifecycle_configuration")]
mod _bucket_lifecycle_configuration;

#[cfg(any(feature = "op_create_bucket", feature = "op_get_bucket_location"))]
mod _bucket_location_constraint;

#[cfg(feature = "op_put_bucket_logging")]
mod _bucket_logging_status;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
mod _bucket_logs_permission;

#[cfg(feature = "op_create_bucket")]
mod _bucket_namespace;

#[cfg(feature = "op_create_bucket")]
mod _bucket_type;

#[cfg(any(feature = "op_get_bucket_versioning", feature = "op_put_bucket_versioning"))]
mod _bucket_versioning_status;

#[cfg(feature = "op_get_object_attributes")]
mod _checksum;

#[cfg(any(
    feature = "op_copy_object",
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_create_bucket_metadata_table_configuration",
    feature = "op_create_multipart_upload",
    feature = "op_delete_objects",
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_annotations",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2",
    feature = "op_list_parts",
    feature = "op_put_bucket_abac",
    feature = "op_put_bucket_accelerate_configuration",
    feature = "op_put_bucket_acl",
    feature = "op_put_bucket_cors",
    feature = "op_put_bucket_encryption",
    feature = "op_put_bucket_lifecycle_configuration",
    feature = "op_put_bucket_logging",
    feature = "op_put_bucket_ownership_controls",
    feature = "op_put_bucket_policy",
    feature = "op_put_bucket_replication",
    feature = "op_put_bucket_request_payment",
    feature = "op_put_bucket_tagging",
    feature = "op_put_bucket_versioning",
    feature = "op_put_bucket_website",
    feature = "op_put_object",
    feature = "op_put_object_acl",
    feature = "op_put_object_annotation",
    feature = "op_put_object_legal_hold",
    feature = "op_put_object_lock_configuration",
    feature = "op_put_object_retention",
    feature = "op_put_object_tagging",
    feature = "op_put_public_access_block",
    feature = "op_restore_object",
    feature = "op_update_bucket_metadata_annotation_table_configuration",
    feature = "op_update_bucket_metadata_inventory_table_configuration",
    feature = "op_update_bucket_metadata_journal_table_configuration",
    feature = "op_update_object_encryption",
    feature = "op_upload_part"
))]
mod _checksum_algorithm;

#[cfg(any(
    feature = "op_get_object",
    feature = "op_get_object_annotation",
    feature = "op_head_object"
))]
mod _checksum_mode;

#[cfg(any(
    feature = "op_complete_multipart_upload",
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_get_object",
    feature = "op_get_object_annotation",
    feature = "op_get_object_attributes",
    feature = "op_head_object",
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2",
    feature = "op_list_parts",
    feature = "op_put_object",
    feature = "op_put_object_annotation"
))]
mod _checksum_type;

#[cfg(any(
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2"
))]
mod _common_prefix;

#[cfg(feature = "op_complete_multipart_upload")]
mod _completed_multipart_upload;

#[cfg(feature = "op_complete_multipart_upload")]
mod _completed_part;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
mod _compression_type;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
mod _condition;

#[cfg(feature = "op_select_object_content")]
mod _continuation_event;

#[cfg(feature = "op_copy_object")]
mod _copy_object_result;

#[cfg(feature = "op_upload_part_copy")]
mod _copy_part_result;

#[cfg(feature = "op_put_bucket_cors")]
mod _cors_configuration;

#[cfg(any(feature = "op_get_bucket_cors", feature = "op_put_bucket_cors"))]
mod _cors_rule;

#[cfg(feature = "op_create_bucket")]
mod _create_bucket_configuration;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
mod _csv_input;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
mod _csv_output;

#[cfg(feature = "op_create_bucket")]
mod _data_redundancy;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_put_object_lock_configuration"
))]
mod _default_retention;

#[cfg(feature = "op_delete_objects")]
mod _delete;

#[cfg(feature = "op_list_object_versions")]
mod _delete_marker_entry;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _delete_marker_replication;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _delete_marker_replication_status;

#[cfg(feature = "op_delete_objects")]
mod _deleted_object;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _destination;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
mod _destination_result;

#[cfg(any(
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2"
))]
mod _encoding_type;

#[cfg(feature = "op_restore_object")]
mod _encryption;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _encryption_configuration;

#[cfg(any(feature = "op_get_bucket_encryption", feature = "op_put_bucket_encryption"))]
mod _encryption_type;

#[cfg(feature = "op_select_object_content")]
mod _end_event;

#[cfg(feature = "op_delete_objects")]
mod _error;

#[cfg(any(
    feature = "op_get_bucket_metadata_configuration",
    feature = "op_get_bucket_metadata_table_configuration"
))]
mod _error_details;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
mod _error_document;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
mod _event;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
mod _event_bridge_configuration;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_get_object_retention",
    feature = "op_put_object_lock_configuration",
    feature = "op_put_object_retention"
))]
mod _event_hold_duration;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _existing_object_replication;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _existing_object_replication_status;

#[cfg(any(
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_get_bucket_metadata_configuration",
    feature = "op_update_bucket_metadata_journal_table_configuration"
))]
mod _expiration_state;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
mod _expiration_status;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
mod _expression_type;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
mod _file_header_info;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
mod _filter_rule;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
mod _filter_rule_name;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
mod _get_bucket_metadata_configuration_result;

#[cfg(feature = "op_get_bucket_metadata_table_configuration")]
mod _get_bucket_metadata_table_configuration_result;

#[cfg(feature = "op_get_object_attributes")]
mod _get_object_attributes_parts;

#[cfg(feature = "op_restore_object")]
mod _glacier_job_parameters;

#[cfg(any(
    feature = "op_get_bucket_acl",
    feature = "op_get_object_acl",
    feature = "op_put_bucket_acl",
    feature = "op_put_object_acl",
    feature = "op_restore_object"
))]
mod _grant;

#[cfg(any(
    feature = "op_get_bucket_acl",
    feature = "op_get_bucket_logging",
    feature = "op_get_object_acl",
    feature = "op_put_bucket_acl",
    feature = "op_put_bucket_logging",
    feature = "op_put_object_acl",
    feature = "op_restore_object"
))]
mod _grantee;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
mod _index_document;

#[cfg(any(feature = "op_list_multipart_uploads", feature = "op_list_parts"))]
mod _initiator;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
mod _input_serialization;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_get_object",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
mod _intelligent_tiering_access_tier;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
mod _intelligent_tiering_and_operator;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
mod _intelligent_tiering_configuration;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
mod _intelligent_tiering_filter;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
mod _intelligent_tiering_status;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
mod _inventory_configuration;

#[cfg(any(
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_get_bucket_metadata_configuration",
    feature = "op_update_bucket_metadata_inventory_table_configuration"
))]
mod _inventory_configuration_state;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
mod _inventory_destination;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
mod _inventory_encryption;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
mod _inventory_filter;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
mod _inventory_format;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
mod _inventory_frequency;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
mod _inventory_included_object_versions;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
mod _inventory_optional_field;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
mod _inventory_s3_bucket_destination;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
mod _inventory_schedule;

#[cfg(feature = "op_create_bucket_metadata_configuration")]
mod _inventory_table_configuration;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
mod _inventory_table_configuration_result;

#[cfg(feature = "op_update_bucket_metadata_inventory_table_configuration")]
mod _inventory_table_configuration_updates;

#[cfg(feature = "op_create_bucket_metadata_configuration")]
mod _journal_table_configuration;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
mod _journal_table_configuration_result;

#[cfg(feature = "op_update_bucket_metadata_journal_table_configuration")]
mod _journal_table_configuration_updates;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
mod _json_input;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
mod _json_output;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
mod _json_type;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
mod _lambda_function_configuration;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
mod _lifecycle_expiration;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
mod _lifecycle_rule;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
mod _lifecycle_rule_and_operator;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
mod _lifecycle_rule_filter;

#[cfg(feature = "op_create_bucket")]
mod _location_info;

#[cfg(any(feature = "op_create_bucket", feature = "op_head_bucket"))]
mod _location_type;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
mod _logging_enabled;

#[cfg(feature = "op_create_bucket_metadata_configuration")]
mod _metadata_configuration;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
mod _metadata_configuration_result;

#[cfg(feature = "op_copy_object")]
mod _metadata_directive;

#[cfg(feature = "op_restore_object")]
mod _metadata_entry;

#[cfg(feature = "op_create_bucket_metadata_table_configuration")]
mod _metadata_table_configuration;

#[cfg(feature = "op_get_bucket_metadata_table_configuration")]
mod _metadata_table_configuration_result;

#[cfg(any(
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_update_bucket_metadata_annotation_table_configuration",
    feature = "op_update_bucket_metadata_inventory_table_configuration"
))]
mod _metadata_table_encryption_configuration;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _metrics;

#[cfg(any(
    feature = "op_get_bucket_metrics_configuration",
    feature = "op_list_bucket_metrics_configurations",
    feature = "op_put_bucket_metrics_configuration"
))]
mod _metrics_and_operator;

#[cfg(any(
    feature = "op_get_bucket_metrics_configuration",
    feature = "op_list_bucket_metrics_configurations",
    feature = "op_put_bucket_metrics_configuration"
))]
mod _metrics_configuration;

#[cfg(any(
    feature = "op_get_bucket_metrics_configuration",
    feature = "op_list_bucket_metrics_configurations",
    feature = "op_put_bucket_metrics_configuration"
))]
mod _metrics_filter;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _metrics_status;

#[cfg(feature = "op_put_bucket_versioning")]
mod _mfa_delete;

#[cfg(feature = "op_get_bucket_versioning")]
mod _mfa_delete_status;

#[cfg(feature = "op_list_multipart_uploads")]
mod _multipart_upload;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
mod _noncurrent_version_expiration;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
mod _noncurrent_version_transition;

#[cfg(feature = "op_put_bucket_notification_configuration")]
mod _notification_configuration;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
mod _notification_configuration_filter;

#[cfg(any(feature = "op_list_objects", feature = "op_list_objects_v2"))]
mod _object;

#[cfg(feature = "op_get_object_attributes")]
mod _object_attributes;

#[cfg(any(
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_put_object",
    feature = "op_put_object_acl",
    feature = "op_restore_object"
))]
mod _object_canned_acl;

#[cfg(feature = "op_update_object_encryption")]
mod _object_encryption;

#[cfg(feature = "op_delete_objects")]
mod _object_identifier;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_put_object_lock_configuration"
))]
mod _object_lock_configuration;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_put_object_lock_configuration"
))]
mod _object_lock_enabled;

#[cfg(any(
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_get_object",
    feature = "op_get_object_retention",
    feature = "op_head_object",
    feature = "op_put_object",
    feature = "op_put_object_retention"
))]
mod _object_lock_event_hold;

#[cfg(any(feature = "op_get_object_legal_hold", feature = "op_put_object_legal_hold"))]
mod _object_lock_legal_hold;

#[cfg(any(
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_get_object",
    feature = "op_get_object_legal_hold",
    feature = "op_head_object",
    feature = "op_put_object",
    feature = "op_put_object_legal_hold",
    feature = "op_write_get_object_response"
))]
mod _object_lock_legal_hold_status;

#[cfg(any(
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_get_object",
    feature = "op_head_object",
    feature = "op_put_object",
    feature = "op_write_get_object_response"
))]
mod _object_lock_mode;

#[cfg(any(feature = "op_get_object_retention", feature = "op_put_object_retention"))]
mod _object_lock_retention;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_get_object_retention",
    feature = "op_put_object_lock_configuration",
    feature = "op_put_object_retention"
))]
mod _object_lock_retention_mode;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_put_object_lock_configuration"
))]
mod _object_lock_rule;

#[cfg(any(
    feature = "op_create_bucket",
    feature = "op_get_bucket_ownership_controls",
    feature = "op_put_bucket_ownership_controls"
))]
mod _object_ownership;

#[cfg(feature = "op_get_object_attributes")]
mod _object_part;

#[cfg(any(feature = "op_list_objects", feature = "op_list_objects_v2"))]
mod _object_storage_class;

#[cfg(feature = "op_list_object_versions")]
mod _object_version;

#[cfg(feature = "op_list_object_versions")]
mod _object_version_storage_class;

#[cfg(any(
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2"
))]
mod _optional_object_attributes;

#[cfg(feature = "op_restore_object")]
mod _output_location;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
mod _output_serialization;

#[cfg(any(
    feature = "op_get_bucket_acl",
    feature = "op_get_object_acl",
    feature = "op_list_buckets",
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2",
    feature = "op_list_parts",
    feature = "op_put_bucket_acl",
    feature = "op_put_object_acl"
))]
mod _owner;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _owner_override;

#[cfg(any(
    feature = "op_get_bucket_ownership_controls",
    feature = "op_put_bucket_ownership_controls"
))]
mod _ownership_controls;

#[cfg(any(
    feature = "op_get_bucket_ownership_controls",
    feature = "op_put_bucket_ownership_controls"
))]
mod _ownership_controls_rule;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
mod _parquet_input;

#[cfg(feature = "op_list_parts")]
mod _part;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
mod _partition_date_source;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
mod _partitioned_prefix;

#[cfg(any(feature = "op_get_bucket_request_payment", feature = "op_put_bucket_request_payment"))]
mod _payer;

#[cfg(any(
    feature = "op_get_bucket_acl",
    feature = "op_get_object_acl",
    feature = "op_put_bucket_acl",
    feature = "op_put_object_acl",
    feature = "op_restore_object"
))]
mod _permission;

#[cfg(feature = "op_get_bucket_policy_status")]
mod _policy_status;

#[cfg(feature = "op_select_object_content")]
mod _progress;

#[cfg(feature = "op_select_object_content")]
mod _progress_event;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
mod _protocol;

#[cfg(any(feature = "op_get_public_access_block", feature = "op_put_public_access_block"))]
mod _public_access_block_configuration;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
mod _queue_configuration;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
mod _quote_fields;

#[cfg(any(
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_get_bucket_metadata_configuration",
    feature = "op_update_bucket_metadata_journal_table_configuration"
))]
mod _record_expiration;

#[cfg(feature = "op_select_object_content")]
mod _records_event;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
mod _redirect;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
mod _redirect_all_requests_to;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _replica_modifications;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _replica_modifications_status;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _replication_configuration;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _replication_rule;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _replication_rule_and_operator;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _replication_rule_filter;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _replication_rule_status;

#[cfg(any(
    feature = "op_get_object",
    feature = "op_get_object_annotation",
    feature = "op_head_object",
    feature = "op_list_object_annotations",
    feature = "op_write_get_object_response"
))]
mod _replication_status;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _replication_time;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _replication_time_status;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _replication_time_value;

#[cfg(any(
    feature = "op_abort_multipart_upload",
    feature = "op_complete_multipart_upload",
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_delete_object",
    feature = "op_delete_object_annotation",
    feature = "op_delete_objects",
    feature = "op_get_bucket_accelerate_configuration",
    feature = "op_get_object",
    feature = "op_get_object_acl",
    feature = "op_get_object_annotation",
    feature = "op_get_object_attributes",
    feature = "op_get_object_torrent",
    feature = "op_head_object",
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_annotations",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2",
    feature = "op_list_parts",
    feature = "op_put_object",
    feature = "op_put_object_acl",
    feature = "op_put_object_annotation",
    feature = "op_put_object_legal_hold",
    feature = "op_put_object_lock_configuration",
    feature = "op_put_object_retention",
    feature = "op_restore_object",
    feature = "op_update_object_encryption",
    feature = "op_upload_part",
    feature = "op_upload_part_copy",
    feature = "op_write_get_object_response"
))]
mod _request_charged;

#[cfg(any(
    feature = "op_abort_multipart_upload",
    feature = "op_complete_multipart_upload",
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_delete_object",
    feature = "op_delete_object_annotation",
    feature = "op_delete_objects",
    feature = "op_get_bucket_accelerate_configuration",
    feature = "op_get_object",
    feature = "op_get_object_acl",
    feature = "op_get_object_annotation",
    feature = "op_get_object_attributes",
    feature = "op_get_object_legal_hold",
    feature = "op_get_object_retention",
    feature = "op_get_object_tagging",
    feature = "op_get_object_torrent",
    feature = "op_head_object",
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_annotations",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2",
    feature = "op_list_parts",
    feature = "op_put_object",
    feature = "op_put_object_acl",
    feature = "op_put_object_annotation",
    feature = "op_put_object_legal_hold",
    feature = "op_put_object_lock_configuration",
    feature = "op_put_object_retention",
    feature = "op_put_object_tagging",
    feature = "op_restore_object",
    feature = "op_update_object_encryption",
    feature = "op_upload_part",
    feature = "op_upload_part_copy"
))]
mod _request_payer;

#[cfg(feature = "op_put_bucket_request_payment")]
mod _request_payment_configuration;

#[cfg(feature = "op_select_object_content")]
mod _request_progress;

#[cfg(feature = "op_restore_object")]
mod _restore_request;

#[cfg(feature = "op_restore_object")]
mod _restore_request_type;

#[cfg(any(
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2"
))]
mod _restore_status;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
mod _routing_rule;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
mod _s3_key_filter;

#[cfg(feature = "op_restore_object")]
mod _s3_location;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
mod _s3_tables_bucket_type;

#[cfg(feature = "op_create_bucket_metadata_table_configuration")]
mod _s3_tables_destination;

#[cfg(feature = "op_get_bucket_metadata_table_configuration")]
mod _s3_tables_destination_result;

#[cfg(feature = "op_select_object_content")]
mod _scan_range;

#[cfg(feature = "op_select_object_content")]
mod _select_object_content_event_stream;

#[cfg(feature = "op_restore_object")]
mod _select_parameters;

#[cfg(any(
    feature = "op_complete_multipart_upload",
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_create_session",
    feature = "op_get_bucket_encryption",
    feature = "op_get_object",
    feature = "op_get_object_annotation",
    feature = "op_head_object",
    feature = "op_put_bucket_encryption",
    feature = "op_put_object",
    feature = "op_put_object_annotation",
    feature = "op_restore_object",
    feature = "op_upload_part",
    feature = "op_upload_part_copy",
    feature = "op_write_get_object_response"
))]
mod _server_side_encryption;

#[cfg(any(feature = "op_get_bucket_encryption", feature = "op_put_bucket_encryption"))]
mod _server_side_encryption_by_default;

#[cfg(any(feature = "op_get_bucket_encryption", feature = "op_put_bucket_encryption"))]
mod _server_side_encryption_configuration;

#[cfg(any(feature = "op_get_bucket_encryption", feature = "op_put_bucket_encryption"))]
mod _server_side_encryption_rule;

#[cfg(feature = "op_create_session")]
mod _session_credentials;

#[cfg(feature = "op_create_session")]
mod _session_mode;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
mod _simple_prefix;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _source_selection_criteria;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _sse_kms_encrypted_objects;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
mod _sse_kms_encrypted_objects_status;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
mod _ssekms;

#[cfg(feature = "op_update_object_encryption")]
mod _ssekms_encryption;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
mod _sses3;

#[cfg(feature = "op_select_object_content")]
mod _stats;

#[cfg(feature = "op_select_object_content")]
mod _stats_event;

#[cfg(any(
    feature = "op_copy_object",
    feature = "op_create_multipart_upload",
    feature = "op_get_bucket_replication",
    feature = "op_get_object",
    feature = "op_get_object_attributes",
    feature = "op_head_object",
    feature = "op_list_multipart_uploads",
    feature = "op_list_parts",
    feature = "op_put_bucket_replication",
    feature = "op_put_object",
    feature = "op_restore_object",
    feature = "op_write_get_object_response"
))]
mod _storage_class;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
mod _storage_class_analysis;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
mod _storage_class_analysis_data_export;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
mod _storage_class_analysis_schema_version;

#[cfg(any(
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_update_bucket_metadata_annotation_table_configuration",
    feature = "op_update_bucket_metadata_inventory_table_configuration"
))]
mod _table_sse_algorithm;

#[cfg(any(
    feature = "op_create_bucket",
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_get_bucket_metrics_configuration",
    feature = "op_get_bucket_replication",
    feature = "op_get_bucket_tagging",
    feature = "op_get_object_tagging",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_list_bucket_metrics_configurations",
    feature = "op_put_bucket_analytics_configuration",
    feature = "op_put_bucket_intelligent_tiering_configuration",
    feature = "op_put_bucket_lifecycle_configuration",
    feature = "op_put_bucket_metrics_configuration",
    feature = "op_put_bucket_replication",
    feature = "op_put_bucket_tagging",
    feature = "op_put_object_tagging",
    feature = "op_restore_object"
))]
mod _tag;

#[cfg(any(
    feature = "op_put_bucket_tagging",
    feature = "op_put_object_tagging",
    feature = "op_restore_object"
))]
mod _tagging;

#[cfg(feature = "op_copy_object")]
mod _tagging_directive;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
mod _target_grant;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
mod _target_object_key_format;

#[cfg(feature = "op_restore_object")]
mod _tier;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
mod _tiering;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
mod _topic_configuration;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
mod _transition;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
mod _transition_default_minimum_object_size;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
mod _transition_storage_class;

#[cfg(any(
    feature = "op_get_bucket_acl",
    feature = "op_get_bucket_logging",
    feature = "op_get_object_acl",
    feature = "op_put_bucket_acl",
    feature = "op_put_bucket_logging",
    feature = "op_put_object_acl",
    feature = "op_restore_object"
))]
mod _type_;

#[cfg(feature = "op_put_bucket_versioning")]
mod _versioning_configuration;

#[cfg(feature = "op_put_bucket_website")]
mod _website_configuration;

/// Builders
pub mod builders;

/// Error types that Amazon Simple Storage Service can respond with.
pub mod error;
