// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Specifies the service jobs to terminate and the reason for the termination.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct TerminateServiceJobsInput {
    /// <p>An array of up to 50 service job IDs of the service jobs to terminate.</p>
    pub jobs: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    /// <p>A message to attach to the service job that explains the reason for terminating it. This message is returned by <code>DescribeServiceJob</code> operations on the service job.</p>
    pub reason: ::std::option::Option<::std::string::String>,
}
impl TerminateServiceJobsInput {
    /// <p>An array of up to 50 service job IDs of the service jobs to terminate.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.jobs.is_none()`.
    pub fn jobs(&self) -> &[::std::string::String] {
        self.jobs.as_deref().unwrap_or_default()
    }
    /// <p>A message to attach to the service job that explains the reason for terminating it. This message is returned by <code>DescribeServiceJob</code> operations on the service job.</p>
    pub fn reason(&self) -> ::std::option::Option<&str> {
        self.reason.as_deref()
    }
}
impl TerminateServiceJobsInput {
    /// Creates a new builder-style object to manufacture [`TerminateServiceJobsInput`](crate::operation::terminate_service_jobs::TerminateServiceJobsInput).
    pub fn builder() -> crate::operation::terminate_service_jobs::builders::TerminateServiceJobsInputBuilder {
        crate::operation::terminate_service_jobs::builders::TerminateServiceJobsInputBuilder::default()
    }
}

/// A builder for [`TerminateServiceJobsInput`](crate::operation::terminate_service_jobs::TerminateServiceJobsInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct TerminateServiceJobsInputBuilder {
    pub(crate) jobs: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    pub(crate) reason: ::std::option::Option<::std::string::String>,
}
impl TerminateServiceJobsInputBuilder {
    /// Appends an item to `jobs`.
    ///
    /// To override the contents of this collection use [`set_jobs`](Self::set_jobs).
    ///
    /// <p>An array of up to 50 service job IDs of the service jobs to terminate.</p>
    pub fn jobs(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        let mut v = self.jobs.unwrap_or_default();
        v.push(input.into());
        self.jobs = ::std::option::Option::Some(v);
        self
    }
    /// <p>An array of up to 50 service job IDs of the service jobs to terminate.</p>
    pub fn set_jobs(mut self, input: ::std::option::Option<::std::vec::Vec<::std::string::String>>) -> Self {
        self.jobs = input;
        self
    }
    /// <p>An array of up to 50 service job IDs of the service jobs to terminate.</p>
    pub fn get_jobs(&self) -> &::std::option::Option<::std::vec::Vec<::std::string::String>> {
        &self.jobs
    }
    /// <p>A message to attach to the service job that explains the reason for terminating it. This message is returned by <code>DescribeServiceJob</code> operations on the service job.</p>
    /// This field is required.
    pub fn reason(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.reason = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>A message to attach to the service job that explains the reason for terminating it. This message is returned by <code>DescribeServiceJob</code> operations on the service job.</p>
    pub fn set_reason(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.reason = input;
        self
    }
    /// <p>A message to attach to the service job that explains the reason for terminating it. This message is returned by <code>DescribeServiceJob</code> operations on the service job.</p>
    pub fn get_reason(&self) -> &::std::option::Option<::std::string::String> {
        &self.reason
    }
    /// Consumes the builder and constructs a [`TerminateServiceJobsInput`](crate::operation::terminate_service_jobs::TerminateServiceJobsInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::terminate_service_jobs::TerminateServiceJobsInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::terminate_service_jobs::TerminateServiceJobsInput {
            jobs: self.jobs,
            reason: self.reason,
        })
    }
}
