// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_complete_multipart_upload")]
pub use crate::types::_completed_multipart_upload::CompletedMultipartUploadBuilder;

#[cfg(feature = "op_copy_object")]
pub use crate::types::_copy_object_result::CopyObjectResultBuilder;

#[cfg(feature = "op_create_bucket")]
pub use crate::types::_create_bucket_configuration::CreateBucketConfigurationBuilder;

#[cfg(feature = "op_create_bucket_metadata_configuration")]
pub use crate::types::_metadata_configuration::MetadataConfigurationBuilder;

#[cfg(feature = "op_create_bucket_metadata_table_configuration")]
pub use crate::types::_metadata_table_configuration::MetadataTableConfigurationBuilder;

#[cfg(feature = "op_create_session")]
pub use crate::types::_session_credentials::SessionCredentialsBuilder;

#[cfg(feature = "op_delete_objects")]
pub use crate::types::_delete::DeleteBuilder;

#[cfg(any(feature = "op_get_bucket_abac", feature = "op_put_bucket_abac"))]
pub use crate::types::_abac_status::AbacStatusBuilder;

#[cfg(any(
    feature = "op_get_bucket_acl",
    feature = "op_get_object_acl",
    feature = "op_list_buckets",
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2",
    feature = "op_list_parts",
    feature = "op_put_bucket_acl",
    feature = "op_put_object_acl"
))]
pub use crate::types::_owner::OwnerBuilder;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_analytics_configuration::AnalyticsConfigurationBuilder;

#[cfg(any(feature = "op_get_bucket_encryption", feature = "op_put_bucket_encryption"))]
pub use crate::types::_server_side_encryption_configuration::ServerSideEncryptionConfigurationBuilder;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
pub use crate::types::_intelligent_tiering_configuration::IntelligentTieringConfigurationBuilder;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_configuration::InventoryConfigurationBuilder;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
pub use crate::types::_logging_enabled::LoggingEnabledBuilder;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
pub use crate::types::_get_bucket_metadata_configuration_result::GetBucketMetadataConfigurationResultBuilder;

#[cfg(feature = "op_get_bucket_metadata_table_configuration")]
pub use crate::types::_get_bucket_metadata_table_configuration_result::GetBucketMetadataTableConfigurationResultBuilder;

#[cfg(any(
    feature = "op_get_bucket_metrics_configuration",
    feature = "op_list_bucket_metrics_configurations",
    feature = "op_put_bucket_metrics_configuration"
))]
pub use crate::types::_metrics_configuration::MetricsConfigurationBuilder;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_event_bridge_configuration::EventBridgeConfigurationBuilder;

#[cfg(any(
    feature = "op_get_bucket_ownership_controls",
    feature = "op_put_bucket_ownership_controls"
))]
pub use crate::types::_ownership_controls::OwnershipControlsBuilder;

#[cfg(feature = "op_get_bucket_policy_status")]
pub use crate::types::_policy_status::PolicyStatusBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replication_configuration::ReplicationConfigurationBuilder;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
pub use crate::types::_redirect_all_requests_to::RedirectAllRequestsToBuilder;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
pub use crate::types::_index_document::IndexDocumentBuilder;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
pub use crate::types::_error_document::ErrorDocumentBuilder;

#[cfg(feature = "op_get_object_attributes")]
pub use crate::types::_checksum::ChecksumBuilder;

#[cfg(feature = "op_get_object_attributes")]
pub use crate::types::_get_object_attributes_parts::GetObjectAttributesPartsBuilder;

#[cfg(any(feature = "op_get_object_legal_hold", feature = "op_put_object_legal_hold"))]
pub use crate::types::_object_lock_legal_hold::ObjectLockLegalHoldBuilder;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_put_object_lock_configuration"
))]
pub use crate::types::_object_lock_configuration::ObjectLockConfigurationBuilder;

#[cfg(any(feature = "op_get_object_retention", feature = "op_put_object_retention"))]
pub use crate::types::_object_lock_retention::ObjectLockRetentionBuilder;

#[cfg(any(feature = "op_get_public_access_block", feature = "op_put_public_access_block"))]
pub use crate::types::_public_access_block_configuration::PublicAccessBlockConfigurationBuilder;

#[cfg(any(feature = "op_list_multipart_uploads", feature = "op_list_parts"))]
pub use crate::types::_initiator::InitiatorBuilder;

#[cfg(feature = "op_put_bucket_accelerate_configuration")]
pub use crate::types::_accelerate_configuration::AccelerateConfigurationBuilder;

#[cfg(any(feature = "op_put_bucket_acl", feature = "op_put_object_acl"))]
pub use crate::types::_access_control_policy::AccessControlPolicyBuilder;

#[cfg(feature = "op_put_bucket_cors")]
pub use crate::types::_cors_configuration::CorsConfigurationBuilder;

#[cfg(feature = "op_put_bucket_lifecycle_configuration")]
pub use crate::types::_bucket_lifecycle_configuration::BucketLifecycleConfigurationBuilder;

#[cfg(feature = "op_put_bucket_logging")]
pub use crate::types::_bucket_logging_status::BucketLoggingStatusBuilder;

#[cfg(feature = "op_put_bucket_notification_configuration")]
pub use crate::types::_notification_configuration::NotificationConfigurationBuilder;

#[cfg(feature = "op_put_bucket_request_payment")]
pub use crate::types::_request_payment_configuration::RequestPaymentConfigurationBuilder;

#[cfg(any(
    feature = "op_put_bucket_tagging",
    feature = "op_put_object_tagging",
    feature = "op_restore_object"
))]
pub use crate::types::_tagging::TaggingBuilder;

#[cfg(feature = "op_put_bucket_versioning")]
pub use crate::types::_versioning_configuration::VersioningConfigurationBuilder;

#[cfg(feature = "op_put_bucket_website")]
pub use crate::types::_website_configuration::WebsiteConfigurationBuilder;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_restore_request::RestoreRequestBuilder;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_request_progress::RequestProgressBuilder;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_input_serialization::InputSerializationBuilder;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_output_serialization::OutputSerializationBuilder;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_scan_range::ScanRangeBuilder;

#[cfg(feature = "op_update_bucket_metadata_annotation_table_configuration")]
pub use crate::types::_annotation_table_configuration_updates::AnnotationTableConfigurationUpdatesBuilder;

#[cfg(feature = "op_update_bucket_metadata_inventory_table_configuration")]
pub use crate::types::_inventory_table_configuration_updates::InventoryTableConfigurationUpdatesBuilder;

#[cfg(feature = "op_update_bucket_metadata_journal_table_configuration")]
pub use crate::types::_journal_table_configuration_updates::JournalTableConfigurationUpdatesBuilder;

#[cfg(feature = "op_upload_part_copy")]
pub use crate::types::_copy_part_result::CopyPartResultBuilder;

#[cfg(feature = "op_create_bucket")]
pub use crate::types::_location_info::LocationInfoBuilder;

#[cfg(feature = "op_create_bucket")]
pub use crate::types::_bucket_info::BucketInfoBuilder;

#[cfg(feature = "op_create_bucket_metadata_configuration")]
pub use crate::types::_journal_table_configuration::JournalTableConfigurationBuilder;

#[cfg(feature = "op_create_bucket_metadata_configuration")]
pub use crate::types::_inventory_table_configuration::InventoryTableConfigurationBuilder;

#[cfg(feature = "op_create_bucket_metadata_configuration")]
pub use crate::types::_annotation_table_configuration::AnnotationTableConfigurationBuilder;

#[cfg(feature = "op_create_bucket_metadata_table_configuration")]
pub use crate::types::_s3_tables_destination::S3TablesDestinationBuilder;

#[cfg(feature = "op_delete_objects")]
pub use crate::types::_deleted_object::DeletedObjectBuilder;

#[cfg(feature = "op_delete_objects")]
pub use crate::types::_error::ErrorBuilder;

#[cfg(any(
    feature = "op_get_bucket_acl",
    feature = "op_get_object_acl",
    feature = "op_put_bucket_acl",
    feature = "op_put_object_acl",
    feature = "op_restore_object"
))]
pub use crate::types::_grant::GrantBuilder;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_storage_class_analysis::StorageClassAnalysisBuilder;

#[cfg(any(feature = "op_get_bucket_cors", feature = "op_put_bucket_cors"))]
pub use crate::types::_cors_rule::CorsRuleBuilder;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
pub use crate::types::_intelligent_tiering_filter::IntelligentTieringFilterBuilder;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_destination::InventoryDestinationBuilder;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_filter::InventoryFilterBuilder;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_schedule::InventoryScheduleBuilder;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_lifecycle_rule::LifecycleRuleBuilder;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
pub use crate::types::_target_object_key_format::TargetObjectKeyFormatBuilder;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
pub use crate::types::_metadata_configuration_result::MetadataConfigurationResultBuilder;

#[cfg(feature = "op_get_bucket_metadata_table_configuration")]
pub use crate::types::_metadata_table_configuration_result::MetadataTableConfigurationResultBuilder;

#[cfg(any(
    feature = "op_get_bucket_metadata_configuration",
    feature = "op_get_bucket_metadata_table_configuration"
))]
pub use crate::types::_error_details::ErrorDetailsBuilder;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_topic_configuration::TopicConfigurationBuilder;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_queue_configuration::QueueConfigurationBuilder;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_lambda_function_configuration::LambdaFunctionConfigurationBuilder;

#[cfg(any(
    feature = "op_create_bucket",
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_get_bucket_metrics_configuration",
    feature = "op_get_bucket_replication",
    feature = "op_get_bucket_tagging",
    feature = "op_get_object_tagging",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_list_bucket_metrics_configurations",
    feature = "op_put_bucket_analytics_configuration",
    feature = "op_put_bucket_intelligent_tiering_configuration",
    feature = "op_put_bucket_lifecycle_configuration",
    feature = "op_put_bucket_metrics_configuration",
    feature = "op_put_bucket_replication",
    feature = "op_put_bucket_tagging",
    feature = "op_put_object_tagging",
    feature = "op_restore_object"
))]
pub use crate::types::_tag::TagBuilder;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
pub use crate::types::_routing_rule::RoutingRuleBuilder;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_put_object_lock_configuration"
))]
pub use crate::types::_object_lock_rule::ObjectLockRuleBuilder;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_get_object_retention",
    feature = "op_put_object_lock_configuration",
    feature = "op_put_object_retention"
))]
pub use crate::types::_event_hold_duration::EventHoldDurationBuilder;

#[cfg(any(feature = "op_list_buckets", feature = "op_list_directory_buckets"))]
pub use crate::types::_bucket::BucketBuilder;

#[cfg(feature = "op_list_multipart_uploads")]
pub use crate::types::_multipart_upload::MultipartUploadBuilder;

#[cfg(any(
    feature = "op_list_multipart_uploads",
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2"
))]
pub use crate::types::_common_prefix::CommonPrefixBuilder;

#[cfg(feature = "op_list_object_annotations")]
pub use crate::types::_annotation_entry::AnnotationEntryBuilder;

#[cfg(any(feature = "op_list_objects", feature = "op_list_objects_v2"))]
pub use crate::types::_object::ObjectBuilder;

#[cfg(feature = "op_list_object_versions")]
pub use crate::types::_object_version::ObjectVersionBuilder;

#[cfg(feature = "op_list_object_versions")]
pub use crate::types::_delete_marker_entry::DeleteMarkerEntryBuilder;

#[cfg(feature = "op_list_parts")]
pub use crate::types::_part::PartBuilder;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_glacier_job_parameters::GlacierJobParametersBuilder;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_select_parameters::SelectParametersBuilder;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_output_location::OutputLocationBuilder;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_csv_input::CsvInputBuilder;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_json_input::JsonInputBuilder;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_parquet_input::ParquetInputBuilder;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_csv_output::CsvOutputBuilder;

#[cfg(any(feature = "op_restore_object", feature = "op_select_object_content"))]
pub use crate::types::_json_output::JsonOutputBuilder;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_records_event::RecordsEventBuilder;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_stats_event::StatsEventBuilder;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_progress_event::ProgressEventBuilder;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_continuation_event::ContinuationEventBuilder;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_end_event::EndEventBuilder;

#[cfg(any(
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_update_bucket_metadata_annotation_table_configuration",
    feature = "op_update_bucket_metadata_inventory_table_configuration"
))]
pub use crate::types::_metadata_table_encryption_configuration::MetadataTableEncryptionConfigurationBuilder;

#[cfg(any(
    feature = "op_create_bucket_metadata_configuration",
    feature = "op_get_bucket_metadata_configuration",
    feature = "op_update_bucket_metadata_journal_table_configuration"
))]
pub use crate::types::_record_expiration::RecordExpirationBuilder;

#[cfg(feature = "op_update_object_encryption")]
pub use crate::types::_ssekms_encryption::SsekmsEncryptionBuilder;

#[cfg(feature = "op_complete_multipart_upload")]
pub use crate::types::_completed_part::CompletedPartBuilder;

#[cfg(feature = "op_delete_objects")]
pub use crate::types::_object_identifier::ObjectIdentifierBuilder;

#[cfg(any(
    feature = "op_get_bucket_acl",
    feature = "op_get_bucket_logging",
    feature = "op_get_object_acl",
    feature = "op_put_bucket_acl",
    feature = "op_put_bucket_logging",
    feature = "op_put_object_acl",
    feature = "op_restore_object"
))]
pub use crate::types::_grantee::GranteeBuilder;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_analytics_and_operator::AnalyticsAndOperatorBuilder;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_storage_class_analysis_data_export::StorageClassAnalysisDataExportBuilder;

#[cfg(any(feature = "op_get_bucket_encryption", feature = "op_put_bucket_encryption"))]
pub use crate::types::_server_side_encryption_rule::ServerSideEncryptionRuleBuilder;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
pub use crate::types::_intelligent_tiering_and_operator::IntelligentTieringAndOperatorBuilder;

#[cfg(any(
    feature = "op_get_bucket_intelligent_tiering_configuration",
    feature = "op_list_bucket_intelligent_tiering_configurations",
    feature = "op_put_bucket_intelligent_tiering_configuration"
))]
pub use crate::types::_tiering::TieringBuilder;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_s3_bucket_destination::InventoryS3BucketDestinationBuilder;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_lifecycle_expiration::LifecycleExpirationBuilder;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_lifecycle_rule_filter::LifecycleRuleFilterBuilder;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_noncurrent_version_expiration::NoncurrentVersionExpirationBuilder;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_abort_incomplete_multipart_upload::AbortIncompleteMultipartUploadBuilder;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
pub use crate::types::_target_grant::TargetGrantBuilder;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
pub use crate::types::_simple_prefix::SimplePrefixBuilder;

#[cfg(any(feature = "op_get_bucket_logging", feature = "op_put_bucket_logging"))]
pub use crate::types::_partitioned_prefix::PartitionedPrefixBuilder;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
pub use crate::types::_destination_result::DestinationResultBuilder;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
pub use crate::types::_journal_table_configuration_result::JournalTableConfigurationResultBuilder;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
pub use crate::types::_inventory_table_configuration_result::InventoryTableConfigurationResultBuilder;

#[cfg(feature = "op_get_bucket_metadata_configuration")]
pub use crate::types::_annotation_table_configuration_result::AnnotationTableConfigurationResultBuilder;

#[cfg(feature = "op_get_bucket_metadata_table_configuration")]
pub use crate::types::_s3_tables_destination_result::S3TablesDestinationResultBuilder;

#[cfg(any(
    feature = "op_get_bucket_metrics_configuration",
    feature = "op_list_bucket_metrics_configurations",
    feature = "op_put_bucket_metrics_configuration"
))]
pub use crate::types::_metrics_and_operator::MetricsAndOperatorBuilder;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_notification_configuration_filter::NotificationConfigurationFilterBuilder;

#[cfg(any(
    feature = "op_get_bucket_ownership_controls",
    feature = "op_put_bucket_ownership_controls"
))]
pub use crate::types::_ownership_controls_rule::OwnershipControlsRuleBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replication_rule::ReplicationRuleBuilder;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
pub use crate::types::_condition::ConditionBuilder;

#[cfg(any(feature = "op_get_bucket_website", feature = "op_put_bucket_website"))]
pub use crate::types::_redirect::RedirectBuilder;

#[cfg(feature = "op_get_object_attributes")]
pub use crate::types::_object_part::ObjectPartBuilder;

#[cfg(any(
    feature = "op_get_object_lock_configuration",
    feature = "op_put_object_lock_configuration"
))]
pub use crate::types::_default_retention::DefaultRetentionBuilder;

#[cfg(any(
    feature = "op_list_object_versions",
    feature = "op_list_objects",
    feature = "op_list_objects_v2"
))]
pub use crate::types::_restore_status::RestoreStatusBuilder;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_s3_location::S3LocationBuilder;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_stats::StatsBuilder;

#[cfg(feature = "op_select_object_content")]
pub use crate::types::_progress::ProgressBuilder;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_analytics_export_destination::AnalyticsExportDestinationBuilder;

#[cfg(any(feature = "op_get_bucket_encryption", feature = "op_put_bucket_encryption"))]
pub use crate::types::_server_side_encryption_by_default::ServerSideEncryptionByDefaultBuilder;

#[cfg(any(feature = "op_get_bucket_encryption", feature = "op_put_bucket_encryption"))]
pub use crate::types::_blocked_encryption_types::BlockedEncryptionTypesBuilder;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_inventory_encryption::InventoryEncryptionBuilder;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_lifecycle_rule_and_operator::LifecycleRuleAndOperatorBuilder;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_transition::TransitionBuilder;

#[cfg(any(
    feature = "op_get_bucket_lifecycle_configuration",
    feature = "op_put_bucket_lifecycle_configuration"
))]
pub use crate::types::_noncurrent_version_transition::NoncurrentVersionTransitionBuilder;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_s3_key_filter::S3KeyFilterBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replication_rule_filter::ReplicationRuleFilterBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_source_selection_criteria::SourceSelectionCriteriaBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_existing_object_replication::ExistingObjectReplicationBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_destination::DestinationBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_delete_marker_replication::DeleteMarkerReplicationBuilder;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_encryption::EncryptionBuilder;

#[cfg(any(
    feature = "op_get_bucket_analytics_configuration",
    feature = "op_list_bucket_analytics_configurations",
    feature = "op_put_bucket_analytics_configuration"
))]
pub use crate::types::_analytics_s3_bucket_destination::AnalyticsS3BucketDestinationBuilder;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_sses3::Sses3Builder;

#[cfg(any(
    feature = "op_get_bucket_inventory_configuration",
    feature = "op_list_bucket_inventory_configurations",
    feature = "op_put_bucket_inventory_configuration"
))]
pub use crate::types::_ssekms::SsekmsBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replication_rule_and_operator::ReplicationRuleAndOperatorBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_sse_kms_encrypted_objects::SseKmsEncryptedObjectsBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replica_modifications::ReplicaModificationsBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_access_control_translation::AccessControlTranslationBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_encryption_configuration::EncryptionConfigurationBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replication_time::ReplicationTimeBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_metrics::MetricsBuilder;

#[cfg(feature = "op_restore_object")]
pub use crate::types::_metadata_entry::MetadataEntryBuilder;

#[cfg(any(
    feature = "op_get_bucket_notification_configuration",
    feature = "op_put_bucket_notification_configuration"
))]
pub use crate::types::_filter_rule::FilterRuleBuilder;

#[cfg(any(feature = "op_get_bucket_replication", feature = "op_put_bucket_replication"))]
pub use crate::types::_replication_time_value::ReplicationTimeValueBuilder;
