// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(any(
    feature = "op_add_user_pool_client_secret",
    feature = "op_list_user_pool_client_secrets"
))]
pub use crate::types::_client_secret_descriptor_type::ClientSecretDescriptorType;

#[cfg(feature = "op_admin_create_user")]
pub use crate::types::_message_action_type::MessageActionType;

#[cfg(any(
    feature = "op_admin_create_user",
    feature = "op_list_users",
    feature = "op_list_users_in_group"
))]
pub use crate::types::_user_type::UserType;

#[cfg(any(
    feature = "op_admin_disable_provider_for_user",
    feature = "op_admin_link_provider_for_user"
))]
pub use crate::types::_provider_user_identifier_type::ProviderUserIdentifierType;

#[cfg(any(
    feature = "op_admin_get_device",
    feature = "op_admin_list_devices",
    feature = "op_get_device",
    feature = "op_list_devices"
))]
pub use crate::types::_device_type::DeviceType;

#[cfg(any(
    feature = "op_admin_create_user",
    feature = "op_admin_get_user",
    feature = "op_list_users",
    feature = "op_list_users_in_group"
))]
pub use crate::types::_user_status_type::UserStatusType;

#[cfg(any(feature = "op_admin_initiate_auth", feature = "op_initiate_auth"))]
pub use crate::types::_auth_flow_type::AuthFlowType;

#[cfg(any(
    feature = "op_admin_initiate_auth",
    feature = "op_admin_respond_to_auth_challenge",
    feature = "op_confirm_forgot_password",
    feature = "op_confirm_sign_up",
    feature = "op_forgot_password",
    feature = "op_initiate_auth",
    feature = "op_resend_confirmation_code",
    feature = "op_respond_to_auth_challenge",
    feature = "op_sign_up"
))]
pub use crate::types::_analytics_metadata_type::AnalyticsMetadataType;

#[cfg(any(feature = "op_admin_initiate_auth", feature = "op_admin_respond_to_auth_challenge"))]
pub use crate::types::_context_data_type::ContextDataType;

#[cfg(any(
    feature = "op_admin_initiate_auth",
    feature = "op_admin_respond_to_auth_challenge",
    feature = "op_initiate_auth",
    feature = "op_respond_to_auth_challenge"
))]
pub use crate::types::_challenge_name_type::ChallengeNameType;

#[cfg(any(
    feature = "op_admin_initiate_auth",
    feature = "op_admin_respond_to_auth_challenge",
    feature = "op_get_tokens_from_refresh_token",
    feature = "op_initiate_auth",
    feature = "op_respond_to_auth_challenge"
))]
pub use crate::types::_authentication_result_type::AuthenticationResultType;

#[cfg(any(feature = "op_admin_set_user_mfa_preference", feature = "op_set_user_mfa_preference"))]
pub use crate::types::_sms_mfa_settings_type::SmsMfaSettingsType;

#[cfg(any(feature = "op_admin_set_user_mfa_preference", feature = "op_set_user_mfa_preference"))]
pub use crate::types::_software_token_mfa_settings_type::SoftwareTokenMfaSettingsType;

#[cfg(any(feature = "op_admin_set_user_mfa_preference", feature = "op_set_user_mfa_preference"))]
pub use crate::types::_email_mfa_settings_type::EmailMfaSettingsType;

#[cfg(any(feature = "op_admin_set_user_mfa_preference", feature = "op_set_user_mfa_preference"))]
pub use crate::types::_web_authn_mfa_settings_type::WebAuthnMfaSettingsType;

#[cfg(any(
    feature = "op_admin_list_user_auth_events",
    feature = "op_admin_update_auth_event_feedback",
    feature = "op_update_auth_event_feedback"
))]
pub use crate::types::_feedback_value_type::FeedbackValueType;

#[cfg(any(feature = "op_admin_update_device_status", feature = "op_update_device_status"))]
pub use crate::types::_device_remembered_status_type::DeviceRememberedStatusType;

#[cfg(feature = "op_confirm_device")]
pub use crate::types::_device_secret_verifier_config_type::DeviceSecretVerifierConfigType;

#[cfg(any(
    feature = "op_confirm_forgot_password",
    feature = "op_confirm_sign_up",
    feature = "op_forgot_password",
    feature = "op_initiate_auth",
    feature = "op_resend_confirmation_code",
    feature = "op_respond_to_auth_challenge",
    feature = "op_sign_up"
))]
pub use crate::types::_user_context_data_type::UserContextDataType;

#[cfg(any(
    feature = "op_admin_list_groups_for_user",
    feature = "op_create_group",
    feature = "op_get_group",
    feature = "op_list_groups",
    feature = "op_update_group"
))]
pub use crate::types::_group_type::GroupType;

#[cfg(any(
    feature = "op_create_identity_provider",
    feature = "op_describe_identity_provider",
    feature = "op_get_identity_provider_by_identifier",
    feature = "op_list_identity_providers",
    feature = "op_update_identity_provider"
))]
pub use crate::types::_identity_provider_type_type::IdentityProviderTypeType;

#[cfg(any(
    feature = "op_create_identity_provider",
    feature = "op_describe_identity_provider",
    feature = "op_get_identity_provider_by_identifier",
    feature = "op_update_identity_provider"
))]
pub use crate::types::_identity_provider_type::IdentityProviderType;

#[cfg(any(
    feature = "op_create_managed_login_branding",
    feature = "op_describe_managed_login_branding",
    feature = "op_describe_managed_login_branding_by_client",
    feature = "op_update_managed_login_branding"
))]
pub use crate::types::_managed_login_branding_type::ManagedLoginBrandingType;

#[cfg(any(
    feature = "op_create_resource_server",
    feature = "op_describe_resource_server",
    feature = "op_list_resource_servers",
    feature = "op_update_resource_server"
))]
pub use crate::types::_resource_server_type::ResourceServerType;

#[cfg(any(
    feature = "op_create_terms",
    feature = "op_describe_terms",
    feature = "op_describe_terms_by_client",
    feature = "op_update_terms"
))]
pub use crate::types::_terms_source_type::TermsSourceType;

#[cfg(any(
    feature = "op_create_terms",
    feature = "op_describe_terms",
    feature = "op_describe_terms_by_client",
    feature = "op_list_terms",
    feature = "op_update_terms"
))]
pub use crate::types::_terms_enforcement_type::TermsEnforcementType;

#[cfg(any(
    feature = "op_create_terms",
    feature = "op_describe_terms",
    feature = "op_describe_terms_by_client",
    feature = "op_update_terms"
))]
pub use crate::types::_terms_type::TermsType;

#[cfg(any(
    feature = "op_create_user_import_job",
    feature = "op_describe_user_import_job",
    feature = "op_list_user_import_jobs",
    feature = "op_start_user_import_job",
    feature = "op_stop_user_import_job"
))]
pub use crate::types::_password_hashing_algorithm_type::PasswordHashingAlgorithmType;

#[cfg(any(
    feature = "op_create_user_import_job",
    feature = "op_describe_user_import_job",
    feature = "op_list_user_import_jobs",
    feature = "op_start_user_import_job",
    feature = "op_stop_user_import_job"
))]
pub use crate::types::_user_import_job_type::UserImportJobType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_user_pool_policy_type::UserPoolPolicyType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_deletion_protection_type::DeletionProtectionType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
pub use crate::types::_lambda_config_type::LambdaConfigType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_verification_message_template_type::VerificationMessageTemplateType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_get_user_pool_mfa_config",
    feature = "op_set_user_pool_mfa_config",
    feature = "op_update_user_pool"
))]
pub use crate::types::_user_pool_mfa_type::UserPoolMfaType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_user_attribute_update_settings_type::UserAttributeUpdateSettingsType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_device_configuration_type::DeviceConfigurationType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_email_configuration_type::EmailConfigurationType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_get_user_pool_mfa_config",
    feature = "op_set_user_pool_mfa_config",
    feature = "op_update_user_pool"
))]
pub use crate::types::_sms_configuration_type::SmsConfigurationType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_admin_create_user_config_type::AdminCreateUserConfigType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_user_pool_add_ons_type::UserPoolAddOnsType;

#[cfg(any(feature = "op_create_user_pool", feature = "op_describe_user_pool"))]
pub use crate::types::_username_configuration_type::UsernameConfigurationType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_account_recovery_setting_type::AccountRecoverySettingType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_user_pool_tier_type::UserPoolTierType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_key_configuration_type::KeyConfigurationType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_issuer_configuration_type::IssuerConfigurationType;

#[cfg(any(feature = "op_create_user_pool", feature = "op_describe_user_pool"))]
pub use crate::types::_user_pool_type::UserPoolType;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
pub use crate::types::_token_validity_units_type::TokenValidityUnitsType;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
pub use crate::types::_analytics_configuration_type::AnalyticsConfigurationType;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
pub use crate::types::_prevent_user_existence_error_types::PreventUserExistenceErrorTypes;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
pub use crate::types::_refresh_token_rotation_type::RefreshTokenRotationType;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
pub use crate::types::_user_pool_client_type::UserPoolClientType;

#[cfg(any(
    feature = "op_create_user_pool_domain",
    feature = "op_describe_user_pool_domain",
    feature = "op_update_user_pool_domain"
))]
pub use crate::types::_custom_domain_config_type::CustomDomainConfigType;

#[cfg(any(
    feature = "op_create_user_pool_domain",
    feature = "op_describe_user_pool_domain",
    feature = "op_update_user_pool_domain"
))]
pub use crate::types::_routing_type::RoutingType;

#[cfg(any(
    feature = "op_create_user_pool_replica",
    feature = "op_delete_user_pool_replica",
    feature = "op_list_user_pool_replicas",
    feature = "op_update_user_pool_replica"
))]
pub use crate::types::_user_pool_replica_type::UserPoolReplicaType;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_risk_configuration_type::RiskConfigurationType;

#[cfg(feature = "op_describe_user_pool_domain")]
pub use crate::types::_domain_description_type::DomainDescriptionType;

#[cfg(any(
    feature = "op_forgot_password",
    feature = "op_get_user_attribute_verification_code",
    feature = "op_resend_confirmation_code",
    feature = "op_sign_up",
    feature = "op_update_user_attributes"
))]
pub use crate::types::_code_delivery_details_type::CodeDeliveryDetailsType;

#[cfg(feature = "op_get_client_token")]
pub use crate::types::_client_authentication_result_type::ClientAuthenticationResultType;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
pub use crate::types::_log_delivery_configuration_type::LogDeliveryConfigurationType;

#[cfg(any(feature = "op_get_provisioned_limit", feature = "op_update_provisioned_limit"))]
pub use crate::types::_limit_definition_type::LimitDefinitionType;

#[cfg(any(feature = "op_get_provisioned_limit", feature = "op_update_provisioned_limit"))]
pub use crate::types::_limit_type::LimitType;

#[cfg(any(feature = "op_get_ui_customization", feature = "op_set_ui_customization"))]
pub use crate::types::_ui_customization_type::UiCustomizationType;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
pub use crate::types::_sms_mfa_config_type::SmsMfaConfigType;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
pub use crate::types::_software_token_mfa_config_type::SoftwareTokenMfaConfigType;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
pub use crate::types::_email_mfa_config_type::EmailMfaConfigType;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
pub use crate::types::_web_authn_configuration_type::WebAuthnConfigurationType;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_compromised_credentials_risk_configuration_type::CompromisedCredentialsRiskConfigurationType;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_account_takeover_risk_configuration_type::AccountTakeoverRiskConfigurationType;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_risk_exception_configuration_type::RiskExceptionConfigurationType;

#[cfg(feature = "op_update_user_pool_replica")]
pub use crate::types::_update_replica_status_type::UpdateReplicaStatusType;

#[cfg(feature = "op_verify_software_token")]
pub use crate::types::_verify_software_token_response_type::VerifySoftwareTokenResponseType;

#[cfg(any(
    feature = "op_add_custom_attributes",
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool"
))]
pub use crate::types::_schema_attribute_type::SchemaAttributeType;

#[cfg(any(
    feature = "op_admin_create_user",
    feature = "op_admin_get_device",
    feature = "op_admin_get_user",
    feature = "op_admin_list_devices",
    feature = "op_admin_update_user_attributes",
    feature = "op_get_device",
    feature = "op_get_user",
    feature = "op_list_devices",
    feature = "op_list_users",
    feature = "op_list_users_in_group",
    feature = "op_sign_up",
    feature = "op_update_user_attributes"
))]
pub use crate::types::_attribute_type::AttributeType;

#[cfg(any(
    feature = "op_admin_create_user",
    feature = "op_admin_get_user",
    feature = "op_admin_set_user_settings",
    feature = "op_forgot_password",
    feature = "op_get_user",
    feature = "op_get_user_attribute_verification_code",
    feature = "op_list_users",
    feature = "op_list_users_in_group",
    feature = "op_resend_confirmation_code",
    feature = "op_set_user_settings",
    feature = "op_sign_up",
    feature = "op_update_user_attributes"
))]
pub use crate::types::_delivery_medium_type::DeliveryMediumType;

#[cfg(any(
    feature = "op_admin_create_user",
    feature = "op_admin_get_user",
    feature = "op_admin_set_user_settings",
    feature = "op_get_user",
    feature = "op_list_users",
    feature = "op_list_users_in_group",
    feature = "op_set_user_settings"
))]
pub use crate::types::_mfa_option_type::MfaOptionType;

#[cfg(any(
    feature = "op_admin_get_user_auth_factors",
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_get_user_auth_factors",
    feature = "op_update_user_pool"
))]
pub use crate::types::_auth_factor_type::AuthFactorType;

#[cfg(any(
    feature = "op_admin_initiate_auth",
    feature = "op_admin_respond_to_auth_challenge",
    feature = "op_get_tokens_from_refresh_token",
    feature = "op_initiate_auth",
    feature = "op_respond_to_auth_challenge"
))]
pub use crate::types::_new_device_metadata_type::NewDeviceMetadataType;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_auth_event_type::AuthEventType;

#[cfg(any(
    feature = "op_create_managed_login_branding",
    feature = "op_describe_managed_login_branding",
    feature = "op_describe_managed_login_branding_by_client",
    feature = "op_update_managed_login_branding"
))]
pub use crate::types::_asset_type::AssetType;

#[cfg(any(
    feature = "op_create_resource_server",
    feature = "op_describe_resource_server",
    feature = "op_list_resource_servers",
    feature = "op_update_resource_server"
))]
pub use crate::types::_resource_server_scope_type::ResourceServerScopeType;

#[cfg(any(
    feature = "op_create_user_import_job",
    feature = "op_describe_user_import_job",
    feature = "op_list_user_import_jobs",
    feature = "op_start_user_import_job",
    feature = "op_stop_user_import_job"
))]
pub use crate::types::_user_import_job_status_type::UserImportJobStatusType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_password_policy_type::PasswordPolicyType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_sign_in_policy_type::SignInPolicyType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
pub use crate::types::_pre_token_generation_version_config_type::PreTokenGenerationVersionConfigType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
pub use crate::types::_custom_sms_lambda_version_config_type::CustomSmsLambdaVersionConfigType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
pub use crate::types::_custom_email_lambda_version_config_type::CustomEmailLambdaVersionConfigType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
pub use crate::types::_inbound_federation_lambda_type::InboundFederationLambdaType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_verified_attribute_type::VerifiedAttributeType;

#[cfg(any(feature = "op_create_user_pool", feature = "op_describe_user_pool"))]
pub use crate::types::_alias_attribute_type::AliasAttributeType;

#[cfg(any(feature = "op_create_user_pool", feature = "op_describe_user_pool"))]
pub use crate::types::_username_attribute_type::UsernameAttributeType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_default_email_option_type::DefaultEmailOptionType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_email_sending_account_type::EmailSendingAccountType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_get_user_pool_mfa_config",
    feature = "op_set_user_pool_mfa_config",
    feature = "op_update_user_pool"
))]
pub use crate::types::_eums_sms_configuration_type::EumsSmsConfigurationType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_message_template_type::MessageTemplateType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_advanced_security_mode_type::AdvancedSecurityModeType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_advanced_security_additional_flows_type::AdvancedSecurityAdditionalFlowsType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_encryption_key_type::EncryptionKeyType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_issuer_type::IssuerType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools"
))]
pub use crate::types::_status_type::StatusType;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
pub use crate::types::_time_units_type::TimeUnitsType;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
pub use crate::types::_explicit_auth_flows_type::ExplicitAuthFlowsType;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
pub use crate::types::_o_auth_flow_type::OAuthFlowType;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
pub use crate::types::_feature_type::FeatureType;

#[cfg(any(
    feature = "op_create_user_pool_domain",
    feature = "op_describe_user_pool_domain",
    feature = "op_update_user_pool_domain"
))]
pub use crate::types::_security_policy_type::SecurityPolicyType;

#[cfg(any(
    feature = "op_create_user_pool_domain",
    feature = "op_describe_user_pool_domain",
    feature = "op_update_user_pool_domain"
))]
pub use crate::types::_failover_type::FailoverType;

#[cfg(any(
    feature = "op_create_user_pool_replica",
    feature = "op_delete_user_pool_replica",
    feature = "op_list_user_pool_replicas",
    feature = "op_update_user_pool_replica"
))]
pub use crate::types::_replica_status_type::ReplicaStatusType;

#[cfg(any(
    feature = "op_create_user_pool_replica",
    feature = "op_delete_user_pool_replica",
    feature = "op_list_user_pool_replicas",
    feature = "op_update_user_pool_replica"
))]
pub use crate::types::_replica_role_type::ReplicaRoleType;

#[cfg(feature = "op_describe_user_pool_domain")]
pub use crate::types::_domain_status_type::DomainStatusType;

#[cfg(any(feature = "op_get_provisioned_limit", feature = "op_update_provisioned_limit"))]
pub use crate::types::_limit_class::LimitClass;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
pub use crate::types::_user_verification_type::UserVerificationType;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
pub use crate::types::_web_authn_factor_configuration_type::WebAuthnFactorConfigurationType;

#[cfg(feature = "op_list_identity_providers")]
pub use crate::types::_provider_description::ProviderDescription;

#[cfg(feature = "op_list_terms")]
pub use crate::types::_terms_description_type::TermsDescriptionType;

#[cfg(feature = "op_list_user_pool_clients")]
pub use crate::types::_user_pool_client_description::UserPoolClientDescription;

#[cfg(feature = "op_list_user_pools")]
pub use crate::types::_user_pool_description_type::UserPoolDescriptionType;

#[cfg(feature = "op_list_web_authn_credentials")]
pub use crate::types::_web_authn_credential_description::WebAuthnCredentialDescription;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
pub use crate::types::_log_configuration_type::LogConfigurationType;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_compromised_credentials_actions_type::CompromisedCredentialsActionsType;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_notify_configuration_type::NotifyConfigurationType;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_account_takeover_actions_type::AccountTakeoverActionsType;

#[cfg(any(
    feature = "op_add_custom_attributes",
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool"
))]
pub use crate::types::_attribute_data_type::AttributeDataType;

#[cfg(any(
    feature = "op_add_custom_attributes",
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool"
))]
pub use crate::types::_number_attribute_constraints_type::NumberAttributeConstraintsType;

#[cfg(any(
    feature = "op_add_custom_attributes",
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool"
))]
pub use crate::types::_string_attribute_constraints_type::StringAttributeConstraintsType;

#[cfg(any(feature = "op_admin_initiate_auth", feature = "op_admin_respond_to_auth_challenge"))]
pub use crate::types::_http_header::HttpHeader;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_event_type::EventType;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_event_response_type::EventResponseType;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_event_risk_type::EventRiskType;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_event_context_data_type::EventContextDataType;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_event_feedback_type::EventFeedbackType;

#[cfg(any(
    feature = "op_create_managed_login_branding",
    feature = "op_describe_managed_login_branding",
    feature = "op_describe_managed_login_branding_by_client",
    feature = "op_update_managed_login_branding"
))]
pub use crate::types::_asset_category_type::AssetCategoryType;

#[cfg(any(
    feature = "op_create_managed_login_branding",
    feature = "op_describe_managed_login_branding",
    feature = "op_describe_managed_login_branding_by_client",
    feature = "op_update_managed_login_branding"
))]
pub use crate::types::_color_scheme_mode_type::ColorSchemeModeType;

#[cfg(any(
    feature = "op_create_managed_login_branding",
    feature = "op_describe_managed_login_branding",
    feature = "op_describe_managed_login_branding_by_client",
    feature = "op_update_managed_login_branding"
))]
pub use crate::types::_asset_extension_type::AssetExtensionType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
pub use crate::types::_pre_token_generation_lambda_version_type::PreTokenGenerationLambdaVersionType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
pub use crate::types::_custom_sms_sender_lambda_version_type::CustomSmsSenderLambdaVersionType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
pub use crate::types::_custom_email_sender_lambda_version_type::CustomEmailSenderLambdaVersionType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
pub use crate::types::_inbound_federation_lambda_version_type::InboundFederationLambdaVersionType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_advanced_security_enabled_mode_type::AdvancedSecurityEnabledModeType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_recovery_option_type::RecoveryOptionType;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
pub use crate::types::_log_level::LogLevel;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
pub use crate::types::_event_source_name::EventSourceName;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
pub use crate::types::_cloud_watch_logs_configuration_type::CloudWatchLogsConfigurationType;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
pub use crate::types::_s3_configuration_type::S3ConfigurationType;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
pub use crate::types::_firehose_configuration_type::FirehoseConfigurationType;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_event_filter_type::EventFilterType;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_compromised_credentials_event_action_type::CompromisedCredentialsEventActionType;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_notify_email_type::NotifyEmailType;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_account_takeover_action_type::AccountTakeoverActionType;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_risk_decision_type::RiskDecisionType;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_risk_level_type::RiskLevelType;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_challenge_response_type::ChallengeResponseType;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
pub use crate::types::_recovery_option_name_type::RecoveryOptionNameType;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
pub use crate::types::_account_takeover_event_action_type::AccountTakeoverEventActionType;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_challenge_name::ChallengeName;

#[cfg(feature = "op_admin_list_user_auth_events")]
pub use crate::types::_challenge_response::ChallengeResponse;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _account_recovery_setting_type;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
mod _account_takeover_action_type;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
mod _account_takeover_actions_type;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
mod _account_takeover_event_action_type;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
mod _account_takeover_risk_configuration_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _admin_create_user_config_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _advanced_security_additional_flows_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _advanced_security_enabled_mode_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _advanced_security_mode_type;

#[cfg(any(feature = "op_create_user_pool", feature = "op_describe_user_pool"))]
mod _alias_attribute_type;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
mod _analytics_configuration_type;

#[cfg(any(
    feature = "op_admin_initiate_auth",
    feature = "op_admin_respond_to_auth_challenge",
    feature = "op_confirm_forgot_password",
    feature = "op_confirm_sign_up",
    feature = "op_forgot_password",
    feature = "op_initiate_auth",
    feature = "op_resend_confirmation_code",
    feature = "op_respond_to_auth_challenge",
    feature = "op_sign_up"
))]
mod _analytics_metadata_type;

#[cfg(any(
    feature = "op_create_managed_login_branding",
    feature = "op_describe_managed_login_branding",
    feature = "op_describe_managed_login_branding_by_client",
    feature = "op_update_managed_login_branding"
))]
mod _asset_category_type;

#[cfg(any(
    feature = "op_create_managed_login_branding",
    feature = "op_describe_managed_login_branding",
    feature = "op_describe_managed_login_branding_by_client",
    feature = "op_update_managed_login_branding"
))]
mod _asset_extension_type;

#[cfg(any(
    feature = "op_create_managed_login_branding",
    feature = "op_describe_managed_login_branding",
    feature = "op_describe_managed_login_branding_by_client",
    feature = "op_update_managed_login_branding"
))]
mod _asset_type;

#[cfg(any(
    feature = "op_add_custom_attributes",
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool"
))]
mod _attribute_data_type;

#[cfg(any(
    feature = "op_admin_create_user",
    feature = "op_admin_get_device",
    feature = "op_admin_get_user",
    feature = "op_admin_list_devices",
    feature = "op_admin_update_user_attributes",
    feature = "op_get_device",
    feature = "op_get_user",
    feature = "op_list_devices",
    feature = "op_list_users",
    feature = "op_list_users_in_group",
    feature = "op_sign_up",
    feature = "op_update_user_attributes"
))]
mod _attribute_type;

#[cfg(feature = "op_admin_list_user_auth_events")]
mod _auth_event_type;

#[cfg(any(
    feature = "op_admin_get_user_auth_factors",
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_get_user_auth_factors",
    feature = "op_update_user_pool"
))]
mod _auth_factor_type;

#[cfg(any(feature = "op_admin_initiate_auth", feature = "op_initiate_auth"))]
mod _auth_flow_type;

#[cfg(any(
    feature = "op_admin_initiate_auth",
    feature = "op_admin_respond_to_auth_challenge",
    feature = "op_get_tokens_from_refresh_token",
    feature = "op_initiate_auth",
    feature = "op_respond_to_auth_challenge"
))]
mod _authentication_result_type;

#[cfg(feature = "op_admin_list_user_auth_events")]
mod _challenge_name;

#[cfg(any(
    feature = "op_admin_initiate_auth",
    feature = "op_admin_respond_to_auth_challenge",
    feature = "op_initiate_auth",
    feature = "op_respond_to_auth_challenge"
))]
mod _challenge_name_type;

#[cfg(feature = "op_admin_list_user_auth_events")]
mod _challenge_response;

#[cfg(feature = "op_admin_list_user_auth_events")]
mod _challenge_response_type;

#[cfg(feature = "op_get_client_token")]
mod _client_authentication_result_type;

#[cfg(any(
    feature = "op_add_user_pool_client_secret",
    feature = "op_list_user_pool_client_secrets"
))]
mod _client_secret_descriptor_type;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
mod _cloud_watch_logs_configuration_type;

#[cfg(any(
    feature = "op_forgot_password",
    feature = "op_get_user_attribute_verification_code",
    feature = "op_resend_confirmation_code",
    feature = "op_sign_up",
    feature = "op_update_user_attributes"
))]
mod _code_delivery_details_type;

#[cfg(any(
    feature = "op_create_managed_login_branding",
    feature = "op_describe_managed_login_branding",
    feature = "op_describe_managed_login_branding_by_client",
    feature = "op_update_managed_login_branding"
))]
mod _color_scheme_mode_type;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
mod _compromised_credentials_actions_type;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
mod _compromised_credentials_event_action_type;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
mod _compromised_credentials_risk_configuration_type;

#[cfg(any(feature = "op_admin_initiate_auth", feature = "op_admin_respond_to_auth_challenge"))]
mod _context_data_type;

#[cfg(any(
    feature = "op_create_user_pool_domain",
    feature = "op_describe_user_pool_domain",
    feature = "op_update_user_pool_domain"
))]
mod _custom_domain_config_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
mod _custom_email_lambda_version_config_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
mod _custom_email_sender_lambda_version_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
mod _custom_sms_lambda_version_config_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
mod _custom_sms_sender_lambda_version_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _default_email_option_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _deletion_protection_type;

#[cfg(any(
    feature = "op_admin_create_user",
    feature = "op_admin_get_user",
    feature = "op_admin_set_user_settings",
    feature = "op_forgot_password",
    feature = "op_get_user",
    feature = "op_get_user_attribute_verification_code",
    feature = "op_list_users",
    feature = "op_list_users_in_group",
    feature = "op_resend_confirmation_code",
    feature = "op_set_user_settings",
    feature = "op_sign_up",
    feature = "op_update_user_attributes"
))]
mod _delivery_medium_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _device_configuration_type;

#[cfg(any(feature = "op_admin_update_device_status", feature = "op_update_device_status"))]
mod _device_remembered_status_type;

#[cfg(feature = "op_confirm_device")]
mod _device_secret_verifier_config_type;

#[cfg(any(
    feature = "op_admin_get_device",
    feature = "op_admin_list_devices",
    feature = "op_get_device",
    feature = "op_list_devices"
))]
mod _device_type;

#[cfg(feature = "op_describe_user_pool_domain")]
mod _domain_description_type;

#[cfg(feature = "op_describe_user_pool_domain")]
mod _domain_status_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _email_configuration_type;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
mod _email_mfa_config_type;

#[cfg(any(feature = "op_admin_set_user_mfa_preference", feature = "op_set_user_mfa_preference"))]
mod _email_mfa_settings_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _email_sending_account_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _encryption_key_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_get_user_pool_mfa_config",
    feature = "op_set_user_pool_mfa_config",
    feature = "op_update_user_pool"
))]
mod _eums_sms_configuration_type;

#[cfg(feature = "op_admin_list_user_auth_events")]
mod _event_context_data_type;

#[cfg(feature = "op_admin_list_user_auth_events")]
mod _event_feedback_type;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
mod _event_filter_type;

#[cfg(feature = "op_admin_list_user_auth_events")]
mod _event_response_type;

#[cfg(feature = "op_admin_list_user_auth_events")]
mod _event_risk_type;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
mod _event_source_name;

#[cfg(feature = "op_admin_list_user_auth_events")]
mod _event_type;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
mod _explicit_auth_flows_type;

#[cfg(any(
    feature = "op_create_user_pool_domain",
    feature = "op_describe_user_pool_domain",
    feature = "op_update_user_pool_domain"
))]
mod _failover_type;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
mod _feature_type;

#[cfg(any(
    feature = "op_admin_list_user_auth_events",
    feature = "op_admin_update_auth_event_feedback",
    feature = "op_update_auth_event_feedback"
))]
mod _feedback_value_type;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
mod _firehose_configuration_type;

#[cfg(any(
    feature = "op_admin_list_groups_for_user",
    feature = "op_create_group",
    feature = "op_get_group",
    feature = "op_list_groups",
    feature = "op_update_group"
))]
mod _group_type;

#[cfg(any(feature = "op_admin_initiate_auth", feature = "op_admin_respond_to_auth_challenge"))]
mod _http_header;

#[cfg(any(
    feature = "op_create_identity_provider",
    feature = "op_describe_identity_provider",
    feature = "op_get_identity_provider_by_identifier",
    feature = "op_update_identity_provider"
))]
mod _identity_provider_type;

#[cfg(any(
    feature = "op_create_identity_provider",
    feature = "op_describe_identity_provider",
    feature = "op_get_identity_provider_by_identifier",
    feature = "op_list_identity_providers",
    feature = "op_update_identity_provider"
))]
mod _identity_provider_type_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
mod _inbound_federation_lambda_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
mod _inbound_federation_lambda_version_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _issuer_configuration_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _issuer_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _key_configuration_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
mod _lambda_config_type;

#[cfg(any(feature = "op_get_provisioned_limit", feature = "op_update_provisioned_limit"))]
mod _limit_class;

#[cfg(any(feature = "op_get_provisioned_limit", feature = "op_update_provisioned_limit"))]
mod _limit_definition_type;

#[cfg(any(feature = "op_get_provisioned_limit", feature = "op_update_provisioned_limit"))]
mod _limit_type;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
mod _log_configuration_type;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
mod _log_delivery_configuration_type;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
mod _log_level;

#[cfg(any(
    feature = "op_create_managed_login_branding",
    feature = "op_describe_managed_login_branding",
    feature = "op_describe_managed_login_branding_by_client",
    feature = "op_update_managed_login_branding"
))]
mod _managed_login_branding_type;

#[cfg(feature = "op_admin_create_user")]
mod _message_action_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _message_template_type;

#[cfg(any(
    feature = "op_admin_create_user",
    feature = "op_admin_get_user",
    feature = "op_admin_set_user_settings",
    feature = "op_get_user",
    feature = "op_list_users",
    feature = "op_list_users_in_group",
    feature = "op_set_user_settings"
))]
mod _mfa_option_type;

#[cfg(any(
    feature = "op_admin_initiate_auth",
    feature = "op_admin_respond_to_auth_challenge",
    feature = "op_get_tokens_from_refresh_token",
    feature = "op_initiate_auth",
    feature = "op_respond_to_auth_challenge"
))]
mod _new_device_metadata_type;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
mod _notify_configuration_type;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
mod _notify_email_type;

#[cfg(any(
    feature = "op_add_custom_attributes",
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool"
))]
mod _number_attribute_constraints_type;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
mod _o_auth_flow_type;

#[cfg(any(
    feature = "op_create_user_import_job",
    feature = "op_describe_user_import_job",
    feature = "op_list_user_import_jobs",
    feature = "op_start_user_import_job",
    feature = "op_stop_user_import_job"
))]
mod _password_hashing_algorithm_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _password_policy_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
mod _pre_token_generation_lambda_version_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools",
    feature = "op_update_user_pool"
))]
mod _pre_token_generation_version_config_type;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
mod _prevent_user_existence_error_types;

#[cfg(feature = "op_list_identity_providers")]
mod _provider_description;

#[cfg(any(
    feature = "op_admin_disable_provider_for_user",
    feature = "op_admin_link_provider_for_user"
))]
mod _provider_user_identifier_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _recovery_option_name_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _recovery_option_type;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
mod _refresh_token_rotation_type;

#[cfg(any(
    feature = "op_create_user_pool_replica",
    feature = "op_delete_user_pool_replica",
    feature = "op_list_user_pool_replicas",
    feature = "op_update_user_pool_replica"
))]
mod _replica_role_type;

#[cfg(any(
    feature = "op_create_user_pool_replica",
    feature = "op_delete_user_pool_replica",
    feature = "op_list_user_pool_replicas",
    feature = "op_update_user_pool_replica"
))]
mod _replica_status_type;

#[cfg(any(
    feature = "op_create_resource_server",
    feature = "op_describe_resource_server",
    feature = "op_list_resource_servers",
    feature = "op_update_resource_server"
))]
mod _resource_server_scope_type;

#[cfg(any(
    feature = "op_create_resource_server",
    feature = "op_describe_resource_server",
    feature = "op_list_resource_servers",
    feature = "op_update_resource_server"
))]
mod _resource_server_type;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
mod _risk_configuration_type;

#[cfg(feature = "op_admin_list_user_auth_events")]
mod _risk_decision_type;

#[cfg(any(feature = "op_describe_risk_configuration", feature = "op_set_risk_configuration"))]
mod _risk_exception_configuration_type;

#[cfg(feature = "op_admin_list_user_auth_events")]
mod _risk_level_type;

#[cfg(any(
    feature = "op_create_user_pool_domain",
    feature = "op_describe_user_pool_domain",
    feature = "op_update_user_pool_domain"
))]
mod _routing_type;

#[cfg(any(
    feature = "op_get_log_delivery_configuration",
    feature = "op_set_log_delivery_configuration"
))]
mod _s3_configuration_type;

#[cfg(any(
    feature = "op_add_custom_attributes",
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool"
))]
mod _schema_attribute_type;

#[cfg(any(
    feature = "op_create_user_pool_domain",
    feature = "op_describe_user_pool_domain",
    feature = "op_update_user_pool_domain"
))]
mod _security_policy_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _sign_in_policy_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_get_user_pool_mfa_config",
    feature = "op_set_user_pool_mfa_config",
    feature = "op_update_user_pool"
))]
mod _sms_configuration_type;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
mod _sms_mfa_config_type;

#[cfg(any(feature = "op_admin_set_user_mfa_preference", feature = "op_set_user_mfa_preference"))]
mod _sms_mfa_settings_type;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
mod _software_token_mfa_config_type;

#[cfg(any(feature = "op_admin_set_user_mfa_preference", feature = "op_set_user_mfa_preference"))]
mod _software_token_mfa_settings_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_list_user_pools"
))]
mod _status_type;

#[cfg(any(
    feature = "op_add_custom_attributes",
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool"
))]
mod _string_attribute_constraints_type;

#[cfg(feature = "op_list_terms")]
mod _terms_description_type;

#[cfg(any(
    feature = "op_create_terms",
    feature = "op_describe_terms",
    feature = "op_describe_terms_by_client",
    feature = "op_list_terms",
    feature = "op_update_terms"
))]
mod _terms_enforcement_type;

#[cfg(any(
    feature = "op_create_terms",
    feature = "op_describe_terms",
    feature = "op_describe_terms_by_client",
    feature = "op_update_terms"
))]
mod _terms_source_type;

#[cfg(any(
    feature = "op_create_terms",
    feature = "op_describe_terms",
    feature = "op_describe_terms_by_client",
    feature = "op_update_terms"
))]
mod _terms_type;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
mod _time_units_type;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
mod _token_validity_units_type;

#[cfg(any(feature = "op_get_ui_customization", feature = "op_set_ui_customization"))]
mod _ui_customization_type;

#[cfg(feature = "op_update_user_pool_replica")]
mod _update_replica_status_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _user_attribute_update_settings_type;

#[cfg(any(
    feature = "op_confirm_forgot_password",
    feature = "op_confirm_sign_up",
    feature = "op_forgot_password",
    feature = "op_initiate_auth",
    feature = "op_resend_confirmation_code",
    feature = "op_respond_to_auth_challenge",
    feature = "op_sign_up"
))]
mod _user_context_data_type;

#[cfg(any(
    feature = "op_create_user_import_job",
    feature = "op_describe_user_import_job",
    feature = "op_list_user_import_jobs",
    feature = "op_start_user_import_job",
    feature = "op_stop_user_import_job"
))]
mod _user_import_job_status_type;

#[cfg(any(
    feature = "op_create_user_import_job",
    feature = "op_describe_user_import_job",
    feature = "op_list_user_import_jobs",
    feature = "op_start_user_import_job",
    feature = "op_stop_user_import_job"
))]
mod _user_import_job_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _user_pool_add_ons_type;

#[cfg(feature = "op_list_user_pool_clients")]
mod _user_pool_client_description;

#[cfg(any(
    feature = "op_create_user_pool_client",
    feature = "op_describe_user_pool_client",
    feature = "op_update_user_pool_client"
))]
mod _user_pool_client_type;

#[cfg(feature = "op_list_user_pools")]
mod _user_pool_description_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_get_user_pool_mfa_config",
    feature = "op_set_user_pool_mfa_config",
    feature = "op_update_user_pool"
))]
mod _user_pool_mfa_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _user_pool_policy_type;

#[cfg(any(
    feature = "op_create_user_pool_replica",
    feature = "op_delete_user_pool_replica",
    feature = "op_list_user_pool_replicas",
    feature = "op_update_user_pool_replica"
))]
mod _user_pool_replica_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _user_pool_tier_type;

#[cfg(any(feature = "op_create_user_pool", feature = "op_describe_user_pool"))]
mod _user_pool_type;

#[cfg(any(
    feature = "op_admin_create_user",
    feature = "op_admin_get_user",
    feature = "op_list_users",
    feature = "op_list_users_in_group"
))]
mod _user_status_type;

#[cfg(any(
    feature = "op_admin_create_user",
    feature = "op_list_users",
    feature = "op_list_users_in_group"
))]
mod _user_type;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
mod _user_verification_type;

#[cfg(any(feature = "op_create_user_pool", feature = "op_describe_user_pool"))]
mod _username_attribute_type;

#[cfg(any(feature = "op_create_user_pool", feature = "op_describe_user_pool"))]
mod _username_configuration_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _verification_message_template_type;

#[cfg(any(
    feature = "op_create_user_pool",
    feature = "op_describe_user_pool",
    feature = "op_update_user_pool"
))]
mod _verified_attribute_type;

#[cfg(feature = "op_verify_software_token")]
mod _verify_software_token_response_type;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
mod _web_authn_configuration_type;

#[cfg(feature = "op_list_web_authn_credentials")]
mod _web_authn_credential_description;

#[cfg(any(feature = "op_get_user_pool_mfa_config", feature = "op_set_user_pool_mfa_config"))]
mod _web_authn_factor_configuration_type;

#[cfg(any(feature = "op_admin_set_user_mfa_preference", feature = "op_set_user_mfa_preference"))]
mod _web_authn_mfa_settings_type;

/// Builders
pub mod builders;

/// Error types that Amazon Cognito Identity Provider can respond with.
pub mod error;
