// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(any(
    feature = "op_cancel_job",
    feature = "op_cancel_jobs",
    feature = "op_create_compute_environment",
    feature = "op_create_consumable_resource",
    feature = "op_create_job_queue",
    feature = "op_create_quota_share",
    feature = "op_create_scheduling_policy",
    feature = "op_create_service_environment",
    feature = "op_delete_compute_environment",
    feature = "op_delete_consumable_resource",
    feature = "op_delete_job_queue",
    feature = "op_delete_quota_share",
    feature = "op_delete_scheduling_policy",
    feature = "op_delete_service_environment",
    feature = "op_deregister_job_definition",
    feature = "op_describe_compute_environments",
    feature = "op_describe_consumable_resource",
    feature = "op_describe_job_definitions",
    feature = "op_describe_job_queues",
    feature = "op_describe_jobs",
    feature = "op_describe_quota_share",
    feature = "op_describe_scheduling_policies",
    feature = "op_describe_service_environments",
    feature = "op_describe_service_job",
    feature = "op_get_job_queue_snapshot",
    feature = "op_list_consumable_resources",
    feature = "op_list_jobs",
    feature = "op_list_jobs_by_consumable_resource",
    feature = "op_list_quota_shares",
    feature = "op_list_scheduling_policies",
    feature = "op_list_service_jobs",
    feature = "op_list_tags_for_resource",
    feature = "op_register_job_definition",
    feature = "op_submit_job",
    feature = "op_submit_service_job",
    feature = "op_tag_resource",
    feature = "op_terminate_job",
    feature = "op_terminate_jobs",
    feature = "op_terminate_service_job",
    feature = "op_terminate_service_jobs",
    feature = "op_untag_resource",
    feature = "op_update_compute_environment",
    feature = "op_update_consumable_resource",
    feature = "op_update_job_queue",
    feature = "op_update_quota_share",
    feature = "op_update_scheduling_policy",
    feature = "op_update_service_environment",
    feature = "op_update_service_job"
))]
pub(crate) fn type_erase_result<O, E>(
    result: ::std::result::Result<O, E>,
) -> ::std::result::Result<
    ::aws_smithy_runtime_api::client::interceptors::context::Output,
    ::aws_smithy_runtime_api::client::orchestrator::OrchestratorError<
        ::aws_smithy_runtime_api::client::interceptors::context::Error,
    >,
>
where
    O: ::std::fmt::Debug + ::std::marker::Send + ::std::marker::Sync + 'static,
    E: ::std::error::Error + std::fmt::Debug + ::std::marker::Send + ::std::marker::Sync + 'static,
{
    result
        .map(|output| ::aws_smithy_runtime_api::client::interceptors::context::Output::erase(output))
        .map_err(|error| ::aws_smithy_runtime_api::client::interceptors::context::Error::erase(error))
        .map_err(::std::convert::Into::into)
}

#[cfg(any(
    feature = "op_cancel_job",
    feature = "op_cancel_jobs",
    feature = "op_create_compute_environment",
    feature = "op_create_consumable_resource",
    feature = "op_create_job_queue",
    feature = "op_create_quota_share",
    feature = "op_create_scheduling_policy",
    feature = "op_create_service_environment",
    feature = "op_delete_compute_environment",
    feature = "op_delete_consumable_resource",
    feature = "op_delete_job_queue",
    feature = "op_delete_quota_share",
    feature = "op_delete_scheduling_policy",
    feature = "op_delete_service_environment",
    feature = "op_deregister_job_definition",
    feature = "op_describe_compute_environments",
    feature = "op_describe_consumable_resource",
    feature = "op_describe_job_definitions",
    feature = "op_describe_job_queues",
    feature = "op_describe_jobs",
    feature = "op_describe_quota_share",
    feature = "op_describe_scheduling_policies",
    feature = "op_describe_service_environments",
    feature = "op_describe_service_job",
    feature = "op_get_job_queue_snapshot",
    feature = "op_list_consumable_resources",
    feature = "op_list_jobs",
    feature = "op_list_jobs_by_consumable_resource",
    feature = "op_list_quota_shares",
    feature = "op_list_scheduling_policies",
    feature = "op_list_service_jobs",
    feature = "op_list_tags_for_resource",
    feature = "op_register_job_definition",
    feature = "op_submit_job",
    feature = "op_submit_service_job",
    feature = "op_tag_resource",
    feature = "op_terminate_job",
    feature = "op_terminate_jobs",
    feature = "op_terminate_service_job",
    feature = "op_terminate_service_jobs",
    feature = "op_untag_resource",
    feature = "op_update_compute_environment",
    feature = "op_update_consumable_resource",
    feature = "op_update_job_queue",
    feature = "op_update_quota_share",
    feature = "op_update_scheduling_policy",
    feature = "op_update_service_environment",
    feature = "op_update_service_job"
))]
pub fn parse_http_error_metadata(
    _response_status: u16,
    response_headers: &::aws_smithy_runtime_api::http::Headers,
    response_body: &[u8],
) -> ::std::result::Result<
    ::aws_smithy_types::error::metadata::Builder,
    ::aws_smithy_json::deserialize::error::DeserializeError,
> {
    crate::json_errors::parse_error_metadata(response_body, response_headers)
}

#[cfg(feature = "op_cancel_job")]
pub(crate) mod shape_cancel_job;

#[cfg(feature = "op_cancel_jobs")]
pub(crate) mod shape_cancel_jobs;

#[cfg(feature = "op_create_compute_environment")]
pub(crate) mod shape_create_compute_environment;

#[cfg(feature = "op_create_consumable_resource")]
pub(crate) mod shape_create_consumable_resource;

#[cfg(feature = "op_create_job_queue")]
pub(crate) mod shape_create_job_queue;

#[cfg(feature = "op_create_quota_share")]
pub(crate) mod shape_create_quota_share;

#[cfg(feature = "op_create_scheduling_policy")]
pub(crate) mod shape_create_scheduling_policy;

#[cfg(feature = "op_create_service_environment")]
pub(crate) mod shape_create_service_environment;

#[cfg(feature = "op_delete_compute_environment")]
pub(crate) mod shape_delete_compute_environment;

#[cfg(feature = "op_delete_consumable_resource")]
pub(crate) mod shape_delete_consumable_resource;

#[cfg(feature = "op_delete_job_queue")]
pub(crate) mod shape_delete_job_queue;

#[cfg(feature = "op_delete_quota_share")]
pub(crate) mod shape_delete_quota_share;

#[cfg(feature = "op_delete_scheduling_policy")]
pub(crate) mod shape_delete_scheduling_policy;

#[cfg(feature = "op_delete_service_environment")]
pub(crate) mod shape_delete_service_environment;

#[cfg(feature = "op_deregister_job_definition")]
pub(crate) mod shape_deregister_job_definition;

#[cfg(feature = "op_describe_compute_environments")]
pub(crate) mod shape_describe_compute_environments;

#[cfg(feature = "op_describe_consumable_resource")]
pub(crate) mod shape_describe_consumable_resource;

#[cfg(feature = "op_describe_job_definitions")]
pub(crate) mod shape_describe_job_definitions;

#[cfg(feature = "op_describe_job_queues")]
pub(crate) mod shape_describe_job_queues;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_describe_jobs;

#[cfg(feature = "op_describe_quota_share")]
pub(crate) mod shape_describe_quota_share;

#[cfg(feature = "op_describe_scheduling_policies")]
pub(crate) mod shape_describe_scheduling_policies;

#[cfg(feature = "op_describe_service_environments")]
pub(crate) mod shape_describe_service_environments;

#[cfg(feature = "op_describe_service_job")]
pub(crate) mod shape_describe_service_job;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_get_job_queue_snapshot;

#[cfg(feature = "op_list_consumable_resources")]
pub(crate) mod shape_list_consumable_resources;

#[cfg(feature = "op_list_jobs")]
pub(crate) mod shape_list_jobs;

#[cfg(feature = "op_list_jobs_by_consumable_resource")]
pub(crate) mod shape_list_jobs_by_consumable_resource;

#[cfg(feature = "op_list_quota_shares")]
pub(crate) mod shape_list_quota_shares;

#[cfg(feature = "op_list_scheduling_policies")]
pub(crate) mod shape_list_scheduling_policies;

#[cfg(feature = "op_list_service_jobs")]
pub(crate) mod shape_list_service_jobs;

#[cfg(feature = "op_list_tags_for_resource")]
pub(crate) mod shape_list_tags_for_resource;

#[cfg(feature = "op_register_job_definition")]
pub(crate) mod shape_register_job_definition;

#[cfg(feature = "op_submit_job")]
pub(crate) mod shape_submit_job;

#[cfg(feature = "op_submit_service_job")]
pub(crate) mod shape_submit_service_job;

#[cfg(feature = "op_tag_resource")]
pub(crate) mod shape_tag_resource;

#[cfg(feature = "op_terminate_job")]
pub(crate) mod shape_terminate_job;

#[cfg(feature = "op_terminate_jobs")]
pub(crate) mod shape_terminate_jobs;

#[cfg(feature = "op_terminate_service_job")]
pub(crate) mod shape_terminate_service_job;

#[cfg(feature = "op_terminate_service_jobs")]
pub(crate) mod shape_terminate_service_jobs;

#[cfg(feature = "op_untag_resource")]
pub(crate) mod shape_untag_resource;

#[cfg(feature = "op_update_compute_environment")]
pub(crate) mod shape_update_compute_environment;

#[cfg(feature = "op_update_consumable_resource")]
pub(crate) mod shape_update_consumable_resource;

#[cfg(feature = "op_update_job_queue")]
pub(crate) mod shape_update_job_queue;

#[cfg(feature = "op_update_quota_share")]
pub(crate) mod shape_update_quota_share;

#[cfg(feature = "op_update_scheduling_policy")]
pub(crate) mod shape_update_scheduling_policy;

#[cfg(feature = "op_update_service_environment")]
pub(crate) mod shape_update_service_environment;

#[cfg(feature = "op_update_service_job")]
pub(crate) mod shape_update_service_job;

#[cfg(feature = "op_cancel_job")]
pub(crate) mod shape_cancel_job_input;

#[cfg(any(
    feature = "op_cancel_job",
    feature = "op_cancel_jobs",
    feature = "op_create_compute_environment",
    feature = "op_create_consumable_resource",
    feature = "op_create_job_queue",
    feature = "op_create_quota_share",
    feature = "op_create_scheduling_policy",
    feature = "op_create_service_environment",
    feature = "op_delete_compute_environment",
    feature = "op_delete_consumable_resource",
    feature = "op_delete_job_queue",
    feature = "op_delete_quota_share",
    feature = "op_delete_scheduling_policy",
    feature = "op_delete_service_environment",
    feature = "op_deregister_job_definition",
    feature = "op_describe_compute_environments",
    feature = "op_describe_consumable_resource",
    feature = "op_describe_job_definitions",
    feature = "op_describe_job_queues",
    feature = "op_describe_jobs",
    feature = "op_describe_quota_share",
    feature = "op_describe_scheduling_policies",
    feature = "op_describe_service_environments",
    feature = "op_describe_service_job",
    feature = "op_get_job_queue_snapshot",
    feature = "op_list_consumable_resources",
    feature = "op_list_jobs",
    feature = "op_list_jobs_by_consumable_resource",
    feature = "op_list_quota_shares",
    feature = "op_list_scheduling_policies",
    feature = "op_list_service_jobs",
    feature = "op_list_tags_for_resource",
    feature = "op_register_job_definition",
    feature = "op_submit_job",
    feature = "op_submit_service_job",
    feature = "op_tag_resource",
    feature = "op_terminate_job",
    feature = "op_terminate_jobs",
    feature = "op_terminate_service_job",
    feature = "op_terminate_service_jobs",
    feature = "op_untag_resource",
    feature = "op_update_compute_environment",
    feature = "op_update_consumable_resource",
    feature = "op_update_job_queue",
    feature = "op_update_quota_share",
    feature = "op_update_scheduling_policy",
    feature = "op_update_service_environment",
    feature = "op_update_service_job"
))]
pub(crate) fn or_empty_doc(data: &[u8]) -> &[u8] {
    if data.is_empty() {
        b"{}"
    } else {
        data
    }
}

#[cfg(feature = "op_cancel_jobs")]
pub(crate) mod shape_cancel_jobs_input;

#[cfg(any(
    feature = "op_cancel_job",
    feature = "op_cancel_jobs",
    feature = "op_create_compute_environment",
    feature = "op_create_consumable_resource",
    feature = "op_create_job_queue",
    feature = "op_create_quota_share",
    feature = "op_create_scheduling_policy",
    feature = "op_create_service_environment",
    feature = "op_delete_compute_environment",
    feature = "op_delete_consumable_resource",
    feature = "op_delete_job_queue",
    feature = "op_delete_quota_share",
    feature = "op_delete_scheduling_policy",
    feature = "op_delete_service_environment",
    feature = "op_deregister_job_definition",
    feature = "op_describe_compute_environments",
    feature = "op_describe_consumable_resource",
    feature = "op_describe_job_definitions",
    feature = "op_describe_job_queues",
    feature = "op_describe_jobs",
    feature = "op_describe_quota_share",
    feature = "op_describe_scheduling_policies",
    feature = "op_describe_service_environments",
    feature = "op_describe_service_job",
    feature = "op_get_job_queue_snapshot",
    feature = "op_list_consumable_resources",
    feature = "op_list_jobs",
    feature = "op_list_jobs_by_consumable_resource",
    feature = "op_list_quota_shares",
    feature = "op_list_scheduling_policies",
    feature = "op_list_service_jobs",
    feature = "op_list_tags_for_resource",
    feature = "op_register_job_definition",
    feature = "op_submit_job",
    feature = "op_submit_service_job",
    feature = "op_tag_resource",
    feature = "op_terminate_job",
    feature = "op_terminate_jobs",
    feature = "op_terminate_service_job",
    feature = "op_terminate_service_jobs",
    feature = "op_untag_resource",
    feature = "op_update_compute_environment",
    feature = "op_update_consumable_resource",
    feature = "op_update_job_queue",
    feature = "op_update_quota_share",
    feature = "op_update_scheduling_policy",
    feature = "op_update_service_environment",
    feature = "op_update_service_job"
))]
pub(crate) mod shape_client_exception;

#[cfg(feature = "op_create_compute_environment")]
pub(crate) mod shape_create_compute_environment_input;

#[cfg(feature = "op_create_consumable_resource")]
pub(crate) mod shape_create_consumable_resource_input;

#[cfg(feature = "op_create_job_queue")]
pub(crate) mod shape_create_job_queue_input;

#[cfg(feature = "op_create_quota_share")]
pub(crate) mod shape_create_quota_share_input;

#[cfg(feature = "op_create_scheduling_policy")]
pub(crate) mod shape_create_scheduling_policy_input;

#[cfg(feature = "op_create_service_environment")]
pub(crate) mod shape_create_service_environment_input;

#[cfg(feature = "op_delete_compute_environment")]
pub(crate) mod shape_delete_compute_environment_input;

#[cfg(feature = "op_delete_consumable_resource")]
pub(crate) mod shape_delete_consumable_resource_input;

#[cfg(feature = "op_delete_job_queue")]
pub(crate) mod shape_delete_job_queue_input;

#[cfg(feature = "op_delete_quota_share")]
pub(crate) mod shape_delete_quota_share_input;

#[cfg(feature = "op_delete_scheduling_policy")]
pub(crate) mod shape_delete_scheduling_policy_input;

#[cfg(feature = "op_delete_service_environment")]
pub(crate) mod shape_delete_service_environment_input;

#[cfg(feature = "op_deregister_job_definition")]
pub(crate) mod shape_deregister_job_definition_input;

#[cfg(feature = "op_describe_compute_environments")]
pub(crate) mod shape_describe_compute_environments_input;

#[cfg(feature = "op_describe_consumable_resource")]
pub(crate) mod shape_describe_consumable_resource_input;

#[cfg(feature = "op_describe_job_definitions")]
pub(crate) mod shape_describe_job_definitions_input;

#[cfg(feature = "op_describe_job_queues")]
pub(crate) mod shape_describe_job_queues_input;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_describe_jobs_input;

#[cfg(feature = "op_describe_quota_share")]
pub(crate) mod shape_describe_quota_share_input;

#[cfg(feature = "op_describe_scheduling_policies")]
pub(crate) mod shape_describe_scheduling_policies_input;

#[cfg(feature = "op_describe_service_environments")]
pub(crate) mod shape_describe_service_environments_input;

#[cfg(feature = "op_describe_service_job")]
pub(crate) mod shape_describe_service_job_input;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_get_job_queue_snapshot_input;

#[cfg(feature = "op_list_consumable_resources")]
pub(crate) mod shape_list_consumable_resources_input;

#[cfg(feature = "op_list_jobs_by_consumable_resource")]
pub(crate) mod shape_list_jobs_by_consumable_resource_input;

#[cfg(feature = "op_list_jobs")]
pub(crate) mod shape_list_jobs_input;

#[cfg(feature = "op_list_quota_shares")]
pub(crate) mod shape_list_quota_shares_input;

#[cfg(feature = "op_list_scheduling_policies")]
pub(crate) mod shape_list_scheduling_policies_input;

#[cfg(feature = "op_list_service_jobs")]
pub(crate) mod shape_list_service_jobs_input;

#[cfg(feature = "op_register_job_definition")]
pub(crate) mod shape_register_job_definition_input;

#[cfg(any(
    feature = "op_cancel_job",
    feature = "op_cancel_jobs",
    feature = "op_create_compute_environment",
    feature = "op_create_consumable_resource",
    feature = "op_create_job_queue",
    feature = "op_create_quota_share",
    feature = "op_create_scheduling_policy",
    feature = "op_create_service_environment",
    feature = "op_delete_compute_environment",
    feature = "op_delete_consumable_resource",
    feature = "op_delete_job_queue",
    feature = "op_delete_quota_share",
    feature = "op_delete_scheduling_policy",
    feature = "op_delete_service_environment",
    feature = "op_deregister_job_definition",
    feature = "op_describe_compute_environments",
    feature = "op_describe_consumable_resource",
    feature = "op_describe_job_definitions",
    feature = "op_describe_job_queues",
    feature = "op_describe_jobs",
    feature = "op_describe_quota_share",
    feature = "op_describe_scheduling_policies",
    feature = "op_describe_service_environments",
    feature = "op_describe_service_job",
    feature = "op_get_job_queue_snapshot",
    feature = "op_list_consumable_resources",
    feature = "op_list_jobs",
    feature = "op_list_jobs_by_consumable_resource",
    feature = "op_list_quota_shares",
    feature = "op_list_scheduling_policies",
    feature = "op_list_service_jobs",
    feature = "op_list_tags_for_resource",
    feature = "op_register_job_definition",
    feature = "op_submit_job",
    feature = "op_submit_service_job",
    feature = "op_tag_resource",
    feature = "op_terminate_job",
    feature = "op_terminate_jobs",
    feature = "op_terminate_service_job",
    feature = "op_terminate_service_jobs",
    feature = "op_untag_resource",
    feature = "op_update_compute_environment",
    feature = "op_update_consumable_resource",
    feature = "op_update_job_queue",
    feature = "op_update_quota_share",
    feature = "op_update_scheduling_policy",
    feature = "op_update_service_environment",
    feature = "op_update_service_job"
))]
pub(crate) mod shape_server_exception;

#[cfg(feature = "op_submit_job")]
pub(crate) mod shape_submit_job_input;

#[cfg(feature = "op_submit_service_job")]
pub(crate) mod shape_submit_service_job_input;

#[cfg(feature = "op_tag_resource")]
pub(crate) mod shape_tag_resource_input;

#[cfg(feature = "op_terminate_job")]
pub(crate) mod shape_terminate_job_input;

#[cfg(feature = "op_terminate_jobs")]
pub(crate) mod shape_terminate_jobs_input;

#[cfg(feature = "op_terminate_service_job")]
pub(crate) mod shape_terminate_service_job_input;

#[cfg(feature = "op_terminate_service_jobs")]
pub(crate) mod shape_terminate_service_jobs_input;

#[cfg(feature = "op_update_compute_environment")]
pub(crate) mod shape_update_compute_environment_input;

#[cfg(feature = "op_update_consumable_resource")]
pub(crate) mod shape_update_consumable_resource_input;

#[cfg(feature = "op_update_job_queue")]
pub(crate) mod shape_update_job_queue_input;

#[cfg(feature = "op_update_quota_share")]
pub(crate) mod shape_update_quota_share_input;

#[cfg(feature = "op_update_scheduling_policy")]
pub(crate) mod shape_update_scheduling_policy_input;

#[cfg(feature = "op_update_service_environment")]
pub(crate) mod shape_update_service_environment_input;

#[cfg(feature = "op_update_service_job")]
pub(crate) mod shape_update_service_job_input;

#[cfg(feature = "op_submit_job")]
pub(crate) mod shape_array_properties;

#[cfg(feature = "op_cancel_jobs")]
pub(crate) mod shape_cancel_jobs_error_detail_list;

#[cfg(any(
    feature = "op_create_service_environment",
    feature = "op_describe_service_environments",
    feature = "op_update_service_environment"
))]
pub(crate) mod shape_capacity_limit;

#[cfg(feature = "op_describe_compute_environments")]
pub(crate) mod shape_compute_environment_detail_list;

#[cfg(any(
    feature = "op_create_job_queue",
    feature = "op_describe_job_queues",
    feature = "op_update_job_queue"
))]
pub(crate) mod shape_compute_environment_order;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments"
))]
pub(crate) mod shape_compute_resource;

#[cfg(feature = "op_update_compute_environment")]
pub(crate) mod shape_compute_resource_update;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_list_jobs_by_consumable_resource",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_consumable_resource_properties;

#[cfg(feature = "op_list_consumable_resources")]
pub(crate) mod shape_consumable_resource_summary_list;

#[cfg(feature = "op_submit_job")]
pub(crate) mod shape_container_overrides;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_container_properties;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_ecs_properties;

#[cfg(feature = "op_submit_job")]
pub(crate) mod shape_ecs_properties_override;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_ecs_settings;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments"
))]
pub(crate) mod shape_eks_configuration;

#[cfg(feature = "op_update_compute_environment")]
pub(crate) mod shape_eks_configuration_update;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_eks_properties;

#[cfg(feature = "op_submit_job")]
pub(crate) mod shape_eks_properties_override;

#[cfg(any(
    feature = "op_create_scheduling_policy",
    feature = "op_describe_scheduling_policies",
    feature = "op_update_scheduling_policy"
))]
pub(crate) mod shape_fairshare_policy;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_front_of_queue_detail;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_front_of_quota_shares_detail;

#[cfg(feature = "op_describe_job_definitions")]
pub(crate) mod shape_job_definition_list;

#[cfg(any(feature = "op_describe_jobs", feature = "op_submit_job"))]
pub(crate) mod shape_job_dependency;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_job_detail_list;

#[cfg(feature = "op_describe_job_queues")]
pub(crate) mod shape_job_queue_detail_list;

#[cfg(any(
    feature = "op_create_job_queue",
    feature = "op_describe_job_queues",
    feature = "op_update_job_queue"
))]
pub(crate) mod shape_job_state_time_limit_action;

#[cfg(feature = "op_list_jobs")]
pub(crate) mod shape_job_summary_list;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_job_timeout;

#[cfg(any(
    feature = "op_list_consumable_resources",
    feature = "op_list_jobs",
    feature = "op_list_jobs_by_consumable_resource",
    feature = "op_list_service_jobs"
))]
pub(crate) mod shape_key_values_pair;

#[cfg(any(feature = "op_describe_service_job", feature = "op_list_service_jobs"))]
pub(crate) mod shape_latest_service_job_attempt;

#[cfg(feature = "op_list_jobs_by_consumable_resource")]
pub(crate) mod shape_list_jobs_by_consumable_resource_summary_list;

#[cfg(feature = "op_submit_job")]
pub(crate) mod shape_node_overrides;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_node_properties;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_queue_snapshot_utilization_detail;

#[cfg(any(
    feature = "op_create_quota_share",
    feature = "op_describe_quota_share",
    feature = "op_list_quota_shares",
    feature = "op_update_quota_share"
))]
pub(crate) mod shape_quota_share_capacity_limit;

#[cfg(any(feature = "op_describe_quota_share", feature = "op_list_quota_shares"))]
pub(crate) mod shape_quota_share_capacity_limits;

#[cfg(feature = "op_list_quota_shares")]
pub(crate) mod shape_quota_share_list;

#[cfg(any(
    feature = "op_create_scheduling_policy",
    feature = "op_describe_scheduling_policies",
    feature = "op_update_scheduling_policy"
))]
pub(crate) mod shape_quota_share_policy;

#[cfg(any(
    feature = "op_create_quota_share",
    feature = "op_describe_quota_share",
    feature = "op_list_quota_shares",
    feature = "op_update_quota_share"
))]
pub(crate) mod shape_quota_share_preemption_configuration;

#[cfg(any(
    feature = "op_create_quota_share",
    feature = "op_describe_quota_share",
    feature = "op_list_quota_shares",
    feature = "op_update_quota_share"
))]
pub(crate) mod shape_quota_share_resource_sharing_configuration;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_retry_strategy;

#[cfg(feature = "op_describe_scheduling_policies")]
pub(crate) mod shape_scheduling_policy_detail_list;

#[cfg(feature = "op_list_scheduling_policies")]
pub(crate) mod shape_scheduling_policy_listing_detail_list;

#[cfg(feature = "op_describe_service_environments")]
pub(crate) mod shape_service_environment_detail_list;

#[cfg(any(
    feature = "op_create_job_queue",
    feature = "op_describe_job_queues",
    feature = "op_update_job_queue"
))]
pub(crate) mod shape_service_environment_order;

#[cfg(feature = "op_describe_service_job")]
pub(crate) mod shape_service_job_attempt_details;

#[cfg(feature = "op_describe_service_job")]
pub(crate) mod shape_service_job_capacity_usage_detail_list;

#[cfg(any(feature = "op_describe_service_job", feature = "op_submit_service_job"))]
pub(crate) mod shape_service_job_preemption_configuration;

#[cfg(feature = "op_describe_service_job")]
pub(crate) mod shape_service_job_preemption_summary;

#[cfg(any(feature = "op_describe_service_job", feature = "op_submit_service_job"))]
pub(crate) mod shape_service_job_retry_strategy;

#[cfg(feature = "op_list_service_jobs")]
pub(crate) mod shape_service_job_summary_list;

#[cfg(any(feature = "op_describe_service_job", feature = "op_submit_service_job"))]
pub(crate) mod shape_service_job_timeout;

#[cfg(any(
    feature = "op_cancel_jobs",
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition",
    feature = "op_terminate_jobs",
    feature = "op_terminate_service_jobs",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_string_list;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_describe_consumable_resource",
    feature = "op_describe_job_definitions",
    feature = "op_describe_job_queues",
    feature = "op_describe_jobs",
    feature = "op_describe_quota_share",
    feature = "op_describe_scheduling_policies",
    feature = "op_describe_service_environments",
    feature = "op_describe_service_job",
    feature = "op_list_tags_for_resource"
))]
pub(crate) mod shape_tagris_tags_map;

#[cfg(feature = "op_terminate_jobs")]
pub(crate) mod shape_terminate_jobs_error_detail_list;

#[cfg(feature = "op_terminate_service_jobs")]
pub(crate) mod shape_terminate_service_jobs_error_detail_list;

#[cfg(any(
    feature = "op_describe_compute_environments",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_update_policy;

#[cfg(feature = "op_cancel_jobs")]
pub(crate) mod shape_cancel_jobs_error_detail;

#[cfg(feature = "op_describe_compute_environments")]
pub(crate) mod shape_compute_environment_detail;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_compute_scaling_policy;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_list_jobs_by_consumable_resource",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_consumable_resource_requirement;

#[cfg(feature = "op_list_consumable_resources")]
pub(crate) mod shape_consumable_resource_summary;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_ec2_configuration;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_ecs_task_properties;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_eks_access_entry;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_eks_pod_properties;

#[cfg(feature = "op_submit_job")]
pub(crate) mod shape_eks_pod_properties_override;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_ephemeral_storage;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_evaluate_on_exit;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_fairshare_utilization_detail;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_fargate_platform_configuration;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_front_of_queue_job_summary_list;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_front_of_quota_shares_job_summary_map;

#[cfg(feature = "op_describe_job_definitions")]
pub(crate) mod shape_job_definition;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_job_detail;

#[cfg(feature = "op_describe_job_queues")]
pub(crate) mod shape_job_queue_detail;

#[cfg(feature = "op_list_jobs")]
pub(crate) mod shape_job_summary;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_key_value_pair;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_launch_template_specification;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_linux_parameters;

#[cfg(feature = "op_list_jobs_by_consumable_resource")]
pub(crate) mod shape_list_jobs_by_consumable_resource_summary;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_log_configuration;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments"
))]
pub(crate) mod shape_managed_instances_provider;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_mount_point;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_network_configuration;

#[cfg(feature = "op_submit_job")]
pub(crate) mod shape_node_property_override;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_node_range_property;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_queue_snapshot_capacity_usage_list;

#[cfg(feature = "op_list_quota_shares")]
pub(crate) mod shape_quota_share_detail;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_quota_share_utilization_detail;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_repository_credentials;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_resource_requirement;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_runtime_platform;

#[cfg(feature = "op_describe_scheduling_policies")]
pub(crate) mod shape_scheduling_policy_detail;

#[cfg(feature = "op_list_scheduling_policies")]
pub(crate) mod shape_scheduling_policy_listing_detail;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_secret;

#[cfg(feature = "op_describe_service_environments")]
pub(crate) mod shape_service_environment_detail;

#[cfg(feature = "op_describe_service_job")]
pub(crate) mod shape_service_job_attempt_detail;

#[cfg(feature = "op_describe_service_job")]
pub(crate) mod shape_service_job_capacity_usage_detail;

#[cfg(any(feature = "op_describe_service_job", feature = "op_submit_service_job"))]
pub(crate) mod shape_service_job_evaluate_on_exit;

#[cfg(any(feature = "op_describe_service_job", feature = "op_submit_service_job"))]
pub(crate) mod shape_service_job_evaluate_on_exit_list;

#[cfg(feature = "op_describe_service_job")]
pub(crate) mod shape_service_job_recent_preempted_attempt_list;

#[cfg(feature = "op_list_service_jobs")]
pub(crate) mod shape_service_job_summary;

#[cfg(any(feature = "op_describe_service_job", feature = "op_list_service_jobs"))]
pub(crate) mod shape_service_resource_id;

#[cfg(any(
    feature = "op_create_scheduling_policy",
    feature = "op_describe_scheduling_policies",
    feature = "op_update_scheduling_policy"
))]
pub(crate) mod shape_share_attributes;

#[cfg(feature = "op_submit_job")]
pub(crate) mod shape_task_properties_override;

#[cfg(feature = "op_terminate_jobs")]
pub(crate) mod shape_terminate_jobs_error_detail;

#[cfg(feature = "op_terminate_service_jobs")]
pub(crate) mod shape_terminate_service_jobs_error_detail;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_ulimit;

#[cfg(feature = "op_update_compute_environment")]
pub(crate) mod shape_update_managed_instances_provider_configuration;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_volume;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_array_properties_detail;

#[cfg(feature = "op_list_jobs")]
pub(crate) mod shape_array_properties_summary;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_attempt_details;

#[cfg(feature = "op_describe_service_environments")]
pub(crate) mod shape_capacity_limits;

#[cfg(feature = "op_describe_job_queues")]
pub(crate) mod shape_compute_environment_orders;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_container_detail;

#[cfg(feature = "op_list_jobs")]
pub(crate) mod shape_container_summary;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_device;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_ecs_properties_detail;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_efs_volume_configuration;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_eks_attempt_details;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_eks_container;

#[cfg(feature = "op_submit_job")]
pub(crate) mod shape_eks_container_override;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_eks_metadata;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_eks_properties_detail;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_eks_volume;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_fairshare_capacity_utilization_list;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_front_of_queue_job_summary;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_front_of_quota_share_job_summary_list;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_host;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_image_pull_secret;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_infrastructure_optimization;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments"
))]
pub(crate) mod shape_instance_launch_template;

#[cfg(feature = "op_update_compute_environment")]
pub(crate) mod shape_instance_launch_template_update;

#[cfg(feature = "op_list_jobs")]
pub(crate) mod shape_job_capacity_usage_summary_list;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_job_dependency_list;

#[cfg(feature = "op_describe_job_queues")]
pub(crate) mod shape_job_state_time_limit_actions;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_launch_template_specification_override;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_node_details;

#[cfg(feature = "op_list_jobs")]
pub(crate) mod shape_node_properties_summary;

#[cfg(any(feature = "op_describe_job_definitions", feature = "op_describe_jobs"))]
pub(crate) mod shape_parameters_map;

#[cfg(any(feature = "op_describe_job_definitions", feature = "op_describe_jobs"))]
pub(crate) mod shape_platform_capability_list;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_queue_snapshot_capacity_usage;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_quota_share_capacity_utilization_list;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_s3_files_volume_configuration;

#[cfg(feature = "op_describe_job_queues")]
pub(crate) mod shape_service_environment_orders;

#[cfg(feature = "op_list_service_jobs")]
pub(crate) mod shape_service_job_capacity_usage_summary_list;

#[cfg(feature = "op_describe_service_job")]
pub(crate) mod shape_service_job_preempted_attempt;

#[cfg(feature = "op_submit_job")]
pub(crate) mod shape_task_container_overrides;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_task_container_properties;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_tmpfs;

#[cfg(any(feature = "op_describe_jobs", feature = "op_list_jobs"))]
pub(crate) mod shape_array_job_status_summary;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_attempt_detail;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_capacity_reservation_request;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_list_jobs_by_consumable_resource",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_consumable_resource_list;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments"
))]
pub(crate) mod shape_ec2_configuration_list;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_efs_authorization_config;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_eks_attempt_detail;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_eks_container_environment_variable;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_eks_container_resource_requirements;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_eks_container_security_context;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_eks_container_volume_mount;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_eks_empty_dir;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_eks_host_path;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_eks_persistent_volume_claim;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_eks_pod_properties_detail;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_eks_secret;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_environment_variables;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_evaluate_on_exit_list;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_fairshare_capacity_utilization;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_firelens_configuration;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_front_of_quota_share_job_summary;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_instance_requirements_request;

#[cfg(feature = "op_list_jobs")]
pub(crate) mod shape_job_capacity_usage_summary;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_list_ecs_task_details;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_list_ecs_task_properties;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_managed_instances_local_storage_configuration;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_managed_instances_network_configuration;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_managed_instances_storage_configuration;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_mount_points;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_network_interface_list;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_node_range_properties;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_quota_share_capacity_utilization;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_resource_requirements;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_secret_list;

#[cfg(feature = "op_list_service_jobs")]
pub(crate) mod shape_service_job_capacity_usage_summary;

#[cfg(any(
    feature = "op_create_scheduling_policy",
    feature = "op_describe_scheduling_policies",
    feature = "op_update_scheduling_policy"
))]
pub(crate) mod shape_share_attributes_list;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments"
))]
pub(crate) mod shape_tags_map;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_task_container_dependency;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_ulimits;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_volumes;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_attempt_container_detail;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_devices_list;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_ecs_task_details;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_eks_attempt_container_details;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_eks_container_details;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_eks_containers;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_eks_volumes;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_fairshare_capacity_usage_list;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_image_pull_secrets;

#[cfg(any(
    feature = "op_create_compute_environment",
    feature = "op_describe_compute_environments",
    feature = "op_update_compute_environment"
))]
pub(crate) mod shape_launch_template_specification_override_list;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_list_attempt_ecs_task_details;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_log_configuration_options_map;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_network_interface;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_quota_share_capacity_usage_list;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_tmpfs_list;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_attempt_ecs_task_details;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_eks_annotations_map;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_eks_attempt_container_detail;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_eks_container_detail;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_eks_labels_map;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_fairshare_capacity_usage;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_list_task_container_details;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_list_task_container_properties;

#[cfg(feature = "op_get_job_queue_snapshot")]
pub(crate) mod shape_quota_share_capacity_usage;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_device_cgroup_permissions;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_eks_container_environment_variables;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_eks_container_volume_mounts;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_list_attempt_task_container_details;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_task_container_details;

#[cfg(feature = "op_describe_jobs")]
pub(crate) mod shape_attempt_task_container_details;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_eks_limits;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition",
    feature = "op_submit_job"
))]
pub(crate) mod shape_eks_requests;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_task_container_dependency_list;

#[cfg(any(
    feature = "op_describe_job_definitions",
    feature = "op_describe_jobs",
    feature = "op_register_job_definition"
))]
pub(crate) mod shape_firelens_configuration_options_map;
